---
title: "scrbseq"
output: html_document
---

## Prepare session

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(echo = TRUE)
path <- '~/Desktop/scrbseq'
dir.create(path = path, recursive = T)
knitr::opts_knit$set(root.dir = path, collapse = T, comment = '#>')
```

```{r loadlibraries, echo=FALSE}
library(scater)
library(tibble)
library(ggpubr)
library(dplyr)
library(data.table)
library(SingleCellExperiment)
library(openxlsx)
library(Seurat)
library(cowplot)
library(pheatmap)

# Define custom themes for ggplot
theme_custom <- theme(axis.text.x = element_text(size = 12.8, color = 'black'),
                      axis.text.y = element_text(size = 12.8, color = 'black'), 
                      axis.title.x = element_text(size = 16, margin = margin(6,0,0,0)), 
                      axis.title.y = element_text(size = 16, margin = margin(0,8,0,0)),
                      plot.title = element_text(size = 16, face = 'plain', hjust = 0.5, margin = margin(5,0,10,0)),
                      plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(0,0,10,0)), 
                      axis.ticks.x = element_line(size = 0.4, colour = 'black'), 
                      axis.ticks.y = element_line(size = 0.4, colour = 'black'),
                      axis.line = element_blank(), 
                      panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank(),
                      panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(),
                      panel.border = element_rect(colour = 'black', size = 0.8, fill = NA),
                      panel.background = element_rect(colour = NA, fill = NA), 
                      strip.text.x = element_text(size = 16, face = 'plain', margin = margin(0,0,5,0) ), 
                      strip.text.y = element_text(size = 16, face = 'plain', margin = margin(0,0,0,5) ), 
                      strip.background = element_blank(), 
                      legend.key = element_blank(), legend.key.size = unit(0.5,'cm'),
                      legend.text = element_text(size = 12.8), 
                      legend.title = element_text(size = 12.8),
                      plot.background = element_rect(colour = NA, fill = NA), aspect.ratio = 1)
theme_custom2 <- theme(axis.text.x = element_blank(), 
                       axis.text.y = element_blank(), 
                       axis.title.x = element_text(size = 16, margin = margin(4,0,0,0)), 
                       axis.title.y = element_text(size = 16, margin = margin(0,4,0,0)),
                       plot.title = element_text(size = 16, face = 'plain', hjust = 0.5, margin = margin(5,0,10,0)),
                       plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(0,0,10,0)), 
                       axis.ticks.x = element_blank(), 
                       axis.ticks.y = element_blank(), 
                       axis.line = element_blank(), 
                       panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank(),
                       panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(),
                       panel.border = element_rect(colour = 'grey80', size = 0.8, fill = NA),
                       panel.background = element_rect(colour = NA, fill = NA),
                       strip.text.x = element_text(size = 16, face = 'plain', margin = margin(0,0,5,0) ), 
                       strip.text.y = element_text(size = 16, face = 'plain', margin = margin(0,0,0,5) ), 
                       strip.background = element_blank(), 
                       legend.key = element_blank(), legend.key.size = unit(0.5,'cm'),
                       legend.text = element_text(size = 12.8), 
                       legend.title = element_text(size = 12.8),
                       plot.background = element_rect(colour = NA, fill = NA), aspect.ratio = 1)

# Function to save plots with same size
grid <- function(data, layout=rbind(c(1,1,1,1,2,2,3))) {
  gridExtra::grid.arrange(grobs = list(data + guides(color = 'none', fill = 'none', size = 'none'), 
                                       cowplot::get_legend(data)), ncol = 2, layout_matrix = layout, 
                          top = grid::textGrob('', gp = grid::gpar(fontsize = 16, font = 2)))
}
```

-------------------------------------------------------------------------------------------------------------------

## Data pre-processing

```{r load raw data}
# Download pre-processed data from GEO SuperSeries and place at '~/Desktop/bulk/'
download.file(url='https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE200359&format=file&file=GSE200359%5FRun30%5Fcounts%2Ecsv%2Egz', destfile=paste0(path, '/GSE200359_Run30_counts.csv.gz'))

# Prepare data
Raw_data <- read.csv(gzfile(paste0(path, '/GSE200359_Run30_counts.csv.gz')), header = T, row.names = 1, sep = ',', stringsAsFactors = F)

# Filtering
Raw_data <- Raw_data[rowSums(Raw_data) > 1, ]

# Metadata
Design <- data.frame(row.names = colnames(Raw_data),
                    cell_name = colnames(Raw_data),
                    cell_type = as.character(lapply(colnames(Raw_data), function(x) unlist(strsplit(x, '[.]'))[2])),
                    stringsAsFactors = F)

# Create sce
sce = SingleCellExperiment(assays = list(counts = as.matrix(Raw_data)), colData = Design) %>% calculateQCMetrics()
cell_info = as.data.frame(colData(sce))

# Calculate percentage of mito-genes, ribo-genes
mito.genes <- grep(pattern = "^mt-", x = rownames(Raw_data), value = TRUE)
ribo.genes <- grep(pattern = "^Rpl", x = rownames(Raw_data), value = TRUE)
cell_info$mito_percentage <- Matrix::colSums(Raw_data[mito.genes, ]) / Matrix::colSums(Raw_data)
cell_info$ribo_percentage <- Matrix::colSums(Raw_data[ribo.genes, ]) / Matrix::colSums(Raw_data)
#write.xlsx(cell_info, paste0(path, '/raw_cell_info.xlsx'))

# filter by GENE > 500 and UMI > 5000
selected_cells = cell_info %>% dplyr::filter(total_features_by_counts > 500 & total_counts > 5000)
selected_expr = Raw_data[,colnames(Raw_data) %in% as.character(selected_cells$cell_name)]
```

-------------------------------------------------------------------------------------------------------------------

## Seurat clustering

```{r}
# reinstall seurat package version 2.3.4

# Create seurat object
SC3_Seurat = CreateSeuratObject(raw.data = as.data.frame(selected_expr), normalization.method = 'LogNormalize', meta.data = 
                                  data.frame(row.names = colnames(selected_expr),
                                             cell_type = Design[colnames(selected_expr),'cell_type']))

# Find variable features
SC3_Seurat <- FindVariableGenes(object = SC3_Seurat, mean.function = ExpMean, dispersion.function = LogVMR,
                                x.low.cutoff = 0.0125, x.high.cutoff = 3,
                                y.cutoff = 0.5, do.plot = F)

# Scale data
SC3_Seurat <- ScaleData(SC3_Seurat)

# Run PCA
SC3_Seurat <- RunPCA(object = SC3_Seurat, pcs.compute = 20, pc.genes = SC3_Seurat@var.genes, do.print = T)
SC3_Seurat <- FindClusters(object = SC3_Seurat, reduction.type = "pca", 
                       dims.use = 1:10, k.param = 200, resolution = 0.8,
                       print.output = 0, save.SNN = F, n.iter = 1000, n.start = 1000)
#saveRDS(SC3_Seurat, paste0(path, '/seurat_obj.rds'))
```

-------------------------------------------------------------------------------------------------------------------

## Dimensional reduction Visualization

```{r}
SC3_Seurat <- RunTSNE(object = SC3_Seurat, reduction.use = "pca", dims.use = 1:10, nthreads = 4, reduction.name = "tSNE", reduction.key = "tSNE_", max_iter = 2000)
SC3_Seurat <- RunUMAP(object = SC3_Seurat, reduction.use = "pca", dims.use = 1:10, min_dist = 0.75)
##Seurat3
#SC3_Seurat <- UpdateSeuratObject(SC3_Seurat)
#SC3_Seurat <- RunTSNE(object = SC3_Seurat, reduction = "pca", dims = 1:10, nthreads = 4, reduction.name = "tSNE", reduction.key = "tSNE_", max_iter = 2000)
#SC3_Seurat <- RunUMAP(object = SC3_Seurat, reduction = "pca", dims = 1:10, min_dist = 0.75)

# Rename clusters
SC3_Seurat@ident <- factor(plyr::mapvalues(SC3_Seurat@ident, from = 0:4, to = c(1,5,4,3,2) ), levels=1:5)
#Idents(SC3_Seurat) <- factor(plyr::mapvalues(Idents(SC3_Seurat), from = 0:4, to = c(1,5,4,3,2) ), levels=1:5) #Seurat3

# Plot tSNE
colors <- c('#8DC73F','#25CED1','#FF8A5B', '#EA526F','#FFCA04','#731DD8', '#D5A18E')
condition_color = c('#BF4342', '#033F63')
#tmp <- as.factor(as.numeric(SC3_Seurat@ident))
##tmp <- as.factor(as.numeric(Idents(SC3_Seurat))) #Seurat3
#names(tmp) <- SC3_Seurat@cell.names
#SC3_Seurat@ident <- tmp

p1 <- DimPlot(object = SC3_Seurat, reduction.use = "tSNE", do.return = TRUE, group.by = "ident", vector.friendly = TRUE, pt.size = 5, cols.use = colors) + ggtitle("tSNE") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2

p2 <- DimPlot(object = SC3_Seurat, reduction.use = "umap", do.return = TRUE, vector.friendly = TRUE, pt.size = 4, cols.use = colors) + ggtitle("UMAP") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2

p3 <- DimPlot(object = SC3_Seurat, reduction.use = "tSNE", do.return = TRUE, group.by = 'cell_type', cols.use = condition_color, vector.friendly = TRUE, pt.size = 5) + ggtitle("Cell type") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2

p4 <- DimPlot(object = SC3_Seurat, reduction.use = "umap", do.return = TRUE, group.by = 'cell_type', cols.use = condition_color, vector.friendly = TRUE, pt.size = 4) + ggtitle("Cell Type") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2

##Seurat3
#p1 <- DimPlot(object = SC3_Seurat, reduction = "tSNE", group.by = "ident", pt.size = 1, cols = colors, label = T, 
#              label.size = 5) + ggtitle("tSNE") + theme(plot.title = element_text(hjust = 0.5), 
#                                                        text = element_text(size = 20)) + theme_custom2
#
#p2 <- DimPlot(object = SC3_Seurat, reduction = "umap", pt.size = 1, cols = colors) + ggtitle("UMAP") + theme(plot.title = #element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2
#
#p3 <- DimPlot(object = SC3_Seurat, reduction = "tSNE", group.by = 'cell_type', cols = condition_color, pt.size = 1) + #ggtitle("Cell type") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2
#
#p4 <- DimPlot(object = SC3_Seurat, reduction = "umap", do.return = TRUE, group.by = 'cell_type', cols = condition_color, #pt.size = 1) + ggtitle("Cell Type") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20))

# Save umap plots
ggsave(plot = grid(p1,rbind(c(1,1,1,1,1,1,1,1,1,2,3))), file = paste0(path, '/Fig5Al.pdf'), height = 4.2, width = 4.5)
ggsave(plot = grid(p3,rbind(c(1,1,1,1,1,1,1,1,1,2,3))), file = paste0(path, '/Fig5Ar.pdf'), height = 4.2, width = 4.5)
```

-------------------------------------------------------------------------------------------------------------------

## Feature plots

```{r}
# Genelists
genes <- list(a=c('Tcf7','Ccr7','Sell','Il7r','Slamf6','Bcl2','Stat5a','Id3'), 
              b=c('Gzma','Gzmb','Id2','Prf1'), 
              c=c('Mki67','Dhodh'),
              d=c('Myc','Hdac1','Hdac7','Hif1a','Hif1an','Xbp1'))

# Plot expression
fp1 <- FeaturePlot(SC3_Seurat, genes$a, dark.theme = F, reduction.use = 'tSNE', pt.size = 5, vector.friendly = T, nCol = 4, cols.use = c('grey', 'red'), no.legend = F, no.axes = T, do.return = T) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2
fp2 <- FeaturePlot(SC3_Seurat, genes$b, dark.theme = F, reduction.use = 'tSNE', pt.size = 5, vector.friendly = T, nCol = 2, cols.use = c('grey', 'red'), no.legend = F, no.axes = T, do.return = T) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2
fp3 <- FeaturePlot(SC3_Seurat, genes$c, dark.theme = F, reduction.use = 'tSNE', pt.size = 5, vector.friendly = T, nCol = 1, cols.use = c('grey', 'red'), no.legend = F, no.axes = T, do.return = T) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2
fp4 <- FeaturePlot(SC3_Seurat, genes$d, dark.theme = F, reduction.use = 'tSNE', pt.size = 5, vector.friendly = T, nCol = 1, cols.use = c('grey', 'red'), no.legend = F, no.axes = T, do.return = T) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2

##Seurat3
fp1 <- FeaturePlot(SC3_Seurat, features = genes$a, reduction = 'tSNE', pt.size = 1, 
                   ncol = 4, cols = c('grey', 'red'), combine = F)
fp1 <- lapply(1:length(fp1), function(x) fp1[[x]] + 
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                      panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2 )
fp1 <- gridExtra::grid.arrange(grobs = fp1, ncol=4)
fp2 <- FeaturePlot(SC3_Seurat, features = genes$b, reduction = 'tSNE', pt.size = 1, 
                   ncol = 2, cols = c('grey', 'red'), combine = F)
fp2 <- lapply(1:length(fp2), function(x) fp2[[x]] + 
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                      panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2 )
fp2 <- gridExtra::grid.arrange(grobs = fp2, ncol=2)
fp3 <- FeaturePlot(SC3_Seurat, features = genes$c, reduction = 'tSNE', pt.size = 1, 
                   ncol = 2, cols = c('grey', 'red'), combine = F)
fp3 <- lapply(1:length(fp3), function(x) fp3[[x]] + 
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                      panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2 )
fp3 <- gridExtra::grid.arrange(grobs = fp3, ncol=1)
fp4 <- FeaturePlot(SC3_Seurat, features = genes$d, reduction = 'tSNE', pt.size = 1, 
                   ncol = 2, cols = c('grey', 'red'), combine = F)
fp4 <- lapply(1:length(fp4), function(x) fp4[[x]] + 
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                      panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2 )
fp4 <- gridExtra::grid.arrange(grobs = fp4, ncol=1)

# Save umap plots
ggsave(plot = fp1, file = paste0(path, '/Fig5Cl.pdf'), height = 7, width = 15)
ggsave(plot = fp2, file = paste0(path, '/Fig5Cr.pdf'), height = 7, width = 8)
ggsave(plot = fp3, file = paste0(path, '/Fig6A.pdf'), height = 7, width = 4.2)
ggsave(plot = fp4, file = paste0(path, '/ExtData9Bl.pdf'), height = 20.5, width = 4.2)
```

-------------------------------------------------------------------------------------------------------------------

## Bar plots

```{r}
##Seurat3
# Function to draw dotplot
col <- list(hm=colorRampPalette(c('#133d67','#2166AC','#90b2d5','#d2e0ee','grey90','#efd0d4','#d88b95','#B2182B','#590c15'))(41), hm2=colorRampPalette(c('grey90','#efd0d4','#d88b95','#B2182B','#590c15'))(41))
dotplot <- function(object=bd, sel=genes$sel1, cl=F, scale=T, b=15, gr=NULL, sample='OT1 cells', subtitle='Expression by cluster',smax=100) {
  sel <- sel[sel %in% rownames(object)]
  dt <- DotPlot(object, assay = 'RNA', features = sel, cluster.idents = cl, scale.max=smax, group.by = gr)$data
  if(!is.null(gr)) dt <- cbind(dt, reshape2::colsplit(dt$id, pattern = '_', names = c('condition','cluster')))
  if(scale) l <- list(a=-1.5,b=1.5) else l <- list(a=0,b=b)
  #dtI <- transform(reshape2::dcast(dt, features.plot ~ id, value.var='avg.exp'), row.names = features.plot)[,-1]
  #sel.order <- hclust(d = dist(x = scale(dtI)))
  #sel.order <- callback(sel.order, dtI)
  #dt$features.plot <- factor(dt$features.plot, levels = rownames(dtI)[sel.order$order] )
  p <- ggplot(dt, aes(if(!is.null(gr)) factor(cluster, levels=rev(unique(cluster))) else factor(id, levels=rev(unique(id))), features.plot, color=if(scale) avg.exp.scaled else avg.exp, size=pct.exp)) + 
    geom_point() + scale_x_discrete('cluster') + scale_y_discrete('') + coord_flip() + 
    scale_color_gradientn(ifelse(scale,'z-score','Avg. exp.'), colours = if(scale) col$hm else col$hm2, oob = scales::squish, 
                          limits = c(l$a,l$b), breaks = seq(l$a,l$b, length.out = 3)) + 
    scale_size_continuous('Pct. exp', limits = c(0,smax), breaks = seq(0,smax,smax/4), range = c(0,6)) + 
    ggtitle(gsub('_',' ',sample), subtitle = subtitle) + theme_custom + 
    #facet_grid(.~factor(celltype, levels = levels(object$celltype)), scales = 'free', space = 'free') + 
    facet_grid(features.plot~., scales = 'free', space = 'free') + 
    theme(aspect.ratio = length(unique(dt$id)) / length(sel), #aspect.ratio = length(sel) / length(unique(dt$id)),  
          strip.text = element_text(size = 12.8, face = 'plain', angle=0, vjust=0, hjust=0.5, margin = margin(5,0,5,0)), 
          #axis.text.x = element_text(size = 12.8, color = 'black', angle = 0, vjust = 1, hjust = 0.5))
          axis.text.x = element_text(size = 12.8, color = 'black', angle = 90, vjust = 0.5, hjust = 1))
  if(!is.null(gr)) p + facet_grid(factor(condition, levels = levels(bd$all$condition))~., scales = 'free', space = 'free') else p
}

# Function to rescale
rescale <- function(scores,to=c(0,1)) if(any(scores > 1)) scales::rescale(scores, to=to) else scores

# Extract data
df.pct <- dotplot(object = SC3_Seurat, sel = unlist(genes[c('c','d')]), gr=NULL)$data
df.pct <- dplyr::bind_rows(Map(x=unique(df.pct$features.plot), function(x) {
  dfI <- df.pct %>% filter(features.plot %in% x) %>% mutate(scaled = rescale(avg.exp))
  #dfI <- cbind(dfI, reshape2::colsplit(dfI$id, pattern = '_', names = c('condition','cluster')))
  return(dfI)
}))

# Plot bar plot
bp3 <- ggplot(df.pct %>% filter(features.plot %in% genes$c), aes(x = id, y = pct.exp)) + 
  geom_bar(aes(fill = scaled), color='black', size=0.5, stat = 'identity', width = 0.7, alpha = 1) + 
  scale_x_discrete('cluster') + 
  scale_y_continuous('% expressing cells', limits=c(0,100), breaks = seq(0,100,20), expand = c(0,0)) + 
  scale_fill_gradientn('Exp.', colours = col$hm2, oob = scales::squish, 
                       limits = c(0,1), breaks = seq(0,1, length.out = 2), labels = c('min','max')) + 
  facet_grid(features.plot~., scales = 'free', space = 'free') +
  ggtitle('OT1 cells', subtitle = 'Upstream regulators') + theme_custom + #theme(aspect.ratio = NULL)
  theme(axis.text.x = element_text(size = 12.8, color = 'black', angle = 0, vjust = 0, hjust = 0.5), aspect.ratio = NULL, panel.spacing = unit(0.7, "lines"))
bp4 <- ggplot(df.pct %>% filter(features.plot %in% genes$d), aes(x = id, y = pct.exp)) + 
  geom_bar(aes(fill = scaled), color='black', size=0.5, stat = 'identity', width = 0.7, alpha = 1) + 
  scale_x_discrete('cluster') + 
  scale_y_continuous('% expressing cells', limits=c(0,100), breaks = seq(0,100,20), expand = c(0,0)) + 
  scale_fill_gradientn('Exp.', colours = col$hm2, oob = scales::squish, 
                       limits = c(0,1), breaks = seq(0,1, length.out = 2), labels = c('min','max')) + 
  facet_grid(features.plot~., scales = 'free', space = 'free') +
  ggtitle('OT1 cells', subtitle = 'Upstream regulators') + theme_custom + #theme(aspect.ratio = NULL)
  theme(axis.text.x = element_text(size = 12.8, color = 'black', angle = 0, vjust = 0, hjust = 0.5), aspect.ratio = NULL, panel.spacing = unit(0.7, "lines"))

# Save umap plots
ggsave(plot = bp3, file = paste0(path, '/Fig6B.pdf'), height = 5.5, width = 4)
ggsave(plot = bp4, file = paste0(path, '/ExtData9Br.pdf'), height = 14, width = 4)
```

-------------------------------------------------------------------------------------------------------------------

## Heatmap for each cluster with average expression

```{r}
# Gene list
selected_genes = list(a=c("Mki67", "Ezh2", "Id2", "Id3", "Gzma", "Gzmb", "Gzmk", "Klrg1", "Prf1", "Fasl", "Havcr2", 
                   "Pdcd1", "Lgals3", "Lgals1", "Il18r1", "Il17ra", "Cxcr6", "Cxcr3", "Klf2", "S1pr1", "S1pr4", 
                   "Tcf7", "Slamf6", "Ccr7", "Bcl2", "Il7r", "Sell", "Il6ra", "Klf3", 
                   "Myc", "Bcl2l1", "Il2ra", "Cd83", "Tnfrsf18", "Batf3", "Bax", "Icos", "Cd81", "Tnfrsf4", 
                   "Tnfsf4", "Tnfrsf9", "Tnfsf14", "Dhodh", "Cad", "Umps"))
                   

# Prepare data
data.use = SC3_Seurat@scale.data
#data.use = SC3_Seurat@assays$RNA@scale.data #Seurat3
cell_info = SC3_Seurat@meta.data
#cell_info$seurat_cluster = as.numeric(SC3_Seurat@ident)
#cell_info$seurat_cluster = as.numeric(Idents(SC3_Seurat))
cell_info$seurat_cluster = as.numeric(SC3_Seurat$res.0.8)+1
cell_info$cell_names = rownames(cell_info)
order.data.use = data.use[unlist(selected_genes),cell_info[order(cell_info$seurat_cluster, decreasing = F), 'cell_names']]
#annotation = data.frame(row.names = SC3_Seurat@cell.names, cell.type = SC3_Seurat@meta.data$cell_type, cluster = SC3_Seurat@ident)
#annotation = data.frame(row.names = colnames(SC3_Seurat), cell.type = SC3_Seurat@meta.data$cell_type, cluster = Idents(SC3_Seurat)) #Seurat3
# cluster = c('0' = '#8DC73F', '1' = '#25CED1', '2' = '#FF8A5B','3' = '#EA526F', '4' = '#FFCA04', '5' = '#731DD8')
annotation_colors = list(cell.type = c('CMC' = '#033F63', 'Tfl' = '#BF4342'), 
                         cluster = c('1' = '#8DC73F', '2' = '#25CED1', '3' = '#FF8A5B', '4' = '#EA526F', '5' = '#FFCA04'))
split = c(0, 351, 679, 988,1258, 1518)
avg_df = NULL
for (j in 1:(length(split)-1)) {
  avg_df <- rbind(avg_df, rowMeans(order.data.use[,((split[j]+1): split[j+1])]))
}
avg_df <- as.data.frame(t(avg_df))
colnames(avg_df) <- c('Cluster_1', 'Cluster_2', 'Cluster_3', 'Cluster_4', 'Cluster_5')[c(1,5,4,3,2)]
avg_df <- avg_df[,c(1,5,4,3,2)]
new_annotation = data.frame(row.names = colnames(avg_df), Cluster = as.factor(colnames(avg_df)))
new_annotation_color <- list(Cluster = c('Cluster_1' = '#8DC73F', 'Cluster_2' = '#FFCA04', 'Cluster_3' = '#EA526F', 'Cluster_4' = '#FF8A5B', 'Cluster_5' = '#25CED1'))

# Plot heatmap
heat1 <- pheatmap(t(avg_df[rownames(avg_df) %in% selected_genes$a,]), 
                 cluster_rows = FALSE, cluster_cols = FALSE, show_colnames = T, 
                 #legend_breaks = seq(-0.5,1,0.5), breaks = seq(-0.5,1,length.out=100), 
                 annotation_row = new_annotation, cutree_cols =  1, gaps_col = c(), cellwidth = 15, cellheight = 15, 
                 annotation_colors=new_annotation_color, fontsize = 12)

# Save heatmap
ggsave(paste0(path, '/ExtData9A.pdf'), heat1[[4]], height = 3, width = 13)
ggsave(paste0(path, '/ExtData9D.pdf'), heat2[[4]], height = 3, width = 13)
```

-------------------------------------------------------------------------------------------------------------------

## GSEA for cluster markers

```{r}
library(AnnotationDbi)
library(org.Mm.eg.db)
library(clusterProfiler)

# Find cluster markers
mk <- Map(x=levels(SC3_Seurat@ident), function(x) FindMarkers(SC3_Seurat, ident.1 = x) %>% rownames_to_column(., 'GeneName'))
#write.xlsx(mk[order(mk$avg_logFC, decreasing = T),], file = paste0(path, 'Cluster_', i, '_Markergenes.xlsx'))

# Run enrichment analysis for KEGG pathways and MolSigDB signatures c2
download.file(url='https://data.broadinstitute.org/gsea-msigdb/msigdb/release/6.2/c2.all.v6.2.symbols.gmt', 
              destfile=paste0(path, '/c2.all.v6.2.symbols.gmt'))
c2 <- read.gmt(paste0(path, '/c2.all.v6.2.symbols.gmt'))
enrich <- lapply(setNames(levels(SC3_Seurat@ident), nm=levels(SC3_Seurat@ident))[-3], function(x) {
#enrich <- Map(x=setNames(as.numeric(levels(Idents(SC3_Seurat))), nm=as.numeric(levels(Idents(SC3_Seurat))))[-4], function(x) {#Seurat3
  deg <- mk[[x]]
  deg$entrez = mapIds(org.Mm.eg.db,
                       keys=as.character(deg$GeneName), 
                       column="ENTREZID",
                       keytype="SYMBOL",
                       multiVals="first")
  
  #remove NAs
  deg <- deg[complete.cases(deg),]
  
  #KEGG over-representation test (hypergeometric test)
  path_enrich <- enrichKEGG(deg$entrez, organism = 'mmu')
  
  #Plot enrichment
  kegg <- clusterProfiler::dotplot(path_enrich,  font.size = 6) + 
    theme(legend.key.size = unit(0.8, 'line')) +
    coord_cartesian(xlim = c(0,1))
  
  #MolsigDB c2 enrichment
  msig_enrich <- enricher(toupper(deg$GeneName), TERM2GENE = c2)
  
  #Plot enrichment
  msig <- clusterProfiler::dotplot(msig_enrich,  font.size = 6) + 
    theme(legend.key.size = unit(0.8, 'line')) +
    coord_cartesian(xlim = c(0,1))
  
  return(list(kegg=kegg, msig=msig))
})

# Save plots
lapply(c(1,2), function(x) ggsave(paste0(path, '/Fig6C',x,'.pdf'), enrich[[x]]$kegg, height = 4, width = 5) )
lapply(names(enrich), function(x) ggsave(paste0(path, '/ExtData9C',x,'.pdf'), enrich[[x]]$msig, height = 8, width = 6) )
```

-------------------------------------------------------------------------------------------------------------------
## Session info

```{r sessioninfo, collapse=T, echo=F, warning=F, message=F, include=F}
devtools::session_info()

#─ Session info ───────────────────────────────────────────────────────────────────────────────────────────────────────────────#─
# setting  value                       
# version  R version 4.0.4 (2021-02-15)
# os       macOS Big Sur 11.2.3        
# system   x86_64, darwin17.0          
# ui       RStudio                     
# language (EN)                        
# collate  en_US.UTF-8                 
# ctype    en_US.UTF-8                 
# tz       Europe/Berlin               

#─ Packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────#─
# package              * version  date       lib source        
# abind                  1.4-5    2016-07-21 [1] CRAN (R 4.0.2)
# AnnotationDbi        * 1.52.0   2020-10-27 [1] Bioconductor  
# assertthat             0.2.1    2019-03-21 [1] CRAN (R 4.0.2)
# backports              1.2.1    2020-12-09 [1] CRAN (R 4.0.2)
# beachmat               2.6.4    2020-12-20 [1] Bioconductor  
# beeswarm               0.3.1    2021-03-07 [1] CRAN (R 4.0.2)
# Biobase              * 2.50.0   2020-10-27 [1] Bioconductor  
# BiocGenerics         * 0.36.0   2020-10-27 [1] Bioconductor  
# BiocManager            1.30.10  2019-11-16 [1] CRAN (R 4.0.2)
# BiocNeighbors          1.8.2    2020-12-07 [1] Bioconductor  
# BiocParallel           1.24.1   2020-11-06 [1] Bioconductor  
# BiocSingular           1.6.0    2020-10-27 [1] Bioconductor  
# bit                    4.0.4    2020-08-04 [1] CRAN (R 4.0.2)
# bit64                  4.0.5    2020-08-30 [1] CRAN (R 4.0.2)
# bitops                 1.0-6    2013-08-17 [1] CRAN (R 4.0.2)
# blob                   1.2.1    2020-01-20 [1] CRAN (R 4.0.2)
# broom                  0.7.6    2021-04-05 [1] CRAN (R 4.0.2)
# cachem                 1.0.4    2021-02-13 [1] CRAN (R 4.0.2)
# callr                  3.5.1    2020-10-13 [1] CRAN (R 4.0.2)
# car                    3.0-10   2020-09-29 [1] CRAN (R 4.0.2)
# carData                3.0-4    2020-05-22 [1] CRAN (R 4.0.2)
# cellranger             1.1.0    2016-07-27 [1] CRAN (R 4.0.2)
# cli                    2.3.1    2021-02-23 [1] CRAN (R 4.0.2)
# cluster                2.1.0    2019-06-19 [1] CRAN (R 4.0.4)
# clusterProfiler      * 3.18.1   2021-02-11 [1] Bioconductor  
# codetools              0.2-18   2020-11-04 [1] CRAN (R 4.0.4)
# colorspace             2.0-0    2020-11-11 [1] CRAN (R 4.0.2)
# cowplot              * 1.1.1    2020-12-30 [1] CRAN (R 4.0.2)
# crayon                 1.4.1    2021-02-08 [1] CRAN (R 4.0.2)
# curl                   4.3      2019-12-02 [1] CRAN (R 4.0.1)
# data.table           * 1.14.0   2021-02-21 [1] CRAN (R 4.0.2)
# DBI                    1.1.1    2021-01-15 [1] CRAN (R 4.0.2)
# DelayedArray           0.16.2   2021-02-26 [1] Bioconductor  
# DelayedMatrixStats     1.12.3   2021-02-03 [1] Bioconductor  
# deldir                 0.2-10   2021-02-16 [1] CRAN (R 4.0.2)
# desc                   1.3.0    2021-03-05 [1] CRAN (R 4.0.2)
# devtools               2.3.2    2020-09-18 [1] CRAN (R 4.0.2)
# digest                 0.6.27   2020-10-24 [1] CRAN (R 4.0.2)
# DO.db                  2.9      2021-03-18 [1] Bioconductor  
# DOSE                   3.16.0   2020-10-27 [1] Bioconductor  
# downloader             0.4      2015-07-09 [1] CRAN (R 4.0.2)
# dplyr                * 1.0.5    2021-03-05 [1] CRAN (R 4.0.2)
# ellipsis               0.3.1    2020-05-15 [1] CRAN (R 4.0.2)
# enrichplot             1.10.2   2021-01-28 [1] Bioconductor  
# evaluate               0.14     2019-05-28 [1] CRAN (R 4.0.1)
# fansi                  0.4.2    2021-01-15 [1] CRAN (R 4.0.2)
# farver                 2.1.0    2021-02-28 [1] CRAN (R 4.0.2)
# fastmap                1.1.0    2021-01-25 [1] CRAN (R 4.0.2)
# fastmatch              1.1-0    2017-01-28 [1] CRAN (R 4.0.2)
# fgsea                  1.16.0   2020-10-27 [1] Bioconductor  
# fitdistrplus           1.1-3    2020-12-05 [1] CRAN (R 4.0.2)
# forcats                0.5.1    2021-01-27 [1] CRAN (R 4.0.2)
# foreign                0.8-81   2020-12-22 [1] CRAN (R 4.0.4)
# fs                     1.5.0    2020-07-31 [1] CRAN (R 4.0.2)
# future                 1.21.0   2020-12-10 [1] CRAN (R 4.0.2)
# future.apply           1.7.0    2021-01-04 [1] CRAN (R 4.0.2)
# generics               0.1.0    2020-10-31 [1] CRAN (R 4.0.2)
# GenomeInfoDb         * 1.26.4   2021-03-10 [1] Bioconductor  
# GenomeInfoDbData       1.2.4    2021-03-15 [1] Bioconductor  
# GenomicRanges        * 1.42.0   2020-10-27 [1] Bioconductor  
# ggbeeswarm             0.6.0    2017-08-07 [1] CRAN (R 4.0.2)
# ggforce                0.3.3    2021-03-05 [1] CRAN (R 4.0.2)
# ggplot2              * 3.3.3    2020-12-30 [1] CRAN (R 4.0.2)
# ggpubr               * 0.4.0    2020-06-27 [1] CRAN (R 4.0.2)
# ggraph                 2.0.5    2021-02-23 [1] CRAN (R 4.0.2)
# ggrepel                0.9.1    2021-01-15 [1] CRAN (R 4.0.2)
# ggridges               0.5.3    2021-01-08 [1] CRAN (R 4.0.2)
# ggsignif               0.6.1    2021-02-23 [1] CRAN (R 4.0.2)
# globals                0.14.0   2020-11-22 [1] CRAN (R 4.0.2)
# glue                   1.4.2    2020-08-27 [1] CRAN (R 4.0.2)
# GO.db                  3.12.1   2021-03-18 [1] Bioconductor  
# goftest                1.2-2    2019-12-02 [1] CRAN (R 4.0.2)
# GOSemSim               2.16.1   2020-10-29 [1] Bioconductor  
# graphlayouts           0.7.1    2020-10-26 [1] CRAN (R 4.0.2)
# gridExtra              2.3      2017-09-09 [1] CRAN (R 4.0.2)
# gtable                 0.3.0    2019-03-25 [1] CRAN (R 4.0.2)
# haven                  2.4.0    2021-04-14 [1] CRAN (R 4.0.2)
# hms                    1.0.0    2021-01-13 [1] CRAN (R 4.0.2)
# htmltools              0.5.4    2022-12-07 [1] CRAN (R 4.0.4)
# htmlwidgets            1.5.3    2020-12-10 [1] CRAN (R 4.0.2)
# httpuv                 1.5.5    2021-01-13 [1] CRAN (R 4.0.2)
# httr                   1.4.2    2020-07-20 [1] CRAN (R 4.0.2)
# ica                    1.0-2    2018-05-24 [1] CRAN (R 4.0.2)
# igraph                 1.2.6    2020-10-06 [1] CRAN (R 4.0.2)
# IRanges              * 2.24.1   2020-12-12 [1] Bioconductor  
# irlba                  2.3.3    2019-02-05 [1] CRAN (R 4.0.2)
# jsonlite               1.7.2    2020-12-09 [1] CRAN (R 4.0.2)
# KernSmooth             2.23-18  2020-10-29 [1] CRAN (R 4.0.4)
# knitr                  1.36     2021-09-29 [1] CRAN (R 4.0.2)
# later                  1.1.0.1  2020-06-05 [1] CRAN (R 4.0.2)
# lattice                0.20-41  2020-04-02 [1] CRAN (R 4.0.4)
# lazyeval               0.2.2    2019-03-15 [1] CRAN (R 4.0.2)
# leiden                 0.3.7    2021-01-26 [1] CRAN (R 4.0.2)
# lifecycle              1.0.0    2021-02-15 [1] CRAN (R 4.0.2)
# listenv                0.8.0    2019-12-05 [1] CRAN (R 4.0.2)
# lmtest                 0.9-38   2020-09-09 [1] CRAN (R 4.0.2)
# magrittr               2.0.1    2020-11-17 [1] CRAN (R 4.0.2)
# MASS                   7.3-53   2020-09-09 [1] CRAN (R 4.0.4)
# Matrix                 1.3-2    2021-01-06 [1] CRAN (R 4.0.4)
# MatrixGenerics       * 1.2.1    2021-01-30 [1] Bioconductor  
# matrixStats          * 0.58.0   2021-01-29 [1] CRAN (R 4.0.2)
# memoise                2.0.1    2021-11-26 [1] CRAN (R 4.0.2)
# mgcv                   1.8-33   2020-08-27 [1] CRAN (R 4.0.4)
# mime                   0.10     2021-02-13 [1] CRAN (R 4.0.2)
# miniUI                 0.1.1.1  2018-05-18 [1] CRAN (R 4.0.2)
# munsell                0.5.0    2018-06-12 [1] CRAN (R 4.0.2)
# nlme                   3.1-152  2021-02-04 [1] CRAN (R 4.0.4)
# openxlsx             * 4.2.3    2020-10-27 [1] CRAN (R 4.0.2)
# org.Mm.eg.db         * 3.12.0   2021-03-25 [1] Bioconductor  
# parallelly             1.24.0   2021-03-14 [1] CRAN (R 4.0.4)
# patchwork              1.1.1    2020-12-17 [1] CRAN (R 4.0.2)
# pbapply                1.4-3    2020-08-18 [1] CRAN (R 4.0.2)
# pheatmap             * 1.0.12   2019-01-04 [1] CRAN (R 4.0.2)
# pillar                 1.5.1    2021-03-05 [1] CRAN (R 4.0.2)
# pkgbuild               1.2.0    2020-12-15 [1] CRAN (R 4.0.2)
# pkgconfig              2.0.3    2019-09-22 [1] CRAN (R 4.0.2)
# pkgload                1.2.0    2021-02-23 [1] CRAN (R 4.0.2)
# plotly                 4.9.3    2021-01-10 [1] CRAN (R 4.0.2)
# plyr                   1.8.6    2020-03-03 [1] CRAN (R 4.0.2)
# png                    0.1-7    2013-12-03 [1] CRAN (R 4.0.2)
# polyclip               1.10-0   2019-03-14 [1] CRAN (R 4.0.2)
# prettyunits            1.1.1    2020-01-24 [1] CRAN (R 4.0.2)
# processx               3.5.0    2021-03-23 [1] CRAN (R 4.0.4)
# promises               1.2.0.1  2021-02-11 [1] CRAN (R 4.0.2)
# ps                     1.6.0    2021-02-28 [1] CRAN (R 4.0.2)
# purrr                  0.3.4    2020-04-17 [1] CRAN (R 4.0.2)
# qvalue                 2.22.0   2020-10-27 [1] Bioconductor  
# R6                     2.5.0    2020-10-28 [1] CRAN (R 4.0.2)
# RANN                   2.6.1    2019-01-08 [1] CRAN (R 4.0.2)
# RColorBrewer           1.1-2    2014-12-07 [1] CRAN (R 4.0.2)
# Rcpp                   1.0.8.3  2022-03-17 [1] CRAN (R 4.0.5)
# RcppAnnoy              0.0.18   2020-12-15 [1] CRAN (R 4.0.2)
# RCurl                  1.98-1.3 2021-03-16 [1] CRAN (R 4.0.4)
# readxl                 1.3.1    2019-03-13 [1] CRAN (R 4.0.2)
# remotes                2.2.0    2020-07-21 [1] CRAN (R 4.0.2)
# reshape2               1.4.4    2020-04-09 [1] CRAN (R 4.0.2)
# reticulate             1.25     2022-05-11 [1] CRAN (R 4.0.4)
# rio                    0.5.26   2021-03-01 [1] CRAN (R 4.0.2)
# rlang                  0.4.10   2020-12-30 [1] CRAN (R 4.0.2)
# rmarkdown              2.19     2022-12-15 [1] CRAN (R 4.0.4)
# ROCR                   1.0-11   2020-05-02 [1] CRAN (R 4.0.2)
# rpart                  4.1-15   2019-04-12 [1] CRAN (R 4.0.4)
# rprojroot              2.0.2    2020-11-15 [1] CRAN (R 4.0.2)
# RSQLite                2.2.4    2021-03-12 [1] CRAN (R 4.0.2)
# rstatix                0.7.0    2021-02-13 [1] CRAN (R 4.0.2)
# rsvd                   1.0.5    2021-04-16 [1] CRAN (R 4.0.2)
# Rtsne                  0.15     2018-11-10 [1] CRAN (R 4.0.2)
# rvcheck                0.1.8    2020-03-01 [1] CRAN (R 4.0.2)
# S4Vectors            * 0.28.1   2020-12-09 [1] Bioconductor  
# scales                 1.1.1    2020-05-11 [1] CRAN (R 4.0.2)
# scater               * 1.18.6   2021-02-26 [1] Bioconductor  
# scattermore            0.7      2020-11-24 [1] CRAN (R 4.0.2)
# scatterpie             0.1.5    2020-09-09 [1] CRAN (R 4.0.2)
# sctransform            0.3.2    2020-12-16 [1] CRAN (R 4.0.2)
# scuttle                1.0.4    2020-12-17 [1] Bioconductor  
# sessioninfo            1.1.1    2018-11-05 [1] CRAN (R 4.0.2)
# Seurat               * 4.0.1    2021-03-18 [1] CRAN (R 4.0.4)
# SeuratObject         * 4.0.0    2021-01-15 [1] CRAN (R 4.0.2)
# shadowtext             0.0.7    2019-11-06 [1] CRAN (R 4.0.2)
# shiny                  1.6.0    2021-01-25 [1] CRAN (R 4.0.2)
# SingleCellExperiment * 1.12.0   2020-10-27 [1] Bioconductor  
# sparseMatrixStats      1.2.1    2021-02-02 [1] Bioconductor  
# spatstat.core          2.0-0    2021-03-23 [1] CRAN (R 4.0.4)
# spatstat.data          2.1-0    2021-03-21 [1] CRAN (R 4.0.2)
# spatstat.geom          2.0-1    2021-03-22 [1] CRAN (R 4.0.2)
# spatstat.sparse        2.0-0    2021-03-16 [1] CRAN (R 4.0.4)
# spatstat.utils         2.1-0    2021-03-15 [1] CRAN (R 4.0.4)
# stringi                1.5.3    2020-09-09 [1] CRAN (R 4.0.2)
# stringr                1.4.0    2019-02-10 [1] CRAN (R 4.0.2)
# SummarizedExperiment * 1.20.0   2020-10-27 [1] Bioconductor  
# survival               3.2-7    2020-09-28 [1] CRAN (R 4.0.4)
# tensor                 1.5      2012-05-05 [1] CRAN (R 4.0.2)
# testthat               3.0.2    2021-02-14 [1] CRAN (R 4.0.2)
# tibble               * 3.1.0    2021-02-25 [1] CRAN (R 4.0.2)
# tidygraph              1.2.0    2020-05-12 [1] CRAN (R 4.0.2)
# tidyr                  1.1.3    2021-03-03 [1] CRAN (R 4.0.2)
# tidyselect             1.1.0    2020-05-11 [1] CRAN (R 4.0.2)
# tweenr                 1.0.2    2021-03-23 [1] CRAN (R 4.0.4)
# usethis                2.0.1    2021-02-10 [1] CRAN (R 4.0.2)
# utf8                   1.2.1    2021-03-12 [1] CRAN (R 4.0.2)
# uwot                   0.1.10   2020-12-15 [1] CRAN (R 4.0.2)
# vctrs                  0.3.6    2020-12-17 [1] CRAN (R 4.0.2)
# vipor                  0.4.5    2017-03-22 [1] CRAN (R 4.0.2)
# viridis                0.5.1    2018-03-29 [1] CRAN (R 4.0.2)
# viridisLite            0.3.0    2018-02-01 [1] CRAN (R 4.0.1)
# withr                  2.4.1    2021-01-26 [1] CRAN (R 4.0.2)
# xfun                   0.36     2022-12-21 [1] CRAN (R 4.0.4)
# xtable                 1.8-4    2019-04-21 [1] CRAN (R 4.0.2)
# XVector                0.30.0   2020-10-28 [1] Bioconductor  
# yaml                   2.2.1    2020-02-01 [1] CRAN (R 4.0.2)
# zip                    2.1.1    2020-08-27 [1] CRAN (R 4.0.2)
# zlibbioc               1.36.0   2020-10-28 [1] Bioconductor  
# zoo                    1.8-9    2021-03-09 [1] CRAN (R 4.0.2)
```

-------------------------------------------------------------------------------------------------------------------
