---
title: "10xgenomics"
output: html_document
---

## Prepare session

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(echo = TRUE)
path <- '~/Desktop/10xgenomics'
dir.create(path = path, recursive = T)
knitr::opts_knit$set(root.dir = path, collapse = T, comment = '#>')

# Load libraries
library(Seurat)
library(sctransform)
library(dplyr)
library(ggplot2)
#library(SeuratWrappers)

# Define custom themes for ggplot
theme_custom <- theme(axis.text.x = element_text(size = 12.8, color = 'black'),
                      axis.text.y = element_text(size = 12.8, color = 'black'), 
                      axis.title.x = element_text(size = 16, margin = margin(6,0,0,0)), 
                      axis.title.y = element_text(size = 16, margin = margin(0,8,0,0)),
                      plot.title = element_text(size = 16, face = 'plain', hjust = 0.5, margin = margin(5,0,10,0)),
                      plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(0,0,10,0)), 
                      axis.ticks.x = element_line(size = 0.4, colour = 'black'), 
                      axis.ticks.y = element_line(size = 0.4, colour = 'black'),
                      axis.line = element_blank(), 
                      panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank(),
                      panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(),
                      panel.border = element_rect(colour = 'black', size = 0.8, fill = NA),
                      panel.background = element_rect(colour = NA, fill = NA), 
                      strip.text.x = element_text(size = 16, face = 'plain', margin = margin(0,0,5,0) ), 
                      strip.text.y = element_text(size = 16, face = 'plain', margin = margin(0,0,0,5) ), 
                      strip.background = element_blank(), 
                      legend.key = element_blank(), legend.key.size = unit(0.5,'cm'),
                      legend.text = element_text(size = 12.8), 
                      legend.title = element_text(size = 12.8),
                      plot.background = element_rect(colour = NA, fill = NA), aspect.ratio = 1)
theme_custom2 <- theme(axis.text.x = element_blank(), 
                       axis.text.y = element_blank(), 
                       axis.title.x = element_text(size = 16, margin = margin(4,0,0,0)), 
                       axis.title.y = element_text(size = 16, margin = margin(0,4,0,0)),
                       plot.title = element_text(size = 16, face = 'plain', hjust = 0.5, margin = margin(5,0,10,0)),
                       plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(0,0,10,0)), 
                       axis.ticks.x = element_blank(), 
                       axis.ticks.y = element_blank(), 
                       axis.line = element_blank(), 
                       panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank(),
                       panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(),
                       panel.border = element_rect(colour = 'grey80', size = 0.8, fill = NA),
                       panel.background = element_rect(colour = NA, fill = NA),
                       strip.text.x = element_text(size = 16, face = 'plain', margin = margin(0,0,5,0) ), 
                       strip.text.y = element_text(size = 16, face = 'plain', margin = margin(0,0,0,5) ), 
                       strip.background = element_blank(), 
                       legend.key = element_blank(), legend.key.size = unit(0.5,'cm'),
                       legend.text = element_text(size = 12.8), 
                       legend.title = element_text(size = 12.8),
                       plot.background = element_rect(colour = NA, fill = NA), aspect.ratio = 1)

# Function to save plots with same size
grid <- function(data, layout=rbind(c(1,1,1,1,2,2,3))) {
  gridExtra::grid.arrange(grobs = list(data + guides(color = 'none', fill = 'none', size = 'none'), 
                                       cowplot::get_legend(data)), ncol = 2, layout_matrix = layout, 
                          top = grid::textGrob('', gp = grid::gpar(fontsize = 16, font = 2)))
}

# Function to remove clip from strip labels
rmclip <- function(plot,gg=F) {
  pg <- ggplotGrob(plot)
  for(i in which(grepl("strip-t", pg$layout$name))) {
    pg$grobs[[i]]$layout$clip <- "off"
  }
  if(gg) return(pg) else return(grid::grid.draw(pg))
}
```

-------------------------------------------------------------------------------------------------------------------

## All cells

- Merge the 4 replicates and both conditions together

### Clustering with Seurat

```{r procdata, collapse=T, echo=F, warning=F, message=F, include=F}
# Download pre-processed data from GEO SuperSeries and place at '~/Desktop/10xgenomics/'
download.file(url='https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE200488&format=file', 
              destfile=paste0(path, '/GSE200488_RAW.tar'))
untar(tarfile = paste0(path, '/GSE200488_RAW.tar'), exdir = paste0(path) )
sapply(list.files(path, full.names=T)[grepl('GSM', list.files(path))], function(x) untar(tarfile=x, exdir=paste0(path) ))

# Load UMI counts from 10x data
dirs <- list.dirs(paste0(path,'/cellranger'))
dirs <- dirs[grep('filtered_feature_bc_matrix', dirs)]
names.dirs <- stringr::str_split(dirs, pattern = '/', n = Inf, simplify = T)
names(dirs) <- sub('_filtered_feature_bc_matrix', '', sub('-Spleen', '', names.dirs[,ncol(names.dirs)]) )
names(dirs) <- sub('5', '4', names(dirs))
bd <- lapply(dirs, function(x) Read10X(data.dir = x) )

# Initialize the Seurat object with the raw (non-normalized data).
bd <- lapply(setNames(names(bd), nm=names(bd)), function(x) 
  AddMetaData(CreateSeuratObject(counts = bd[[x]], min.cells = 3, min.features = 0, project = 'ot1_lefl_vs_cmc'), 
              metadata = x, col.name = 'sample') )
# Rename cells
bd <- Map(x=names(bd), function(x) RenameCells(bd[[x]], new.names = paste0(bd[[x]]$sample, '_', colnames(bd[[x]])) ))

# Define colors
col <- list(sp=setNames(c('#D78184', '#7BAFDE', '#96C793', '#b888ae', '#b00409', '#1965B0', '#2d9027', '#6c245b', '#FF7F00', '#ffbf7f', '#b9206f', '#E78AC3', '#55A1B1', '#8DD3C7', '#A6761D', '#E6AB02', '#7570B3', '#BEAED4', '#666666', '#999999', '#997575', '#d4b7b7', '#737300', '#aeae5c'), nm=unique(gsub('_',' ',names(dirs))) ), 
            cl=setNames(c('#b00409', '#D78184', '#1965B0', '#7BAFDE', '#2d9027', '#96C793', '#6c245b'), nm=c('3','5','2','4a','4b','4c','1') ), 
            gp=setNames(c('grey60','royalblue3'), nm=unique(gsub('_',' ',sub('\\d','',names(dirs)))) ), 
            ct=c(OT1='grey80', other='grey80', 'B'='#96C793','B/M'='#96C793','Cyc'='#7570B3','rRNA'='#E78AC3','M'='#E6AB02', 'mtRNA'='#7BAFDE'), 
            hm=colorRampPalette(c('#133d67','#2166AC','#90b2d5','#d2e0ee','grey90','#efd0d4','#d88b95','#B2182B','#590c15'))(41), 
            hm2=colorRampPalette(c('grey90','#efd0d4','#d88b95','#B2182B','#590c15'))(41) )

# Calculate the percentage of mitochondrial features here and store it in object metadata as `percent.mito`
bd <- lapply(bd, FUN = PercentageFeatureSet, pattern = "^mt-", col.name = "percent.mito")

# Keep cells that have unique feature counts less than 3 SDs above the mean, less than 10% of mitochondrial genes 
# and more than 500 detected genes
bd <- lapply(bd, FUN = subset, subset = nFeature_RNA > 500 & nCount_RNA < summary(nCount_RNA)[4]+sd(nCount_RNA)*3 & percent.mito < 10)

# Normalize all samples together
bd <- Map(x='merged', function(x) {
  bdI <- merge(bd[[1]], y = bd[-1])
  bdI <- SCTransform(bdI, method = 'glmGamPoi', variable.features.n = 1000, assay = 'RNA', new.assay.name = 'SCTmerged', return.only.var.genes = F)
  bdI <- PercentageFeatureSet(bdI, pattern = "^mt-", col.name = "percent.mito_SCTmerged")
  
  # Add metadata
  bdI@meta.data <- cbind(bdI@meta.data, data.frame(condition = stringr::str_split(bdI$sample, pattern='\\d', n=Inf, simplify=T)[,1], replicate = sub('CMC|Lefl', '', bdI$sample)))
  bdI$condition <- factor(bdI$condition, levels=sort(unique(sub('[[:digit:]]','',names(dirs)))) )
  bdI$sample <- factor(bdI$sample, levels=sort(unique(names(dirs))) )
  
  # Perform linear dimensional reduction
  bdI <- RunPCA(bdI, features = VariableFeatures(bdI), verbose = T, assay = 'SCTmerged', reduction.name = 'mpca', reduction.key = 'mPC_')
  
  # Compute KNN graphs
  bdI <- FindNeighbors(bdI, reduction = 'mpca', k.param = 20, dims = 1:20, do.plot = F, assay = 'SCTmerged')
  return(bdI)
})

# Visualization and clustering
bd <- Map(x=names(bd), function(x) {
  # Cluster cells
  bdI <- FindClusters(bd[[x]], resolution = 0.33, algorithm = 1, n.start = 10, n.iter = 10, random.seed = 0)
  bdI$seurat_clusters <- factor(plyr::mapvalues(as.numeric(bdI$seurat_clusters), from=sort(unique(as.numeric(bdI$seurat_clusters))), to=1:length(unique(bdI$seurat_clusters)) ))
  colnames(bdI@meta.data)[colnames(bdI@meta.data) %in% 'seurat_clusters'] <- 'cluster'
  Idents(bdI) <- 'cluster'
  
  # Run Non-linear dimensional reduction (tSNE and UMAP)
  bdI <- RunTSNE(bdI, reduction = 'mpca', dims = 1:20, assay = 'SCTmerged', reduction.name = 'mtsne', reduction.key = 'mtSNE_', seed.use = 1, tsne.method = 'Rtsne', dim.embed = 2, perplexity = 30)
  bdI <- RunUMAP(bdI, reduction = 'mpca', dims = 1:20, assay = 'SCTmerged', reduction.name = 'mumap', reduction.key = 'mUMAP_', seed.use = 3, spread = 1, min.dist = 0.3)
  #DimPlot(bdI, reduction = 'mumap', dims = c(1,2), group.by = 'sample', split.by = 'orig.ident', label = F, label.size = 8, pt.size = 0.3, cols = col$sp) + theme_bw() + theme_custom2 #+ NoLegend()
  return(bdI)
})
#trqwe::mcsaveRDS(bd, file = paste0(path, '/seurat.rds'), mc.cores = min(parallel::detectCores(), 14))
#bd <- trqwe::mcreadRDS(paste0(path, '/seurat.rds'), mc.cores = min(parallel::detectCores(), 14))

# Plot clusters
s <- 'merged'
umm.cl <- DimPlot(bd[[s]], reduction = 'mumap', dims = c(1,2), group.by = 'cluster', label = T, label.box = T, label.size = 3, pt.size = 0.1, cols = as.vector(col$sp)) + ggtitle('OT1 cells', subtitle = paste0(gsub('_',' ',s), ' (non-integrated)')) + theme_bw() + theme_custom2 + scale_x_continuous('UMAP 1',breaks=scales::pretty_breaks()) + scale_y_continuous('UMAP 2',breaks=scales::pretty_breaks())
```

### Cluster annotation

```{r procdataanno, collapse=T, echo=F, warning=F, message=F, include=F}
# Function to draw dotplot
dotplot <- function(object=bd, sel=genes$ct, cl=F, scale=T, sample='OT1 CD8+ T cells', subtitle='Marker expression by cluster',smax=100) {
  sel <- sel[sel %in% rownames(object)]
  dt <- DotPlot(object, assay = 'SCTmerged', features = sel, cluster.idents = cl, scale.max=smax)$data
  if(scale) l <- list(a=-1.5,b=1.5) else l <- list(a=0,b=6)
  ggplot(transform(dt, celltype= plyr::mapvalues(dt$id, from=sort(unique(as.numeric(dt$id))), to=ctmap[[s]])), 
         aes(id, features.plot, color=if(scale) avg.exp.scaled else avg.exp, size=pct.exp)) + 
    geom_point() + scale_x_discrete('') + scale_y_discrete('') + #coord_flip() + 
    scale_color_gradientn('Average expression', colours = col$hm, oob = scales::squish, 
                          limits = c(l$a,l$b), breaks = seq(l$a,l$b, length.out = 3)) + 
    scale_size_continuous('Percent expressed', limits = c(0,smax), breaks = seq(0,smax,smax/4), range = c(0,6)) + 
    ggtitle(gsub('_',' ',sample), subtitle = subtitle) + theme_custom + 
    facet_grid(.~factor(celltype, levels = levels(object$celltype)), scales = 'free', space = 'free') + 
    theme(aspect.ratio = length(sel) / length(unique(dt$id)), 
          strip.text = element_text(size = 12.8, face = 'plain', angle=90, vjust=0.5, hjust=0, margin = margin(5,0,5,0)), 
          axis.text.x = element_text(size = 12.8, color = 'black', angle = 0, vjust = 1, hjust = 0.5))
}

# Identify celltypes
ctmap <- list(merged=c('1'='other','2'='Cyc','3'='other','4'='rRNA','5'='Cyc','6'='other','7'='mtRNA','8'='B/M') )
bd[[s]]$celltype <- plyr::mapvalues(bd[[s]]$cluster, from=names(ctmap[[s]]), to=ctmap[[s]])
bd[[s]]$celltype <- factor(bd[[s]]$celltype, levels = sort(unique(as.character(bd[[s]]$celltype)))[c(4,2,5,3,1)])

# Plot celltypes over UMAP
um.ct <- DimPlot(bd[[s]], reduction = 'mumap', dims = c(1,2), group.by = 'celltype', label = F, label.size = 5, pt.size = 0.1, cols = (col$ct)) + ggtitle('OT1 cells', subtitle = paste0(gsub('_',' ',s), ' (integrated)')) + xlab('UMAP 1') + ylab('UMAP 2') + theme_bw() + theme_custom2 + scale_x_continuous(breaks=scales::pretty_breaks()) + scale_y_continuous(breaks=scales::pretty_breaks())

# Plot celltype markers
genes <- list(ct=c('AY036118','Gm42418','Cdk1','Mcm2','Pclaf','H2afz','Birc5','Mki67','mt-Atp6','mt-Co1','mt-Co2','mt-Co3','mt-Nd3','mt-Nd4','Cd14','Lyz2','Fcgr3','Ms4a7','Fcer1g','Cst3','H2-Aa','Ly6d','Ms4a1','Cd19') )
dp.ct <- dotplot(object = bd[[s]], sel = genes$ct, sample=s, subtitle = 'Cell type marker expression by cluster')

# Export cell annotation
write.csv(bd[[s]]@meta.data, file = paste0(path, '/cell_annotation.csv'), row.names = T)
```

-------------------------------------------------------------------------------------------------------------------

## Filtered data

- Merge both conditions together and integrate the 4 replicates
- Filter out clusters of contaminating cells identified on previous analysis

### Clustering with Seurat

```{r filterdata, collapse=T, echo=F, warning=F, message=F, include=F}
# Load UMI counts from 10x data
bd <- lapply(dirs, function(x) Read10X(data.dir = x) )

# Initialize the Seurat object with the raw (non-normalized data).
bd <- lapply(setNames(names(bd), nm=names(bd)), function(x) 
    AddMetaData(CreateSeuratObject(counts = bd[[x]], min.cells = 3, min.features = 0, project = 'ot1_lefl_vs_cmc'), 
                metadata = x, col.name = 'sample') )
# Rename cells
bd <- Map(x=names(bd), function(x) RenameCells(bd[[x]], new.names = paste0(bd[[x]]$sample, '_', colnames(bd[[x]])) ))

# Calculate the percentage of mitochondrial features here and store it in object metadata as `percent.mito`
bd <- lapply(bd, FUN = PercentageFeatureSet, pattern = "^mt-", col.name = "percent.mito")

# Keep cells that have unique feature counts less than 3 SDs above the mean, less than 10% of mitochondrial genes 
# and more than 2000 detected genes
bd <- lapply(bd, FUN = subset, subset = nFeature_RNA > 2000 & nCount_RNA < summary(nCount_RNA)[4]+sd(nCount_RNA)*3 & percent.mito < 10)

# Remove contaminating cells (based on prior analysis over merged data)
ann <- read.csv(file = paste0(path, '/cell_annotation.csv'), row.names = 1)
ann <- ann[!ann$celltype %in% c('mtRNA','B/M'),]
bd <- Map(x=names(bd), function(x) subset(
 AddMetaData(bd[[x]], metadata = colnames(bd[[x]]), col.name = 'cells'), subset = cells %in% rownames(ann)) )

# Group by replicate number
bd <- Map(x=unique(sub('CMC|Lefl','',names(bd))), function(x) bd[sub('CMC|Lefl','',names(bd)) %in% x])

# Merge conditions by replicate number
bd <- Map(x=names(bd), function(x) merge(bd[[x]][[1]], y = bd[[x]][-1]) )

# Normalize merged conditons together
bd <- lapply(bd, FUN = SCTransform, method = 'glmGamPoi', variable.features.n = 1000)

# Identify anchor points and integrate datasets
bd <- Map(x='integrated', function(x) {
 int.features <- SelectIntegrationFeatures(object.list = bd, nfeatures = 1000)
 bdI <- PrepSCTIntegration(object.list = bd, anchor.features = int.features )
 bdI <- FindIntegrationAnchors(object.list = bdI, normalization.method = "SCT", k.anchor = 5, anchor.features = int.features)
 bdI <- IntegrateData(anchorset = bdI, dims = 1:20, normalization.method = "SCT", features.to.integrate = unique(unlist(sapply(bdI@object.list, rownames))) )
 
 # Add metadata
 bdI@meta.data <- cbind(bdI@meta.data, data.frame(condition = stringr::str_split(bdI$sample, pattern='\\d', n=Inf, simplify=T)[,1], 
                                                  replicate = sub('CMC|Lefl', '', bdI$sample)))
 bdI$condition <- factor(bdI$condition, levels=sort(unique(sub('[[:digit:]]','',names(dirs)))) )
 bdI$sample <- factor(bdI$sample, levels=sort(unique(names(dirs))) )
 
 # Perform linear dimensional reduction
 bdI <- RunPCA(bdI, features = VariableFeatures(bdI), verbose = F, assay = 'integrated')
 
 # Compute KNN graphs
 bdI <- FindNeighbors(bdI, reduction = 'pca', k.param = 30, dims = 1:20, do.plot = F, assay = 'integrated')
 return(bdI)
})

# Visualization and clustering
bd <- Map(x=names(bd), function(x) {
 bdI <- FindClusters(bd[[x]], resolution = 0.33, algorithm = 1, n.start = 10, n.iter = 10, random.seed = 0)
 bdI$seurat_clusters <- factor(plyr::mapvalues(as.numeric(bdI$seurat_clusters), from=sort(unique(as.numeric(bdI$seurat_clusters))), 
                                               to=1:length(unique(bdI$seurat_clusters)) ))
 colnames(bdI@meta.data)[colnames(bdI@meta.data) %in% 'seurat_clusters'] <- 'cluster'
 
 # Change cluster numbers
 bdI$cluster <- factor(plyr::mapvalues(as.numeric(bdI$cluster), from=sort(unique(as.numeric(bdI$cluster)))[c(4,1,3,2,6,5,7)], #[c(3,0,2,1,5,4,6)], 
                                       to=1:length(unique(bdI$cluster)) ))
 
 # Run Non-linear dimensional reduction (tSNE and UMAP)
 bdI <- RunTSNE(bdI, reduction = 'pca', dims = 1:20, seed.use = 2, tsne.method = 'Rtsne', dim.embed = 2, perplexity = 30, assay = 'integrated')
 bdI <- RunUMAP(bdI, reduction = 'pca', dims = 1:20, seed.use = 0, spread = 1, min.dist = 0.1, reduction.name = 'umap', assay = 'integrated')
 #DimPlot(bdI, reduction = 'umap', dims = c(1,2), group.by = 'cluster', split.by = 'condition', label = F, label.size = 8, pt.size = 0.3, cols = as.vector(col$cl)) + theme_bw() + theme_custom2 #+ NoLegend()
 return(bdI)
})

# Normalize all datasets together
bd <- Map(x=names(bd), function(x) {
 bdI <- SCTransform(bd[[x]], method = 'glmGamPoi', variable.features.n = 1000, assay = 'RNA', new.assay.name = 'SCTmerged', return.only.var.genes = F)
 Idents(bdI) <- 'cluster'
 bdI <- PercentageFeatureSet(bdI, pattern = "^mt-", col.name = "percent.mito_SCTmerged")
 
 # Perform linear dimensional reduction
 bdI <- RunPCA(bdI, features = VariableFeatures(bdI), verbose = T, assay = 'SCTmerged', reduction.name = 'mpca', reduction.key = 'mPC_')
 
 # Run Non-linear dimensional reduction (tSNE and UMAP)
 bdI <- RunTSNE(bdI, reduction = 'mpca', dims = 1:20, assay = 'SCTmerged', reduction.name = 'mtsne', reduction.key = 'mtSNE_', seed.use = 1, tsne.method = 'Rtsne', dim.embed = 2, perplexity = 30)
 bdI <- RunUMAP(bdI, reduction = 'mpca', dims = 1:20, assay = 'SCTmerged', reduction.name = 'mumap', reduction.key = 'mUMAP_', seed.use = 0, spread = 1, min.dist = 0.1)
 #DimPlot(bdI, reduction = 'mumap', dims = c(1,2), group.by = 'cluster', split.by = 'condition', label = F, label.size = 8, pt.size = 0.3, cols = as.vector(col$cl)) + theme_bw() + theme_custom2 #+ NoLegend()
 return(bdI)
})

# Update cluster labels
s<-'integrated'
bd[[s]]$cluster_old <- bd[[s]]$cluster
bd[[s]]$cluster <- plyr::mapvalues(bd[[s]]$cluster, from = levels(bd[[s]]$cluster), to = c('3','5','2','4a','4b','4c','1') )
bd[[s]]$cluster <- factor(bd[[s]]$cluster, levels = sort(levels(bd[[s]]$cluster)) )
Idents(bd[[s]]) <- 'cluster'
#trqwe::mcsaveRDS(bd, file = paste0(path, '/seurat_filtered.rds'), mc.cores = min(parallel::detectCores(), 14))
#bd <- trqwe::mcreadRDS(paste0(path, '/seurat_filtered.rds'), mc.cores = min(parallel::detectCores(), 14))

# Calculate average cluster expression
avg <- list(norm=AverageExpression(object=AddMetaData(object=bd[[s]], metadata=paste0('cl', bd[[s]]$cluster), col.name='cl'), assay='SCTmerged', return.seurat=F, group.by='cl', slot='data')[[1]], score=AverageExpression(object=AddMetaData(object=bd[[s]], metadata=paste0('cl', bd[[s]]$cluster), col.name='cl'), assay='SCTmerged', return.seurat=F, group.by='cl', slot='scale.data')[[1]] )
avg <- Map(x=names(avg), function(x) transform(as.data.frame(avg[[x]]), gene=rownames(avg[[x]]), row.names=1:nrow(avg[[x]]))[,c((length(unique(bd[[s]]$cluster))+1),1:(length(unique(bd[[s]]$cluster))))] %>% arrange(gene) )

# Export average cluster expression
openxlsx::write.xlsx(avg, firstRow=T, firstCol=T, asTable=T, withFilter=T, 
                     file = paste0(path, '/cluster_avg_expression.xlsx'), startRow = 1, #sheet = 1, 
                     colNames = T, rowNames = F, rows = NULL, cols = NULL, namedRegion = NULL, keepNA = T, na.string='N/A')

# Export metadata
md <- list(OT1_Lefl_vs_CMC=transform(as.data.frame(Reduce(merge, lapply(list(bd[[s]]@meta.data[,], Seurat::Embeddings(bd[[s]], reduction = "umap"), t(as.matrix(Seurat::GetAssayData(bd[[s]], assay = 'SCT', slot = 'data')))), data.table::data.table, keep.rownames = TRUE, key = 'rn') )), row.names=rn) %>% dplyr::rename(cell=rn) )
lapply(names(md), function(x) 
  data.table::fwrite(md[[x]], file = paste0(path, '/GSE200488_OT1_Lefl_vs_CMC_norm.txt.gz'), sep = '\t', row.names = F, col.names = T, compress = 'gzip', nThread = min(parallel::detectCores(), 14) ) )

# Plot data
um.cls <- DimPlot(bd[[s]], reduction = 'umap', dims = c(1,2), group.by = 'cluster', split.by = 'condition', label = T, label.size = 5, pt.size = 0.1, cols = col$cl, ncol=4) + ggtitle('OT1 cells', subtitle = paste0(gsub('_',' ',s), ' (integrated)')) + xlab('UMAP 1') + ylab('UMAP 2') + theme_bw() + theme_custom2 + scale_x_continuous(breaks=scales::pretty_breaks()) + scale_y_continuous(breaks=scales::pretty_breaks()) #ExtData10A
um.clr <- DimPlot(bd[[s]], reduction = 'umap', dims = c(1,2), group.by = 'cluster', split.by = 'sample', label = T, label.size = 5, pt.size = 0.1, cols = col$cl, ncol=4) + ggtitle('OT1 cells', subtitle = paste0(gsub('_',' ',s), ' (integrated)')) + xlab('UMAP 1') + ylab('UMAP 2') + theme_bw() + theme_custom2 + scale_x_continuous(breaks=scales::pretty_breaks()) + scale_y_continuous(breaks=scales::pretty_breaks()) #ExtData10B
```

### Cell distribution

```{r filterdatadist, collapse=T, echo=F, warning=F, message=F, include=F}
# Calculate frequencies for groups in each cluster
freq.spcl <- transform(as.data.frame(table(group = droplevels(bd[[s]]$sample), cluster = bd[[s]]$cluster)) )
freq.spcl <- freq.spcl[order(freq.spcl$cluster),]

# Calculate percentage from total cells accounting for disparity of total cell number
tot.sp <- plyr::ddply(freq.spcl, 'group', summarise, sum = sum(Freq))
for(i in 1:nrow(freq.spcl)) freq.spcl$percent[i] <- 100*freq.spcl$Freq[i] / 
  tot.sp$sum[tot.sp$group == freq.spcl$group[i]]

# Calculate statistics
freq.spcl$condition <- factor(stringr::str_split(freq.spcl$group, pattern = '\\d', simplify = T)[,1], levels=levels(bd[[s]]$condition))
freq.spcl$replicate <- factor(sub('CMC|Lefl', '', freq.spcl$group))
pval.spcl <- data.frame(freq.spcl %>% group_by(cluster) %>% summarise(max=max(percent)), 
                             padj=round(p.adjust(sapply(levels(bd[[s]]$cluster), function(x) 
                               pairwise.t.test(freq.spcl %>% group_by(group=paste0(cluster,'_',group)) %>% filter(cluster %in% x) %>% pull(percent), 
                                               freq.spcl %>% group_by(group=paste0(cluster,'_',group)) %>% filter(cluster %in% x) %>% pull(condition), 
                                               p.adjust.method = 'none', paired = F)$p.value), method = 'BH'), digits = 3) )
pval.spcl <- pval.spcl[order(pval.spcl$cluster),]
pval.spcl$y <- pval.spcl$max+4
pval.spcl$x <- as.numeric(pval.spcl$cluster)
pval.spcl$xe <- as.numeric(pval.spcl$cluster)

# Save p-values
pval.spcl.save <- data.frame(freq.spcl %>% group_by(cluster) %>% summarise(max=max(percent)), 
                                  p=sapply(levels(bd[[s]]$cluster), function(x) 
                                    pairwise.t.test(freq.spcl %>% group_by(group=paste0(cluster,'_',group)) %>% filter(cluster %in% x) %>% pull(percent), 
                                                    freq.spcl %>% group_by(group=paste0(cluster,'_',group)) %>% filter(cluster %in% x) %>% pull(condition), 
                                                    p.adjust.method = 'none', paired = F)$p.value), 
                                  padj=(p.adjust(sapply(levels(bd[[s]]$cluster), function(x) 
                                    pairwise.t.test(freq.spcl %>% group_by(group=paste0(cluster,'_',group)) %>% filter(cluster %in% x) %>% pull(percent), 
                                                    freq.spcl %>% group_by(group=paste0(cluster,'_',group)) %>% filter(cluster %in% x) %>% pull(condition), 
                                                    p.adjust.method = 'none', paired = F)$p.value), method = 'BH') ) )[,-2]
openxlsx::write.xlsx(pval.spcl.save, firstRow=T, firstCol=T, asTable=T, withFilter=T, 
                     file = paste0(path, '/distribution_fdr.xlsx'), startRow = 1, #sheet = 1, 
                     colNames = T, rowNames = F, rows = NULL, cols = NULL, namedRegion = NULL, keepNA = T, na.string='N/A')

# Save distribution
freq.spcl.save <- transform(freq.spcl, sample=group, absolute=Freq, percent=percent, group=NULL, Freq=NULL)[,c(5,1,3,4,6,2)]
openxlsx::write.xlsx(list('distribution' = freq.spcl.save),
                     firstRow=T, firstCol=T, asTable=T, withFilter=T,
                     file = paste0(path, '/distribution.xlsx'), startRow = 1, colNames = T,
                     rowNames = F, rows = NULL, cols = NULL, namedRegion = NULL, keepNA = T, na.string='N/A')

# Plot distribution
dist.spclds <- ggplot(freq.spcl) + 
  geom_point(aes(x = condition, y = percent, color = condition, fill = condition, shape = replicate), 
             position = position_jitterdodge(jitter.width = 0.1, jitter.height = 0, dodge.width = 0.4, seed = 2), 
             size = 1.6, stat = 'identity', alpha = 0.9, stroke=0.5) + 
  geom_segment(data = pval.spcl, aes(x=1.5+0.4,xend=1.5-0.4,y=y,yend=y)) + 
  geom_text(data = pval.spcl, aes(x = 1.5, y = max+8, label = padj), size = 3, angle = 0, hjust = 0.5) + 
  scale_x_discrete('') + 
  scale_y_continuous('% of total cells', limits = c(0,60), breaks = seq(0,60,10), expand = c(0.03,0)) + 
  scale_color_manual('Condition', values = col$gp) + 
  scale_fill_manual('Condition', values = col$gp, guide = guide_legend(override.aes = list(size = 4, alpha = 0.9))) + 
  scale_shape_manual('Replicate', values = c('1'=21,'2'=22,'3'=23,'4'=24), 
                     guide = guide_legend(override.aes = list(size = 4, alpha = 0.9, color='grey60', fill='grey60'))) +
  facet_grid(.~cluster, scales = 'free', space = 'free') + 
  ggtitle('OT1 cells', subtitle = 'Relative cluster distribution per sample') + theme_custom + 
  theme(aspect.ratio = NULL,axis.text.x = element_text(size = 14, color = 'black', angle = 90, vjust=0.5, hjust = 1)) #ExtData10C
```

### Expression of target genes

```{r filterdataexp, collapse=T, echo=F, warning=F, message=F, include=F}
# Function to draw dotplot
dotplot2 <- function(object=bd, sel=genes$sel1, cl=F, scale=T, b=15, gr=NULL, sample='OT1 cells', subtitle='Expression by cluster',smax=100) {
  sel <- sel[sel %in% rownames(object)]
  dt <- DotPlot(object, assay = 'SCTmerged', features = sel, cluster.idents = cl, scale.max=smax, group.by = gr)$data
  if(!is.null(gr)) dt <- cbind(dt, reshape2::colsplit(dt$id, pattern = '_', names = c('condition','cluster')))
  if(scale) l <- list(a=-1.5,b=1.5) else l <- list(a=0,b=b)
  p <- ggplot(dt, 
              aes(if(!is.null(gr)) factor(cluster, levels=rev(unique(cluster))) else factor(id, levels=rev(unique(id))), features.plot, color=if(scale) avg.exp.scaled else avg.exp, size=pct.exp)) + 
    geom_point() + scale_x_discrete('cluster') + scale_y_discrete('') + coord_flip() + 
    scale_color_gradientn(ifelse(scale,'z-score','Avg. exp.'), colours = if(scale) col$hm else col$hm2, oob = scales::squish, 
                          limits = c(l$a,l$b), breaks = seq(l$a,l$b, length.out = 3)) + 
    scale_size_continuous('Pct. exp', limits = c(0,smax), breaks = seq(0,smax,smax/4), range = c(0,6)) + 
    ggtitle(gsub('_',' ',sample), subtitle = subtitle) + theme_custom + 
    theme(aspect.ratio = length(unique(dt$id)) / length(sel), 
          strip.text = element_text(size = 12.8, face = 'plain', angle=0, vjust=0, hjust=0.5, margin = margin(5,0,5,0)), 
          axis.text.x = element_text(size = 12.8, color = 'black', angle = 90, vjust = 0.5, hjust = 1))
  if(!is.null(gr)) p + facet_grid(factor(condition, levels = levels(bd[[s]]$condition))~., scales = 'free', space = 'free') else p
}

# Plot expression
genes$sel <- c('Mki67','Ezh2','Id2','Id3','Gzma','Gzmb','Gzmk','Klrg1','Prf1','Fasl','Havcr2','Pdcd1','Lgals1','Lgals3','Il18r1','Il17ra','Cxcr3','Cxcr6','Klf2','Klf3','S1pr1','Tcf7','Slamf6','Ccr7','Bcl2','Il7r','Sell','Il6ra','Myc','Bcl2l1','Il2ra','Cd83','Tnfrsf18','Batf3','Bax','Icos','Cd81','Tnfrsf4','Tnfsf4','Tnfrsf9','Tnfsf14','Dhodh','Cad','Umps')
dp.sel <- dotplot2(object = bd[[s]], sel = genes$sel, gr=NULL) #ExtData10D

# Plot expression
df.bd <- data.frame(tx = bd[[s]]@reductions$tsne@cell.embeddings[,1], 
                    ty = bd[[s]]@reductions$tsne@cell.embeddings[,2], 
                    ux = bd[[s]]@reductions$umap@cell.embeddings[,1], 
                    uy = bd[[s]]@reductions$umap@cell.embeddings[,2], 
                    cells = colnames(bd[[s]]), 
                    sample = bd[[s]]@meta.data$sample, 
                    condition = bd[[s]]@meta.data$condition, 
                    cluster = bd[[s]]@meta.data$cluster, 
                    replicate = bd[[s]]@meta.data$replicate, 
                    t(as.matrix(GetAssayData(bd[[s]], slot = 'data')['Dhodh',,drop=F])))
df.bd <- reshape2::melt(df.bd, id.vars = c('tx', 'ty', 'ux', 'uy', 'cells', 'sample', 'condition','cluster','replicate'))
#df.bd$value.noise <- df.bd$value + rnorm(n = length(df.bd$value)) / 100000 #add noise

# Scale each gene
rescale <- function(scores,to=c(0,1)) if(any(scores > 1)) scales::rescale(scores, to=to) else scores
df.bd <- dplyr::bind_rows(Map(x=unique(df.bd$variable), function(x) {
  df.bd %>% filter(variable %in% x) %>% mutate(scaled = rescale(value))
}))

# Plot UMAP
um.Dhodh <- ggplot(df.bd %>% filter(variable %in% 'Dhodh'), aes(x = ux, y = uy, color = scaled)) + 
  ggrastr::rasterise(geom_point(shape = 16, size = 0.6, alpha = 1), dpi = 300) + 
  scale_color_gradientn('Exp.', colours = col$hm2, oob = scales::squish, 
                        limits = c(0,1), breaks = seq(0,1, length.out = 2), labels = c('min','max')) + 
  facet_grid(variable~condition) + 
  theme_custom2 + xlab('UMAP 1') + ylab('UMAP 2') + ggtitle(paste0('OT1 cells'), subtitle = 'Gene expression')

# Draw ridgeplot
rpa <- RidgePlot(bd[[s]], features = c('Dhodh'), ncol = 1, group.by = 'condition', assay = 'SCTmerged', slot = 'data', cols = c(alpha(col$gp[1], alpha = 0.6),col$gp[2]) )
```

### Transcriptional trajectory with diffusion pseudotime

- Use merged data

```{r trajectory, collapse=T, echo=F, warning=F, message=F, include=F}
# Extract normalized data from Seurat object
sd <- t(as.matrix(GetAssayData(bd[[s]], slot = "data")))

# Add annotation
sd <- destiny::as.ExpressionSet(as.data.frame(sd))
sd$cells <- names(Idents(bd[[s]]))
sd$condition <- bd[[s]]$condition
sd$sample <- bd[[s]]$sample
sd$cluster <- bd[[s]]$cluster

# Define variable genes to compute the diffusion map
varGenes <- as.character(VariableFeatures(bd[[s]]))

# Create diffusion map
rm(.Random.seed); .Random.seed <- as.integer(rep(1,626))
dm <- destiny::DiffusionMap(sd, verbose = T, n_eigs = 20, n_pcs = 50, vars = varGenes)
#saveRDS(dm, file = paste0(path, "/diffusion_map.rds"))
#dm <- readRDS(paste0(path, "/diffusion_map.rds"))

# Create pseudotime ordering
dpt <- destiny::DPT(dm, which.min(dm$DC1))
rm(.Random.seed)
#saveRDS(dpt, file = paste0(path, "/dpt.rds"))
#dpt <- readRDS(paste0(path, "/dpt.rds"))

# Extract data
df <- destiny::as.data.frame(dm)
df$DPT <- dpt[[paste0('DPT',which.min(dm$DC1))]]
df$tips <- ifelse(1:nrow(df) %in% destiny::tips(dpt)[1:3], 'tip', NA)
plot.dpt <- destiny::plot(dpt, pch = 20, axes = T, main = "dpt", dcs = c(1,3), root = 1, paths_to = c(2,3), w_width = 0.05, 
                          col_path = c("firebrick3", "royalblue2"), col_tip = "red", col_by = paste0('DPT',which.min(dm$DC1)) )

# Plot maps and pseudotime
plot.dm <- ggplot() + 
  geom_point(data=df, aes(DC1, DC3, colour = cluster), shape = 16, size = 0.8, alpha = 1) + 
  geom_path(data=as.data.frame(ggplot_build(plot.dpt)$data[3][[1]]), aes(x = x, y = y), size = 2, color = 'dodgerblue2') + 
  geom_path(data=as.data.frame(ggplot_build(plot.dpt)$data[4][[1]]), aes(x = x, y = y), size = 2, color = 'black') + 
  scale_color_manual("Cluster", values = col$cl, guide = guide_legend(override.aes = list(size = 4, alpha = 1))) + 
  scale_size_manual("", values = c(4,NA)) + ggtitle('OT1 cells', subtitle = 'Diffusion pseudotime') + 
  facet_grid(.~condition, scales = 'free', space = 'free') + theme_custom2 + theme(aspect.ratio = NULL)
```

-------------------------------------------------------------------------------------------------------------------

## Export plots

```{r filterdatasave, collapse=T, echo=F, warning=F, message=F, include=F}
# Save umap plots
ggsave(plot = grid(um.cls,rbind(c(1,1,1,1,1,1,1,1,1,2,3))), file = paste0(path, '/ExtData10A.pdf'), height = 4.32, width = 7.2)
ggsave(plot = grid(um.clr,rbind(c(1,1,1,1,1,1,1,1,1,2,3))), file = paste0(path, '/ExtData10B.pdf'), height = 6.6, width = 11.7)

# Save distribution plot
ggsave(plot = rmclip(dist.spclds), file = paste0(path, '/ExtData10C.pdf'), height = 3.8, width = 7)

# Save percentage expressing cells
ggsave(plot = rmclip(dp.sel), file = paste0(path, '/ExtData10D.pdf'), height = 4, width = 13)

# Save expression plots over UMAP
ggsave(plot = grid(um.Dhodh,rbind(c(1,1,1,1,1,2,3))), file = paste0(path, '/ExtData10E.pdf'), height = 4.5, width = 7.3)

# Save ridge plot
ggsave(plot = rmclip(rpa), file = paste0(path, '/ExtData10F.pdf'), height = 3, width = 5)

# Save Diffusion Map plots
ggsave(paste0(path, '/ExtData10G.pdf'), grid(plot.dm, rbind(c(1,1,1,1,1,1,1,1,2,2,3))), height = 4.35, width = 7.7)
```

-------------------------------------------------------------------------------------------------------------------

## Session info

```{r sessioninfo, collapse=T, echo=F, warning=F, message=F, include=F}
installed.packages() %>% rownames() %>% devtools::package_info()
#─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
# setting  value                       
# version  R version 4.0.4 (2021-02-15)
# os       macOS Big Sur 11.2.3        
# system   x86_64, darwin17.0          
# ui       RStudio                     
# language (EN)                        
# collate  en_US.UTF-8                 
# ctype    en_US.UTF-8                 
# tz       Europe/Berlin               

#─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
# package                * version    date       lib source                                       
# abind                    1.4-5      2016-07-21 [1] CRAN (R 4.0.2)                               
# ade4                     1.7-17     2021-06-17 [1] CRAN (R 4.0.2)                               
# amap                     0.8-18     2019-12-12 [1] CRAN (R 4.0.2)                               
# annotate                 1.68.0     2020-10-27 [1] Bioconductor                                 
# AnnotationDbi            1.52.0     2020-10-27 [1] Bioconductor                                 
# AnnotationFilter         1.14.0     2020-10-27 [1] Bioconductor                                 
# AnnotationHub            2.22.1     2021-04-16 [1] Bioconductor                                 
# ape                      5.6-2      2022-03-02 [1] CRAN (R 4.0.5)                               
# apeglm                   1.12.0     2020-10-27 [1] Bioconductor                                 
# aricode                  1.0.0      2020-06-26 [1] CRAN (R 4.0.2)                               
# arules                   1.6-7      2021-03-16 [1] CRAN (R 4.0.2)                               
# askpass                  1.1        2019-01-13 [1] CRAN (R 4.0.2)                               
# assertthat               0.2.1      2019-03-21 [1] CRAN (R 4.0.2)                               
# AUCell                   1.12.0     2020-10-27 [1] Bioconductor                                 
# babelgene                21.4       2021-04-26 [1] CRAN (R 4.0.2)                               
# backports                1.2.1      2020-12-09 [1] CRAN (R 4.0.2)                               
# base64enc                0.1-3      2015-07-28 [1] CRAN (R 4.0.2)                               
# batchelor                1.6.3      2021-04-16 [1] Bioconductor                                 
# bbmle                    1.0.23.1   2020-02-03 [1] CRAN (R 4.0.2)                               
# bcellViper               1.26.0     2020-10-29 [1] Bioconductor                                 
# bdsmatrix                1.3-4      2020-01-13 [1] CRAN (R 4.0.2)                               
# beachmat                 2.6.4      2020-12-20 [1] Bioconductor                                 
# beeswarm                 0.3.1      2021-03-07 [1] CRAN (R 4.0.2)                               
# BH                       1.75.0-0   2021-01-11 [1] CRAN (R 4.0.2)                               
# Biobase                  2.50.0     2020-10-27 [1] Bioconductor                                 
# BiocFileCache            1.14.0     2020-10-27 [1] Bioconductor                                 
# BiocGenerics             0.36.0     2020-10-27 [1] Bioconductor                                 
# BiocManager              1.30.10    2019-11-16 [1] CRAN (R 4.0.2)                               
# BiocNeighbors            1.8.2      2020-12-07 [1] Bioconductor                                 
# BiocParallel             1.24.1     2020-11-06 [1] Bioconductor                                 
# BiocSingular             1.6.0      2020-10-27 [1] Bioconductor                                 
# BiocVersion              3.12.0     2020-05-14 [1] Bioconductor                                 
# biomaRt                  2.46.3     2021-02-11 [1] Bioconductor                                 
# biomartr                 0.9.2      2020-01-10 [1] CRAN (R 4.0.2)                               
# Biostrings               2.58.0     2020-10-27 [1] Bioconductor                                 
# bit                      4.0.4      2020-08-04 [1] CRAN (R 4.0.2)                               
# bit64                    4.0.5      2020-08-30 [1] CRAN (R 4.0.2)                               
# bitops                   1.0-6      2013-08-17 [1] CRAN (R 4.0.2)                               
# blob                     1.2.1      2020-01-20 [1] CRAN (R 4.0.2)                               
# bluster                  1.0.0      2020-10-27 [1] Bioconductor                                 
# bookdown                 0.21       2020-10-13 [1] CRAN (R 4.0.2)                               
# boot                     1.3-26     2021-01-25 [1] CRAN (R 4.0.4)                               
# brew                     1.0-6      2011-04-13 [1] CRAN (R 4.0.2)                               
# brio                     1.1.1      2021-01-20 [1] CRAN (R 4.0.2)                               
# broom                    0.7.6      2021-04-05 [1] CRAN (R 4.0.2)                               
# bslib                    0.4.2      2022-12-16 [1] CRAN (R 4.0.4)                               
# cachem                   1.0.4      2021-02-13 [1] CRAN (R 4.0.2)                               
# Cairo                    1.5-12.2   2020-07-07 [1] CRAN (R 4.0.2)                               
# callr                    3.5.1      2020-10-13 [1] CRAN (R 4.0.2)                               
# car                      3.0-10     2020-09-29 [1] CRAN (R 4.0.2)                               
# carData                  3.0-4      2020-05-22 [1] CRAN (R 4.0.2)                               
# caTools                  1.18.1     2021-01-11 [1] CRAN (R 4.0.2)                               
# celldex                  1.0.0      2020-10-29 [1] Bioconductor                                 
# cellranger               1.1.0      2016-07-27 [1] CRAN (R 4.0.2)                               
# cerebroApp               1.3.1      2022-03-07 [1] Github (romanhaa/cerebroApp@0de48b6)         
# checkmate                2.0.0      2020-02-06 [1] CRAN (R 4.0.2)                               
# circlize                 0.4.12     2021-01-08 [1] CRAN (R 4.0.2)                               
# class                    7.3-18     2021-01-24 [1] CRAN (R 4.0.4)                               
# classInt                 0.4-3      2020-04-07 [1] CRAN (R 4.0.2)                               
# cli                      2.3.1      2021-02-23 [1] CRAN (R 4.0.2)                               
# clipr                    0.7.1      2020-10-08 [1] CRAN (R 4.0.2)                               
# clue                     0.3-59     2021-04-16 [1] CRAN (R 4.0.2)                               
# cluster                  2.1.0      2019-06-19 [1] CRAN (R 4.0.4)                               
# clusterCrit              1.2.8      2018-07-26 [1] CRAN (R 4.0.2)                               
# clusterProfiler          3.18.1     2021-02-11 [1] Bioconductor                                 
# coda                     0.19-4     2020-09-30 [1] CRAN (R 4.0.2)                               
# codetools                0.2-18     2020-11-04 [1] CRAN (R 4.0.4)                               
# colorjam                 0.0.22.900 2021-08-17 [1] Github (jmw86069/colorjam@94237b5)           
# colorRamps               2.3.1      2022-05-02 [1] CRAN (R 4.0.4)                               
# colorspace               2.0-0      2020-11-11 [1] CRAN (R 4.0.2)                               
# colourpicker             1.1.1      2021-10-04 [1] CRAN (R 4.0.2)                               
# commonmark               1.7        2018-12-01 [1] CRAN (R 4.0.2)                               
# ComplexHeatmap           2.6.2      2020-11-12 [1] Bioconductor                                 
# config                   0.3.1      2020-12-17 [1] CRAN (R 4.0.2)                               
# conquer                  1.0.2      2020-08-27 [1] CRAN (R 4.0.2)                               
# CoRegNet                 1.28.0     2020-10-27 [1] Bioconductor                                 
# corpcor                  1.6.9      2017-04-01 [1] CRAN (R 4.0.2)                               
# corrplot                 0.84       2017-10-16 [1] CRAN (R 4.0.2)                               
# covr                     3.5.1      2020-09-16 [1] CRAN (R 4.0.2)                               
# cowplot                  1.1.1      2020-12-30 [1] CRAN (R 4.0.2)                               
# cpp11                    0.4.2      2021-11-30 [1] CRAN (R 4.0.2)                               
# crayon                   1.4.1      2021-02-08 [1] CRAN (R 4.0.2)                               
# credentials              1.3.0      2020-07-21 [1] CRAN (R 4.0.2)                               
# crosstalk                1.1.1      2021-01-12 [1] CRAN (R 4.0.2)                               
# cubature                 2.0.4.4    2022-03-22 [1] CRAN (R 4.0.5)                               
# curl                     4.3        2019-12-02 [1] CRAN (R 4.0.1)                               
# data.table               1.14.0     2021-02-21 [1] CRAN (R 4.0.2)                               
# DBI                      1.1.1      2021-01-15 [1] CRAN (R 4.0.2)                               
# dbplyr                   2.1.0      2021-02-03 [1] CRAN (R 4.0.2)                               
# DelayedArray             0.16.2     2021-02-26 [1] Bioconductor                                 
# DelayedMatrixStats       1.12.3     2021-02-03 [1] Bioconductor                                 
# deldir                   0.2-10     2021-02-16 [1] CRAN (R 4.0.2)                               
# DEoptimR                 1.0-9      2021-05-24 [1] CRAN (R 4.0.2)                               
# desc                     1.3.0      2021-03-05 [1] CRAN (R 4.0.2)                               
# DESeq2                   1.30.1     2021-02-19 [1] Bioconductor                                 
# destiny                  3.4.0      2020-10-27 [1] Bioconductor                                 
# devtools                 2.3.2      2020-09-18 [1] CRAN (R 4.0.2)                               
# diffobj                  0.3.4      2021-03-22 [1] CRAN (R 4.0.2)                               
# digest                   0.6.27     2020-10-24 [1] CRAN (R 4.0.2)                               
# DO.db                    2.9        2021-03-18 [1] Bioconductor                                 
# doMC                     1.3.7      2020-10-14 [1] CRAN (R 4.0.2)                               
# doParallel               1.0.16     2020-10-16 [1] CRAN (R 4.0.2)                               
# doRNG                    1.8.2      2020-01-27 [1] CRAN (R 4.0.2)                               
# dorothea                 1.2.2      2021-04-19 [1] Bioconductor                                 
# DOSE                     3.16.0     2020-10-27 [1] Bioconductor                                 
# downloader               0.4        2015-07-09 [1] CRAN (R 4.0.2)                               
# dplyr                  * 1.0.5      2021-03-05 [1] CRAN (R 4.0.2)                               
# dqrng                    0.2.1      2019-05-17 [1] CRAN (R 4.0.2)                               
# DT                       0.17       2021-01-06 [1] CRAN (R 4.0.2)                               
# e1071                    1.7-8      2021-07-28 [1] CRAN (R 4.0.2)                               
# edgeR                    3.32.1     2021-01-14 [1] Bioconductor                                 
# ellipsis                 0.3.1      2020-05-15 [1] CRAN (R 4.0.2)                               
# emdbook                  1.3.12     2020-02-19 [1] CRAN (R 4.0.2)                               
# enrichplot               1.10.2     2021-01-28 [1] Bioconductor                                 
# ensembldb                2.14.1     2021-04-19 [1] Bioconductor                                 
# evaluate                 0.14       2019-05-28 [1] CRAN (R 4.0.1)                               
# evd                      2.3-6      2022-04-12 [1] CRAN (R 4.0.4)                               
# evmix                    2.12       2019-09-03 [1] CRAN (R 4.0.2)                               
# ExperimentHub            1.16.1     2021-04-16 [1] Bioconductor                                 
# expm                     0.999-6    2021-01-13 [1] CRAN (R 4.0.2)                               
# fansi                    0.4.2      2021-01-15 [1] CRAN (R 4.0.2)                               
# farver                   2.1.0      2021-02-28 [1] CRAN (R 4.0.2)                               
# fastmap                  1.1.0      2021-01-25 [1] CRAN (R 4.0.2)                               
# fastmatch                1.1-0      2017-01-28 [1] CRAN (R 4.0.2)                               
# fdrtool                  1.2.16     2021-01-06 [1] CRAN (R 4.0.2)                               
# fgsea                    1.16.0     2020-10-27 [1] Bioconductor                                 
# fitdistrplus             1.1-3      2020-12-05 [1] CRAN (R 4.0.2)                               
# FNN                      1.1.3      2019-02-15 [1] CRAN (R 4.0.2)                               
# fontawesome              0.2.2      2021-07-02 [1] CRAN (R 4.0.2)                               
# forcats                  0.5.1      2021-01-27 [1] CRAN (R 4.0.2)                               
# foreach                  1.5.1      2020-10-15 [1] CRAN (R 4.0.2)                               
# foreign                  0.8-81     2020-12-22 [1] CRAN (R 4.0.4)                               
# formatR                  1.8        2021-03-12 [1] CRAN (R 4.0.2)                               
# Formula                  1.2-4      2020-10-16 [1] CRAN (R 4.0.2)                               
# fs                       1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                               
# furrr                    0.2.2      2021-01-29 [1] CRAN (R 4.0.2)                               
# futile.logger            1.4.3      2016-07-10 [1] CRAN (R 4.0.2)                               
# futile.options           1.0.1      2018-04-20 [1] CRAN (R 4.0.2)                               
# future                   1.21.0     2020-12-10 [1] CRAN (R 4.0.2)                               
# future.apply             1.7.0      2021-01-04 [1] CRAN (R 4.0.2)                               
# gdata                    2.18.0     2017-06-06 [1] CRAN (R 4.0.2)                               
# genefilter               1.72.1     2021-01-21 [1] Bioconductor                                 
# geneplotter              1.68.0     2020-10-27 [1] Bioconductor                                 
# generics                 0.1.0      2020-10-31 [1] CRAN (R 4.0.2)                               
# GenomeInfoDb             1.26.4     2021-03-10 [1] Bioconductor                                 
# GenomeInfoDbData         1.2.4      2021-03-15 [1] Bioconductor                                 
# GenomicAlignments        1.26.0     2020-10-27 [1] Bioconductor                                 
# GenomicFeatures          1.42.3     2021-04-04 [1] Bioconductor                                 
# GenomicRanges            1.42.0     2020-10-27 [1] Bioconductor                                 
# gert                     1.2.0      2021-02-14 [1] CRAN (R 4.0.2)                               
# GetoptLong               1.0.5      2020-12-15 [1] CRAN (R 4.0.2)                               
# ggalluvial               0.12.3     2020-12-05 [1] CRAN (R 4.0.2)                               
# ggbeeswarm               0.6.0      2017-08-07 [1] CRAN (R 4.0.2)                               
# ggdendro                 0.1.23     2022-02-16 [1] CRAN (R 4.0.5)                               
# ggfittext                0.9.1      2021-01-30 [1] CRAN (R 4.0.2)                               
# ggforce                  0.3.3      2021-03-05 [1] CRAN (R 4.0.2)                               
# ggfortify                0.4.15     2022-11-11 [1] CRAN (R 4.0.4)                               
# ggnewscale               0.4.5      2021-01-11 [1] CRAN (R 4.0.2)                               
# ggplot.multistats        1.0.0      2019-10-28 [1] CRAN (R 4.0.2)                               
# ggplot2                * 3.3.3      2020-12-30 [1] CRAN (R 4.0.2)                               
# ggplotify                0.0.5      2020-03-12 [1] CRAN (R 4.0.2)                               
# ggpubr                   0.4.0      2020-06-27 [1] CRAN (R 4.0.2)                               
# ggraph                   2.0.5      2021-02-23 [1] CRAN (R 4.0.2)                               
# ggrastr                  0.2.3      2021-03-01 [1] CRAN (R 4.0.2)                               
# ggrepel                  0.9.1      2021-01-15 [1] CRAN (R 4.0.2)                               
# ggridges                 0.5.3      2021-01-08 [1] CRAN (R 4.0.2)                               
# ggsci                    2.9        2018-05-14 [1] CRAN (R 4.0.2)                               
# ggsignif                 0.6.1      2021-02-23 [1] CRAN (R 4.0.2)                               
# ggthemes                 4.2.4      2021-01-20 [1] CRAN (R 4.0.2)                               
# gh                       1.2.0      2020-11-27 [1] CRAN (R 4.0.2)                               
# gitcreds                 0.1.1      2020-12-04 [1] CRAN (R 4.0.2)                               
# glasso                   1.11       2019-10-01 [1] CRAN (R 4.0.2)                               
# glmGamPoi                1.2.0      2020-10-27 [1] Bioconductor                                 
# GlobalOptions            0.1.2      2020-06-10 [1] CRAN (R 4.0.2)                               
# globals                  0.14.0     2020-11-22 [1] CRAN (R 4.0.2)                               
# glue                     1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                               
# gmodels                  2.18.1     2018-06-25 [1] CRAN (R 4.0.2)                               
# GO.db                    3.12.1     2021-03-18 [1] Bioconductor                                 
# goftest                  1.2-2      2019-12-02 [1] CRAN (R 4.0.2)                               
# GOSemSim                 2.16.1     2020-10-29 [1] Bioconductor                                 
# gplots                   3.1.1      2020-11-28 [1] CRAN (R 4.0.2)                               
# graph                    1.68.0     2020-10-27 [1] Bioconductor                                 
# graphite                 1.36.0     2020-10-27 [1] Bioconductor                                 
# graphlayouts             0.7.1      2020-10-26 [1] CRAN (R 4.0.2)                               
# gridExtra                2.3        2017-09-09 [1] CRAN (R 4.0.2)                               
# gridGraphics             0.5-1      2020-12-13 [1] CRAN (R 4.0.2)                               
# grr                      0.9.5      2016-08-26 [1] CRAN (R 4.0.2)                               
# GSEABase                 1.52.1     2020-12-11 [1] Bioconductor                                 
# gsl                      2.1-7.1    2021-11-02 [1] CRAN (R 4.0.2)                               
# GSVA                     1.38.2     2021-02-11 [1] Bioconductor                                 
# gtable                   0.3.0      2019-03-25 [1] CRAN (R 4.0.2)                               
# gtools                   3.8.2      2020-03-31 [1] CRAN (R 4.0.2)                               
# haven                    2.4.0      2021-04-14 [1] CRAN (R 4.0.2)                               
# HDF5Array                1.18.1     2021-02-04 [1] Bioconductor                                 
# hdf5r                    1.3.2      2020-03-25 [1] CRAN (R 4.0.1)                               
# here                     1.0.1      2020-12-13 [1] CRAN (R 4.0.2)                               
# hexbin                   1.28.2     2021-01-08 [1] CRAN (R 4.0.2)                               
# highr                    0.8        2019-03-20 [1] CRAN (R 4.0.2)                               
# Hmisc                    4.5-0      2021-02-28 [1] CRAN (R 4.0.2)                               
# hms                      1.0.0      2021-01-13 [1] CRAN (R 4.0.2)                               
# htmlTable                2.2.1      2021-05-18 [1] CRAN (R 4.0.2)                               
# htmltools                0.5.4      2022-12-07 [1] CRAN (R 4.0.4)                               
# htmlwidgets              1.5.3      2020-12-10 [1] CRAN (R 4.0.2)                               
# httpuv                   1.5.5      2021-01-13 [1] CRAN (R 4.0.2)                               
# httr                     1.4.2      2020-07-20 [1] CRAN (R 4.0.2)                               
# ica                      1.0-2      2018-05-24 [1] CRAN (R 4.0.2)                               
# igraph                   1.2.6      2020-10-06 [1] CRAN (R 4.0.2)                               
# ini                      0.3.1      2018-05-20 [1] CRAN (R 4.0.2)                               
# interactiveDisplayBase   1.28.0     2020-10-27 [1] Bioconductor                                 
# IRanges                  2.24.1     2020-12-12 [1] Bioconductor                                 
# irlba                    2.3.3      2019-02-05 [1] CRAN (R 4.0.2)                               
# isoband                  0.2.4      2021-03-03 [1] CRAN (R 4.0.2)                               
# iterators                1.0.13     2020-10-15 [1] CRAN (R 4.0.2)                               
# jamba                    0.0.65.900 2021-08-17 [1] Github (jmw86069/jamba@537c1aa)              
# jpeg                     0.1-9      2021-07-24 [1] CRAN (R 4.0.2)                               
# jquerylib                0.1.3      2020-12-17 [1] CRAN (R 4.0.2)                               
# jsonlite                 1.7.2      2020-12-09 [1] CRAN (R 4.0.2)                               
# KEGGgraph                1.50.0     2020-10-27 [1] Bioconductor                                 
# KEGGREST                 1.30.1     2020-11-23 [1] Bioconductor                                 
# keras                    2.9.0      2022-05-23 [1] CRAN (R 4.0.4)                               
# kernlab                  0.9-29     2019-11-12 [1] CRAN (R 4.0.2)                               
# KernSmooth               2.23-18    2020-10-29 [1] CRAN (R 4.0.4)                               
# knitr                    1.36       2021-09-29 [1] CRAN (R 4.0.2)                               
# knn.covertree            1.0        2019-10-28 [1] CRAN (R 4.0.2)                               
# labeling                 0.4.2      2020-10-20 [1] CRAN (R 4.0.2)                               
# laeken                   0.5.2      2021-10-06 [1] CRAN (R 4.0.2)                               
# lambda.r                 1.2.4      2019-09-18 [1] CRAN (R 4.0.2)                               
# later                    1.1.0.1    2020-06-05 [1] CRAN (R 4.0.2)                               
# lattice                  0.20-41    2020-04-02 [1] CRAN (R 4.0.4)                               
# latticeExtra             0.6-29     2019-12-19 [1] CRAN (R 4.0.2)                               
# lavaan                   0.6-9      2021-06-27 [1] CRAN (R 4.0.2)                               
# lazyeval                 0.2.2      2019-03-15 [1] CRAN (R 4.0.2)                               
# LearnBayes               2.15.1     2018-03-18 [1] CRAN (R 4.0.2)                               
# leiden                   0.3.7      2021-01-26 [1] CRAN (R 4.0.2)                               
# leidenbase               0.1.3      2021-08-03 [1] Github (cole-trapnell-lab/leidenbase@430f22a)
# lifecycle                1.0.0      2021-02-15 [1] CRAN (R 4.0.2)                               
# limma                    3.46.0     2020-10-27 [1] Bioconductor                                 
# listenv                  0.8.0      2019-12-05 [1] CRAN (R 4.0.2)                               
# lme4                     1.1-26     2020-12-01 [1] CRAN (R 4.0.2)                               
# lmtest                   0.9-38     2020-09-09 [1] CRAN (R 4.0.2)                               
# locfit                   1.5-9.4    2020-03-25 [1] CRAN (R 4.0.2)                               
# magrittr                 2.0.1      2020-11-17 [1] CRAN (R 4.0.2)                               
# maptools                 1.1-1      2021-03-15 [1] CRAN (R 4.0.2)                               
# markdown                 1.1        2019-08-07 [1] CRAN (R 4.0.2)                               
# MASS                     7.3-53     2020-09-09 [1] CRAN (R 4.0.4)                               
# mathjaxr                 1.4-0      2021-03-01 [1] CRAN (R 4.0.2)                               
# Matrix                   1.3-2      2021-01-06 [1] CRAN (R 4.0.4)                               
# Matrix.utils             0.9.8      2020-02-26 [1] CRAN (R 4.0.2)                               
# MatrixGenerics           1.2.1      2021-01-30 [1] Bioconductor                                 
# MatrixModels             0.5-0      2021-03-02 [1] CRAN (R 4.0.2)                               
# matrixStats              0.58.0     2021-01-29 [1] CRAN (R 4.0.2)                               
# memoise                  2.0.1      2021-11-26 [1] CRAN (R 4.0.2)                               
# metap                    1.4        2020-07-12 [1] CRAN (R 4.0.2)                               
# mgcv                     1.8-33     2020-08-27 [1] CRAN (R 4.0.4)                               
# mime                     0.10       2021-02-13 [1] CRAN (R 4.0.2)                               
# miniUI                   0.1.1.1    2018-05-18 [1] CRAN (R 4.0.2)                               
# minqa                    1.2.4      2014-10-09 [1] CRAN (R 4.0.2)                               
# mixtools                 1.2.0      2020-02-07 [1] CRAN (R 4.0.2)                               
# mnormt                   2.0.2      2020-09-01 [1] CRAN (R 4.0.2)                               
# monocle3                 1.0.0      2021-08-03 [1] Github (cole-trapnell-lab/monocle3@004c096)  
# msigdbr                  7.4.1      2021-05-05 [1] CRAN (R 4.0.2)                               
# multcomp                 1.4-17     2021-04-29 [1] CRAN (R 4.0.2)                               
# multienrichjam           0.0.49.900 2021-08-17 [1] Github (jmw86069/multienrichjam@629b347)     
# multtest                 2.46.0     2020-10-27 [1] Bioconductor                                 
# munsell                  0.5.0      2018-06-12 [1] CRAN (R 4.0.2)                               
# mutoss                   0.1-12     2017-12-04 [1] CRAN (R 4.0.2)                               
# mvtnorm                  1.1-1      2020-06-09 [1] CRAN (R 4.0.2)                               
# nlme                     3.1-152    2021-02-04 [1] CRAN (R 4.0.4)                               
# nloptr                   1.2.2.2    2020-07-02 [1] CRAN (R 4.0.2)                               
# nnet                     7.3-15     2021-01-24 [1] CRAN (R 4.0.4)                               
# numDeriv                 2016.8-1.1 2019-06-06 [1] CRAN (R 4.0.2)                               
# openssl                  1.4.3      2020-09-18 [1] CRAN (R 4.0.2)                               
# openxlsx                 4.2.3      2020-10-27 [1] CRAN (R 4.0.2)                               
# org.Hs.eg.db             3.12.0     2021-03-25 [1] Bioconductor                                 
# org.Mm.eg.db             3.12.0     2021-03-25 [1] Bioconductor                                 
# parallelly               1.24.0     2021-03-14 [1] CRAN (R 4.0.4)                               
# patchwork                1.1.1      2020-12-17 [1] CRAN (R 4.0.2)                               
# pathview                 1.30.1     2020-12-10 [1] Bioconductor                                 
# pbapply                  1.4-3      2020-08-18 [1] CRAN (R 4.0.2)                               
# pbivnorm                 0.6.0      2015-01-23 [1] CRAN (R 4.0.2)                               
# pbkrtest                 0.5.1      2021-03-09 [1] CRAN (R 4.0.2)                               
# pbmcapply                1.5.0      2019-07-10 [1] CRAN (R 4.0.2)                               
# pcaMethods               1.82.0     2020-10-27 [1] Bioconductor                                 
# permute                  0.9-7      2022-01-27 [1] CRAN (R 4.0.5)                               
# pheatmap                 1.0.12     2019-01-04 [1] CRAN (R 4.0.2)                               
# philentropy              0.5.0      2021-05-12 [1] CRAN (R 4.0.2)                               
# pillar                   1.5.1      2021-03-05 [1] CRAN (R 4.0.2)                               
# pixmap                   0.4-12     2021-01-29 [1] CRAN (R 4.0.2)                               
# pkgbuild                 1.2.0      2020-12-15 [1] CRAN (R 4.0.2)                               
# pkgconfig                2.0.3      2019-09-22 [1] CRAN (R 4.0.2)                               
# pkgload                  1.2.0      2021-02-23 [1] CRAN (R 4.0.2)                               
# plogr                    0.2.0      2018-03-25 [1] CRAN (R 4.0.2)                               
# plotly                   4.9.3      2021-01-10 [1] CRAN (R 4.0.2)                               
# plotrix                  3.8-1      2021-01-21 [1] CRAN (R 4.0.2)                               
# plyr                     1.8.6      2020-03-03 [1] CRAN (R 4.0.2)                               
# png                      0.1-7      2013-12-03 [1] CRAN (R 4.0.2)                               
# polyclip                 1.10-0     2019-03-14 [1] CRAN (R 4.0.2)                               
# polynom                  1.4-0      2019-03-22 [1] CRAN (R 4.0.2)                               
# powerTCR                 1.10.3     2021-03-16 [1] Bioconductor                                 
# pracma                   2.3.8      2022-03-04 [1] CRAN (R 4.0.5)                               
# praise                   1.0.0      2015-08-11 [1] CRAN (R 4.0.2)                               
# prettyunits              1.1.1      2020-01-24 [1] CRAN (R 4.0.2)                               
# princurve                2.1.6      2021-01-18 [1] CRAN (R 4.0.2)                               
# processx                 3.5.0      2021-03-23 [1] CRAN (R 4.0.4)                               
# progress                 1.2.2      2019-05-16 [1] CRAN (R 4.0.2)                               
# promises                 1.2.0.1    2021-02-11 [1] CRAN (R 4.0.2)                               
# ProtGenerics             1.22.0     2020-10-27 [1] Bioconductor                                 
# proxy                    0.4-26     2021-06-07 [1] CRAN (R 4.0.2)                               
# ps                       1.6.0      2021-02-28 [1] CRAN (R 4.0.2)                               
# pscl                     1.5.5      2020-03-07 [1] CRAN (R 4.0.2)                               
# psych                    2.1.6      2021-06-18 [1] CRAN (R 4.0.2)                               
# purrr                    0.3.4      2020-04-17 [1] CRAN (R 4.0.2)                               
# qgraph                   1.6.9      2021-01-28 [1] CRAN (R 4.0.2)                               
# quantreg                 5.85       2021-02-24 [1] CRAN (R 4.0.2)                               
# qvalue                   2.22.0     2020-10-27 [1] Bioconductor                                 
# R.methodsS3              1.8.1      2020-08-26 [1] CRAN (R 4.0.2)                               
# R.oo                     1.24.0     2020-08-26 [1] CRAN (R 4.0.2)                               
# R.utils                  2.10.1     2020-08-26 [1] CRAN (R 4.0.2)                               
# R6                       2.5.0      2020-10-28 [1] CRAN (R 4.0.2)                               
# ragg                     1.1.2      2021-03-17 [1] CRAN (R 4.0.2)                               
# ranger                   0.13.1     2021-07-14 [1] CRAN (R 4.0.2)                               
# RANN                     2.6.1      2019-01-08 [1] CRAN (R 4.0.2)                               
# rappdirs                 0.3.3      2021-01-31 [1] CRAN (R 4.0.2)                               
# raster                   3.4-13     2021-06-18 [1] CRAN (R 4.0.2)                               
# rbibutils                2.1.1      2021-04-28 [1] CRAN (R 4.0.2)                               
# rcmdcheck                1.3.3      2019-05-07 [1] CRAN (R 4.0.2)                               
# RColorBrewer             1.1-2      2014-12-07 [1] CRAN (R 4.0.2)                               
# Rcpp                     1.0.8.3    2022-03-17 [1] CRAN (R 4.0.5)                               
# RcppAnnoy                0.0.18     2020-12-15 [1] CRAN (R 4.0.2)                               
# RcppArmadillo            0.10.2.2.0 2021-03-09 [1] CRAN (R 4.0.2)                               
# RcppEigen                0.3.3.9.1  2020-12-17 [1] CRAN (R 4.0.2)                               
# RcppHNSW                 0.3.0      2020-09-06 [1] CRAN (R 4.0.2)                               
# RcppNumerical            0.4-0      2019-12-02 [1] CRAN (R 4.0.2)                               
# RcppProgress             0.4.2      2020-02-06 [1] CRAN (R 4.0.2)                               
# RcppTOML                 0.1.7      2020-12-02 [1] CRAN (R 4.0.2)                               
# RCurl                    1.98-1.3   2021-03-16 [1] CRAN (R 4.0.4)                               
# Rdpack                   2.1.1      2021-02-23 [1] CRAN (R 4.0.2)                               
# reactome.db              1.74.0     2021-03-25 [1] Bioconductor                                 
# ReactomePA               1.34.0     2020-10-27 [1] Bioconductor                                 
# readr                    1.4.0      2020-10-05 [1] CRAN (R 4.0.2)                               
# readxl                   1.3.1      2019-03-13 [1] CRAN (R 4.0.2)                               
# rematch                  1.0.1      2016-04-21 [1] CRAN (R 4.0.2)                               
# rematch2                 2.1.2      2020-05-01 [1] CRAN (R 4.0.2)                               
# remotes                  2.2.0      2020-07-21 [1] CRAN (R 4.0.2)                               
# reshape2                 1.4.4      2020-04-09 [1] CRAN (R 4.0.2)                               
# ResidualMatrix           1.0.0      2020-10-27 [1] Bioconductor                                 
# reticulate               1.25       2022-05-11 [1] CRAN (R 4.0.4)                               
# rex                      1.2.0      2020-04-21 [1] CRAN (R 4.0.2)                               
# rgl                      0.107.14   2021-08-21 [1] CRAN (R 4.0.2)                               
# Rgraphviz                2.34.0     2020-10-27 [1] Bioconductor                                 
# rhdf5                    2.34.0     2020-10-27 [1] Bioconductor                                 
# rhdf5filters             1.2.0      2020-10-27 [1] Bioconductor                                 
# Rhdf5lib                 1.12.1     2021-01-26 [1] Bioconductor                                 
# RhpcBLASctl              0.20-137   2020-05-17 [1] CRAN (R 4.0.2)                               
# Rhtslib                  1.22.0     2020-10-27 [1] Bioconductor                                 
# rio                      0.5.26     2021-03-01 [1] CRAN (R 4.0.2)                               
# rjson                    0.2.20     2018-06-08 [1] CRAN (R 4.0.2)                               
# rlang                    0.4.10     2020-12-30 [1] CRAN (R 4.0.2)                               
# rmarkdown                2.19       2022-12-15 [1] CRAN (R 4.0.4)                               
# rngtools                 1.5        2020-01-23 [1] CRAN (R 4.0.2)                               
# robustbase               0.93-9     2021-09-27 [1] CRAN (R 4.0.2)                               
# ROCR                     1.0-11     2020-05-02 [1] CRAN (R 4.0.2)                               
# roxygen2                 7.1.1      2020-06-27 [1] CRAN (R 4.0.2)                               
# rpart                    4.1-15     2019-04-12 [1] CRAN (R 4.0.4)                               
# rprojroot                2.0.2      2020-11-15 [1] CRAN (R 4.0.2)                               
# rsample                  0.1.0      2021-05-08 [1] CRAN (R 4.0.2)                               
# Rsamtools                2.6.0      2020-10-27 [1] Bioconductor                                 
# RSpectra                 0.16-0     2019-12-01 [1] CRAN (R 4.0.2)                               
# RSQLite                  2.2.4      2021-03-12 [1] CRAN (R 4.0.2)                               
# rstatix                  0.7.0      2021-02-13 [1] CRAN (R 4.0.2)                               
# rstudioapi               0.13       2020-11-12 [1] CRAN (R 4.0.2)                               
# rsvd                     1.0.5      2021-04-16 [1] CRAN (R 4.0.2)                               
# rtracklayer              1.50.0     2020-10-27 [1] Bioconductor                                 
# Rtsne                    0.15       2018-11-10 [1] CRAN (R 4.0.2)                               
# rvcheck                  0.1.8      2020-03-01 [1] CRAN (R 4.0.2)                               
# rversions                2.0.2      2020-05-25 [1] CRAN (R 4.0.2)                               
# s2                       1.0.6      2021-06-17 [1] CRAN (R 4.0.2)                               
# S4Vectors                0.28.1     2020-12-09 [1] Bioconductor                                 
# sandwich                 3.0-1      2021-05-18 [1] CRAN (R 4.0.2)                               
# sass                     0.4.4      2022-11-24 [1] CRAN (R 4.0.4)                               
# scales                   1.1.1      2020-05-11 [1] CRAN (R 4.0.2)                               
# scater                   1.18.6     2021-02-26 [1] Bioconductor                                 
# scattermore              0.7        2020-11-24 [1] CRAN (R 4.0.2)                               
# scatterpie               0.1.5      2020-09-09 [1] CRAN (R 4.0.2)                               
# scatterplot3d            0.3-41     2018-03-14 [1] CRAN (R 4.0.2)                               
# scCCESS                  0.2.0      2022-06-29 [1] Github (PYangLab/scCCESS@5a79afe)            
# scran                    1.18.7     2021-04-16 [1] Bioconductor                                 
# scRepertoire             1.0.0      2020-10-27 [1] Bioconductor                                 
# sctransform            * 0.3.2      2020-12-16 [1] CRAN (R 4.0.2)                               
# scuttle                  1.0.4      2020-12-17 [1] Bioconductor                                 
# segmented                1.3-4      2021-04-22 [1] CRAN (R 4.0.2)                               
# seqinr                   4.2-8      2021-06-09 [1] CRAN (R 4.0.2)                               
# sessioninfo              1.1.1      2018-11-05 [1] CRAN (R 4.0.2)                               
# Seurat                 * 4.0.1      2021-03-18 [1] CRAN (R 4.0.4)                               
# SeuratObject           * 4.0.0      2021-01-15 [1] CRAN (R 4.0.2)                               
# SeuratWrappers           0.3.0      2021-08-03 [1] Github (satijalab/seurat-wrappers@8510069)   
# sf                       1.0-2      2021-07-26 [1] CRAN (R 4.0.2)                               
# shades                   1.4.0      2019-08-02 [1] CRAN (R 4.0.2)                               
# shadowtext               0.0.7      2019-11-06 [1] CRAN (R 4.0.2)                               
# shape                    1.4.5      2020-09-13 [1] CRAN (R 4.0.2)                               
# shiny                    1.6.0      2021-01-25 [1] CRAN (R 4.0.2)                               
# shinycssloaders          1.0.0      2020-07-28 [1] CRAN (R 4.0.2)                               
# shinydashboard           0.7.2      2021-09-30 [1] CRAN (R 4.0.2)                               
# shinyFiles               0.9.1      2021-11-10 [1] CRAN (R 4.0.2)                               
# shinyjs                  2.1.0      2021-12-23 [1] CRAN (R 4.0.2)                               
# shinyWidgets             0.6.4      2022-02-06 [1] CRAN (R 4.0.5)                               
# SIMLR                    1.18.0     2022-06-29 [1] Github (yulijia/SIMLR@2d2e97a)               
# SingleCellExperiment     1.12.0     2020-10-27 [1] Bioconductor                                 
# SingleR                  1.4.1      2021-02-02 [1] Bioconductor                                 
# sitmo                    2.0.1      2019-01-07 [1] CRAN (R 4.0.2)                               
# slam                     0.1-48     2020-12-03 [1] CRAN (R 4.0.2)                               
# slider                   0.2.2      2021-07-01 [1] CRAN (R 4.0.2)                               
# slingshot                1.8.0      2020-10-27 [1] Bioconductor                                 
# smoother                 1.1        2015-04-16 [1] CRAN (R 4.0.2)                               
# sn                       2.0.0      2021-03-28 [1] CRAN (R 4.0.2)                               
# snow                     0.4-3      2018-09-14 [1] CRAN (R 4.0.2)                               
# sourcetools              0.1.7      2018-04-25 [1] CRAN (R 4.0.2)                               
# sp                       1.4-5      2021-01-10 [1] CRAN (R 4.0.2)                               
# SparseM                  1.81       2021-02-18 [1] CRAN (R 4.0.2)                               
# sparseMatrixStats        1.2.1      2021-02-02 [1] Bioconductor                                 
# spatial                  7.3-13     2021-01-24 [1] CRAN (R 4.0.4)                               
# spatstat                 2.0-1      2021-03-13 [1] CRAN (R 4.0.4)                               
# spatstat.core            2.0-0      2021-03-23 [1] CRAN (R 4.0.4)                               
# spatstat.data            2.1-0      2021-03-21 [1] CRAN (R 4.0.2)                               
# spatstat.geom            2.0-1      2021-03-22 [1] CRAN (R 4.0.2)                               
# spatstat.linnet          2.0-0      2021-03-18 [1] CRAN (R 4.0.4)                               
# spatstat.sparse          2.0-0      2021-03-16 [1] CRAN (R 4.0.4)                               
# spatstat.utils           2.1-0      2021-03-15 [1] CRAN (R 4.0.4)                               
# spData                   0.3.10     2021-06-18 [1] CRAN (R 4.0.2)                               
# spdep                    1.1-8      2021-05-23 [1] CRAN (R 4.0.2)                               
# speedglm                 0.3-3      2021-01-08 [1] CRAN (R 4.0.2)                               
# statmod                  1.4.35     2020-10-19 [1] CRAN (R 4.0.2)                               
# stringi                  1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                               
# stringr                  1.4.0      2019-02-10 [1] CRAN (R 4.0.2)                               
# SummarizedExperiment     1.20.0     2020-10-27 [1] Bioconductor                                 
# survival                 3.2-7      2020-09-28 [1] CRAN (R 4.0.4)                               
# switchde                 1.16.0     2020-10-27 [1] Bioconductor                                 
# sys                      3.4        2020-07-23 [1] CRAN (R 4.0.2)                               
# systemfonts              1.0.1      2021-02-09 [1] CRAN (R 4.0.2)                               
# tensor                   1.5        2012-05-05 [1] CRAN (R 4.0.2)                               
# tensorflow               2.9.0      2022-05-21 [1] CRAN (R 4.0.4)                               
# testthat                 3.0.2      2021-02-14 [1] CRAN (R 4.0.2)                               
# textshaping              0.3.3      2021-03-16 [1] CRAN (R 4.0.2)                               
# tfautograph              0.3.2      2021-09-17 [1] CRAN (R 4.0.2)                               
# TFisher                  0.2.0      2018-03-21 [1] CRAN (R 4.0.2)                               
# tfruns                   1.5.0      2021-02-26 [1] CRAN (R 4.0.2)                               
# TH.data                  1.0-10     2019-01-21 [1] CRAN (R 4.0.2)                               
# tibble                   3.1.0      2021-02-25 [1] CRAN (R 4.0.2)                               
# tidygraph                1.2.0      2020-05-12 [1] CRAN (R 4.0.2)                               
# tidyr                    1.1.3      2021-03-03 [1] CRAN (R 4.0.2)                               
# tidyselect               1.1.0      2020-05-11 [1] CRAN (R 4.0.2)                               
# tiff                     0.1-8      2021-03-31 [1] CRAN (R 4.0.2)                               
# tinytex                  0.43       2022-12-13 [1] CRAN (R 4.0.4)                               
# tmvnsim                  1.0-2      2016-12-15 [1] CRAN (R 4.0.2)                               
# trqwe                    0.1        2021-08-11 [1] Github (traversc/trqwe@dcf5767)              
# truncdist                1.0-2      2016-08-30 [1] CRAN (R 4.0.2)                               
# TTR                      0.24.2     2020-09-01 [1] CRAN (R 4.0.2)                               
# tweenr                   1.0.2      2021-03-23 [1] CRAN (R 4.0.4)                               
# tximport                 1.18.0     2020-10-27 [1] Bioconductor                                 
# tzdb                     0.2.0      2021-10-27 [1] CRAN (R 4.0.2)                               
# units                    0.7-2      2021-06-08 [1] CRAN (R 4.0.2)                               
# usethis                  2.0.1      2021-02-10 [1] CRAN (R 4.0.2)                               
# utf8                     1.2.1      2021-03-12 [1] CRAN (R 4.0.2)                               
# uwot                     0.1.10     2020-12-15 [1] CRAN (R 4.0.2)                               
# vcd                      1.4-8      2020-09-21 [1] CRAN (R 4.0.2)                               
# vctrs                    0.3.6      2020-12-17 [1] CRAN (R 4.0.2)                               
# vegan                    2.6-2      2022-04-17 [1] CRAN (R 4.0.4)                               
# velocyto.R               0.6        2021-08-11 [1] Github (velocyto-team/velocyto.R@83e6ed9)    
# VennDiagram              1.6.20     2018-03-28 [1] CRAN (R 4.0.2)                               
# VGAM                     1.1-6      2022-02-14 [1] CRAN (R 4.0.5)                               
# VIM                      6.1.1      2021-07-22 [1] CRAN (R 4.0.2)                               
# viper                    1.24.0     2020-10-27 [1] Bioconductor                                 
# vipor                    0.4.5      2017-03-22 [1] CRAN (R 4.0.2)                               
# viridis                  0.5.1      2018-03-29 [1] CRAN (R 4.0.2)                               
# viridisLite              0.3.0      2018-02-01 [1] CRAN (R 4.0.1)                               
# vroom                    1.5.7      2021-11-30 [1] CRAN (R 4.0.2)                               
# waldo                    0.2.5      2021-03-08 [1] CRAN (R 4.0.2)                               
# warp                     0.2.0      2020-10-21 [1] CRAN (R 4.0.2)                               
# whisker                  0.4        2019-08-28 [1] CRAN (R 4.0.2)                               
# withr                    2.4.1      2021-01-26 [1] CRAN (R 4.0.2)                               
# wk                       0.5.0      2021-07-13 [1] CRAN (R 4.0.2)                               
# xfun                     0.36       2022-12-21 [1] CRAN (R 4.0.4)                               
# XML                      3.99-0.6   2021-03-16 [1] CRAN (R 4.0.4)                               
# xml2                     1.3.2      2020-04-23 [1] CRAN (R 4.0.2)                               
# xopen                    1.0.0      2018-09-17 [1] CRAN (R 4.0.2)                               
# xtable                   1.8-4      2019-04-21 [1] CRAN (R 4.0.2)                               
# xts                      0.12.1     2020-09-09 [1] CRAN (R 4.0.2)                               
# XVector                  0.30.0     2020-10-28 [1] Bioconductor                                 
# yaml                     2.2.1      2020-02-01 [1] CRAN (R 4.0.2)                               
# zeallot                  0.1.0      2018-01-28 [1] CRAN (R 4.0.2)                               
# zip                      2.1.1      2020-08-27 [1] CRAN (R 4.0.2)                               
# zlibbioc                 1.36.0     2020-10-28 [1] Bioconductor                                 
# zoo                      1.8-9      2021-03-09 [1] CRAN (R 4.0.2)                               
```

-------------------------------------------------------------------------------------------------------------------
