---
title: "bulk"
output: html_document
---

## Prepare session

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(echo = TRUE)
path <- '~/Desktop/bulk'
dir.create(path = path, recursive = T)
knitr::opts_knit$set(root.dir = path, collapse = T, comment = '#>')
```

```{r loadlibraries, echo=FALSE}
library(DESeq2)
library(tibble)
library(gplots)
library(openxlsx)
library(dplyr)
library(limma)

# Define custom ggplot theme
theme_custom <- theme(axis.text.x = element_text(size = 12.8, color = 'black'),
                      axis.text.y = element_text(size = 12.8, color = 'black'), 
                      axis.title.x = element_text(size = 16, margin = margin(6,0,0,0)), 
                      axis.title.y = element_text(size = 16, margin = margin(0,8,0,0)),
                      plot.title = element_text(size = 16, face = 'plain', hjust = 0.5, margin = margin(5,0,10,0)),
                      plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(0,0,10,0)), 
                      axis.ticks.x = element_line(size = 0.4, colour = 'black'), 
                      axis.ticks.y = element_line(size = 0.4, colour = 'black'),
                      axis.line = element_blank(), 
                      panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank(),
                      panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(),
                      panel.border = element_rect(colour = 'black', size = 0.8, fill = NA),
                      panel.background = element_rect(colour = NA, fill = NA), 
                      strip.text.x = element_text(size = 16, face = 'plain', margin = margin(0,0,5,0) ), 
                      strip.text.y = element_text(size = 16, face = 'plain', margin = margin(0,0,0,5) ), 
                      strip.background = element_blank(), 
                      legend.key = element_blank(), legend.key.size = unit(0.5,'cm'),
                      legend.text = element_text(size = 12.8), 
                      legend.title = element_text(size = 12.8),
                      plot.background = element_rect(colour = NA, fill = NA), aspect.ratio = 1)
```

-------------------------------------------------------------------------------------------------------------------

## DEG function

```{r DEGfunction, echo=FALSE}
Deseq.Func <- function(ReadCountTable, DesignTable, Filename, filepath, Treat, Ctr, 
                       BaseMean= 50, logFC = 1, Padj = 0.05){
  
  #gene pre-filtering
  ReadCountTable <- ReadCountTable[rowSums(ReadCountTable) > 10,]
  
  #perform DEGA
  dds <- DESeqDataSetFromMatrix(countData = ReadCountTable,
                                colData = DesignTable,
                                design = ~ Run + Treatment)
  dds <- DESeq(dds)
  resultsNames(dds)
  
  #get raw DEG list
  res <- as.data.frame(results(dds, contrast = c("Treatment", Treat, Ctr)))
  res$geneName <- rownames(res)
  
  # export norm/rlog, rawDEG data
  write.table(x = rownames_to_column(as.data.frame(counts(dds, normalized = T)),'Gene'),
            file = paste0(filepath,'Norm_', Filename, '.csv'), sep = '\t', row.names = F, quote = F)

  # time consuming
  write.table(x = rownames_to_column(as.data.frame(assay(rlog(dds, blind = F))),'Gene'),
            file = paste0(filepath,'Rlog_', Filename,'.csv'), sep = '\t', row.names = F, quote = F)
  write.xlsx(x = na.omit(res), file = paste0(filepath, Filename, '_', 'Raw_DEG_', Treat, '_VS_', Ctr, '.xlsx'))
  write.xlsx(x = na.omit(res[which(res$baseMean >= BaseMean & abs(res$log2FoldChange) >= logFC &
                                     res$padj < Padj),]), file = paste0(filepath, Filename, '_', 'Filter_DEG_',
                                                                        Treat, '_VS_', Ctr,'.xlsx'))
}
```

-------------------------------------------------------------------------------------------------------------------

## DEG test

```{r}
# Download pre-processed data from GEO SuperSeries and place at '~/Desktop/bulk/'
download.file(url='https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE200358&format=file&file=GSE200358%5FCombined%5FRun2%2B3%2B17%2B19Raw%2Etxt%2Egz', destfile=paste0(path, '/GSE200358_Combined_Run2+3+17+19Raw.txt.gz'))
download.file(url='https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE200358&format=file&file=GSE200358%5FDesign%5FCombined%5FRun2%2B3%2B17%2B19%2Etxt%2Egz', destfile=paste0(path, '/GSE200358_Design_Combined_Run2+3+17+19.txt.gz'))

# Prepare data
Expr = read.csv(gzfile(paste0(path, '/GSE200358_Combined_Run2+3+17+19Raw.txt.gz')), sep = '\t', header = T, row.names = 1, stringsAsFactors = F, check.names = F)
Design = read.csv(gzfile(paste0(path, '/GSE200358_Design_Combined_Run2+3+17+19.txt.gz')), sep = '\t', header = T, nrows = ncol(Expr), row.names = 2, stringsAsFactors = F, blank.lines.skip = T)[,-1] %>% rownames_to_column(., 'Sample')
#make sure identical(colnames(ReadCountTable), Design$sample) = True
Run2_Run3_D7_Design <- Design %>% filter(Day == 'Day7' & Run %in% c('Run2', 'Run3'))
Run2_Run3_D7_Expr <- Expr[, Run2_Run3_D7_Design$Sample]
Run17_Run19_D7_Design <- Design %>% filter(Day == 'Day7' & Run %in% c('Run17', 'Run19'))
Run17_Run19_D7_Expr <- Expr[, Run17_Run19_D7_Design$Sample]

# Find DEGs
Deseq.Func(ReadCountTable = Run2_Run3_D7_Expr, DesignTable = Run2_Run3_D7_Design, Filename = 'Run2_Run3_D7', filepath = paste0(path,'/'), Treat = 'TFL', Ctr = 'CMC')
Deseq.Func(ReadCountTable = Run17_Run19_D7_Expr, DesignTable = Run17_Run19_D7_Design, Filename = 'Run17_Run19_D7', filepath = paste0(path,'/'), Treat = 'TFL', Ctr = 'CMC')
```

-------------------------------------------------------------------------------------------------------------------

## Volcano plot

```{r}
library(ggplot2)

# Function to draw volcano plot
volcano <-  function(data, gene_highlight, title) {
  data$DE <- 'ns'
  data$DE <- ifelse(data$padj < 0.05 & data$log2FoldChange > 1.5, 'up', data$DE)
  data$DE <- ifelse(data$padj < 0.05 & data$log2FoldChange < -1.5, 'dn', data$DE)
  data$DE <- factor(data$DE, levels = sort(unique(data$DE))[c(3,1,2)])
  data$DEf <- 'no'
  data$DEf <- ifelse(data$gene %in% gene_highlight & data$log2FoldChange > 0, 'up', data$DEf)
  data$DEf <- ifelse(data$gene %in% gene_highlight & data$log2FoldChange < 0, 'dn', data$DEf)
  data$DEf <- factor(data$DEf, levels = c('up','dn','ns','no'))
  data$DEs <- 'no'
  #data$DEs <- ifelse(-log10(data$padj) > 10 | data$LFC > 10, 'up', data$DEs)
  #data$DEs <- ifelse(-log10(data$padj) > 10 | data$LFC < -10, 'dn', data$DEs)
  data$DEs <- ifelse(data$padj < 1e-30 | data$log2FoldChange > 5, 'up', data$DEs)
  data$DEs <- ifelse(data$padj < 1e-30 | data$log2FoldChange < -5, 'dn', data$DEs)
  data$DEs <- factor(data$DEs, levels = c('up','dn','no'))
  
  p <- ggplot(data, aes(x = ifelse(log2FoldChange>5,5,ifelse(log2FoldChange<(-5),-5,log2FoldChange)), y = ifelse(padj<1e-30,1e-30, padj) )) + #ifelse(-log10(padj)>10,10, -log10(padj))) ) + 
    #geom_point(aes(), alpha = 1, size = 1, shape = 21) +
    ggrastr::geom_point_rast(aes(color = DE, fill = DEf, size = DEf, shape = DEs), 
                             alpha = 1, stroke = 0.2, raster.dpi = 600) + 
    annotate('text', x = 4, y = 0.5, label = paste0(sum(data$padj < 0.05 & data$log2FoldChange > 1.5), ' up'), size = 5) + 
    annotate('text', x = -4, y = 0.5, label = paste0(sum(data$padj < 0.05 & data$log2FoldChange < -1.5), ' dn'), size = 5) + 
    geom_vline(xintercept = c(-1.5,1.5), colour = "black", linetype = "dashed", size = 0.3) + 
    geom_hline(yintercept = c(0.05), colour = "firebrick3", linetype = "dashed", size = 0.3) + 
    scale_x_continuous(expression(""*log[2]*"(fold change)"), limits = c(-5,5), breaks = seq(-5,5,1), expand = c(0.02,0)) + 
    #scale_y_continuous(expression("-"*log[10]*"(p-value)"), limits = c(0,10), breaks = seq(0,10,2), expand = c(0.02,0)) + 
    #scale_y_log10(expression("Adj. p-value (in "*log[10]*" scale)"), labels = scales::trans_format("log10", scales::math_format(10^.x)) ) + 
    scale_y_continuous(expression("Adj. p-value (in "*log[10]*" scale)"), trans = ggforce::trans_reverser('log10'), limits = c(1,1e-30), breaks = c(1,1e-10,1e-20,1e-30), labels = scales::trans_format("log10", scales::math_format(10^.x)), expand = c(0.02,0)) + #annotation_logticks(base=10, sides = 'l') + 
    #scale_fill_manual("Regulation", values = c('grey60', 'white'), #c("black", "grey60", "white"), 
    #                  guide = guide_legend(override.aes = list(size = 5, alpha = 1))) + 
    scale_size_manual("Regulation", values = c(up=2,dn=2,ns=2,no=1), guide = F) + 
    scale_shape_manual("Regulation", values = c(up=24,dn=24,ns=24,no=21), guide = F) + 
    scale_fill_manual("Regulation", values = c(up='#B2182B', dn='#2166AC', ns='grey70', no=NA), guide = F) + 
    scale_color_manual("Regulation", values = c(up='#B2182B',dn='#2166AC',ns='grey70'), 
                       guide = guide_legend(override.aes = list(size = 5, shape = 16, alpha = 1))) + 
    ggtitle(title) + 
    theme_custom
  p <- p + 
    ggrepel::geom_text_repel(data = subset(data, geneName %in% gene_highlight & log2FoldChange > 0), segment.size=0.2, seed = 1, aes(label = geneName), color = "grey30", size = 3, min.segment.length = 0, force = 5, direction = 'y', nudge_x = 5 - subset(data, geneName %in% gene_highlight & log2FoldChange > 0)$log2FoldChange, hjust=0, max.overlaps=20, box.padding = unit(0.2, "lines"), point.padding = unit(0.4, "lines"), fontface = "italic") + 
    ggrepel::geom_text_repel(data = subset(data, geneName %in% gene_highlight & log2FoldChange < 0), segment.size=0.2, seed = 1, aes(label = geneName), color = "grey30", size = 3, min.segment.length = 0, force = 5, direction = 'y', nudge_x = -5 - subset(data, geneName %in% gene_highlight & log2FoldChange < 0)$log2FoldChange, hjust=1, max.overlaps=20, box.padding = unit(0.2, "lines"), point.padding = unit(0.4, "lines"), fontface = "italic")
  return(p)
}

# Create volcano plots
vp1 <- volcano(data=read.xlsx(paste0(path, '/Run2_Run3_D7_Raw_DEG_TFL_VS_CMC.xlsx')) %>% filter(baseMean > 50), 
               gene_highlight = c('Esm1','Klra4','Klrc1','Klre1','Plekha6','Itga1','Gm4208','S1pr5','Klra9','Klrb1c',' Pdcd1','Cenpk','Shmt1','Ccr7','Capn3','Tox','Izumo1r','Bcat1','Ly6i','Lpl','Saa3','Gbp2b'), title = 'Total OT-1 (day 7)'
)
vp2 <- volcano(data=read.xlsx(paste0(path, '/Run17_Run19_D7_Raw_DEG_TFL_VS_CMC.xlsx')) %>% filter(baseMean > 50), 
               gene_highlight = c('Gm4208','Pls1','Klrb1c','Cx3cr1','Mal','Cd163l1','Plekha6','Epha3',' Tnfsf8','Sell','St8sia1','Capg','Capn3','Cd200','Eng','Phlda3','Serpine2','Tox2','Bcat1'), title = 'CD127+KLRG1- OT-1 (day 7)'
)

# Save volcano plots
ggsave(paste0(path, '/Fig3A.pdf'), vp1, height = 4.5, width = 6)
ggsave(paste0(path, '/Fig3C.pdf'), vp2, height = 4.5, width = 6)
```

-------------------------------------------------------------------------------------------------------------------

## Gene expression

```{r}
library(pheatmap)
library(RColorBrewer)

# Prepare data
Norm_df = read.csv(paste0(path, '/Rlog_Run2_Run3_D7.csv'), sep = '\t', header = T, row.names = 1)
Norm_zscore = t(scale(t(Norm_df[, c(6:10, 1:5)])))
new_annotation = data.frame(row.names = colnames(Norm_zscore),
                            condition = as.factor(c(rep('CMC', 5), rep('TFL',5))), stringsAsFactors = F)
new_annotation_color = list(condition = c('CMC' = '#BF4342', 'TFL' = '#033F63'))

# Plot expression over heatmap
heat <- pheatmap(Norm_zscore[match(toupper(Gene_highlight), toupper(rownames(Norm_zscore))),], cluster_rows = F, cluster_cols = F, show_colnames = F, annotation = new_annotation, cutree_cols = 1, gaps_col = c(5), annotation_colors = new_annotation_color, cellheight = 10, cellwidth = 10, fontsize = 10, border_color = 'white', legend_breaks = seq(-1.5,1.5,0.5), breaks = seq(-1.5,1.5,length.out=42), main = 'Total OT-1 (day 7)', color = colorRampPalette(c('#133d67','#2166AC','#90b2d5','#d2e0ee','grey90','#efd0d4','#d88b95','#B2182B','#590c15'))(41))

# Save heatmap
ggsave(paste0(path, '/Fig3B.pdf'), heat[[4]], height = 4, width = 4)
```

-------------------------------------------------------------------------------------------------------------------

## PCA plot

```{r}
library(ggfortify)

# Prepare data
Run2_Run3_D7_D28_Design = Design %>% filter(Run %in% c('Run2', 'Run3'))
Run2_Run3_D7_D28_Expr = Expr[, Run2_Run3_D7_D28_Design$Sample]
Run2_Run3_D7_D28_Design$group = paste0(Run2_Run3_D7_D28_Design$Day, '_', Run2_Run3_D7_D28_Design$Treatment)
Run2_Run3_D7_D28_Design$cluster = plyr::mapvalues(Run2_Run3_D7_D28_Design$group, from = unique(Run2_Run3_D7_D28_Design$group), to = c(1,2,3,4))

# run deseq2
dds <- DESeqDataSetFromMatrix(countData = Run2_Run3_D7_D28_Expr, colData = Run2_Run3_D7_D28_Design, design = ~ cluster)
rlogcounts = as.data.frame(assay(rlog(dds, blind = FALSE)))

# remove batch effects
rlogcounts <- limma::removeBatchEffect(rlogcounts, as.factor(dds$Run))
rlogcounts <- rlogcounts[apply(rlogcounts, 1, sd) > quantile(apply(rlogcounts, 1, sd), probs=seq(0,1,0.001)[990]), ]

# run PCA
pcDat <- prcomp(t(rlogcounts))

# plot PCA
pca <- autoplot(cluster::fanny(pcDat$x, 4), frame = TRUE, frame.type = 'norm', data = Run2_Run3_D7_D28_Design, label_size = 4) + 
  geom_point(aes(color = cluster), size = 4) + theme_custom + scale_y_reverse() + scale_x_reverse() + 
  scale_color_manual(values=c('1'='#50b2c1', '2'='grey50', '3'='#1266b1', '4'='black'), labels=c(sub('_',' ',unique(Run2_Run3_D7_D28_Design$group))), guide = guide_legend(reverse=T) ) + 
  scale_fill_manual(values=c('1'='#50b2c1', '2'='grey50', '3'='#1485ea', '4'='black'), labels=c(sub('_',' ',unique(Run2_Run3_D7_D28_Design$group))), guide = guide_legend(reverse=T) )

# Save PCA plot
ggsave(paste0(path, '/Fig3D.pdf'), pca, height = 4, width = 6)
```

-------------------------------------------------------------------------------------------------------------------
## Session info

```{r sessioninfo, collapse=T, echo=F, warning=F, message=F, include=F}
installed.packages() %>% rownames() %>% devtools::package_info()
#─ Session info ───────────────────────────────────────────────────────────────
# setting  value                       
# version  R version 3.6.3 (2020-02-29)
# os       Ubuntu 16.04.7 LTS          
# system   x86_64, linux-gnu           
# ui       X11                         
# language (EN)                        
# collate  C.UTF-8                     
# ctype    C.UTF-8                     
# tz       Europe/Berlin               
#
#─ Packages ───────────────────────────────────────────────────────────────────
# package              * version    date       lib source                               
# abind                  1.4-5      2016-07-21 [1] CRAN (R 3.6.1)                       
# acepack                1.4.1      2016-10-29 [1] CRAN (R 3.6.1)                       
# affxparser             1.56.0     2019-05-02 [1] Bioconductor                         
# affy                   1.62.0     2019-05-02 [1] Bioconductor                         
# affyio                 1.54.0     2019-05-02 [1] Bioconductor                         
# anndata                0.7.5.5    2022-09-23 [1] CRAN (R 3.6.3)                       
# annotate               1.62.0     2019-05-02 [1] Bioconductor                         
# AnnotationDbi          1.46.1     2019-08-20 [1] Bioconductor                         
# AnnotationForge        1.26.0     2019-05-02 [1] Bioconductor                         
# apcluster              1.4.8      2019-08-21 [1] CRAN (R 3.6.1)                       
# ape                    5.3        2019-03-17 [1] CRAN (R 3.6.1)                       
# askpass                1.1        2019-01-13 [1] CRAN (R 3.6.1)                       
# assertthat             0.2.1      2019-03-21 [1] CRAN (R 3.6.1)                       
# backports              1.1.4      2019-04-10 [1] CRAN (R 3.6.1)                       
# base64enc              0.1-3      2015-07-28 [1] CRAN (R 3.6.1)                       
# BBmisc                 1.11       2017-03-10 [1] CRAN (R 3.6.1)                       
# bbmle                  1.0.20     2017-10-30 [1] CRAN (R 3.6.1)                       
# BDgraph                2.61       2019-09-05 [1] CRAN (R 3.6.1)                       
# beachmat               2.0.0      2019-05-02 [1] Bioconductor                         
# beeswarm               0.2.3      2016-04-25 [1] CRAN (R 3.6.1)                       
# BH                     1.69.0-1   2019-01-07 [1] CRAN (R 3.6.1)                       
# bibtex                 0.4.2      2017-06-30 [1] CRAN (R 3.6.1)                       
# Biobase                2.44.0     2019-05-02 [1] Bioconductor                         
# BiocGenerics           0.30.0     2019-05-02 [1] Bioconductor                         
# BiocManager            1.30.4     2018-11-13 [1] CRAN (R 3.6.1)                       
# BiocNeighbors          1.2.0      2019-05-02 [1] Bioconductor                         
# BiocParallel           1.18.1     2019-08-06 [1] Bioconductor                         
# BiocSingular           1.0.0      2019-05-02 [1] Bioconductor                         
# BiocVersion            3.9.0      2018-10-30 [1] Bioconductor                         
# biocViews              1.52.2     2019-05-29 [1] Bioconductor                         
# biomaRt                2.40.5     2019-10-01 [1] Bioconductor                         
# Biostrings             2.52.0     2019-05-02 [1] Bioconductor                         
# bit                    1.1-14     2018-05-29 [1] CRAN (R 3.6.1)                       
# bit64                  0.9-7      2017-05-08 [1] CRAN (R 3.6.1)                       
# bitops                 1.0-6      2013-08-17 [1] CRAN (R 3.6.1)                       
# blob                   1.2.0      2019-07-09 [1] CRAN (R 3.6.1)                       
# boot                   1.3-25     2020-04-26 [2] CRAN (R 3.6.3)                       
# brew                   1.0-6      2011-04-13 [1] CRAN (R 3.6.1)                       
# brio                   1.1.1      2021-01-20 [1] CRAN (R 3.6.3)                       
# broom                  0.7.3      2020-12-16 [1] CRAN (R 3.6.3)                       
# calibrate              1.7.5      2019-10-01 [1] CRAN (R 3.6.1)                       
# callr                  3.3.1      2019-07-18 [1] CRAN (R 3.6.1)                       
# car                    3.0-10     2020-09-29 [1] CRAN (R 3.6.3)                       
# carData                3.0-4      2020-05-22 [1] CRAN (R 3.6.3)                       
# caret                  6.0-90     2021-10-09 [1] CRAN (R 3.6.3)                       
# Category               2.50.0     2019-05-02 [1] Bioconductor                         
# caTools                1.17.1.2   2019-03-06 [1] CRAN (R 3.6.1)                       
# cellranger             1.1.0      2016-07-27 [1] CRAN (R 3.6.1)                       
# checkmate              1.9.4      2019-07-04 [1] CRAN (R 3.6.1)                       
# circlize               0.4.10     2020-06-15 [1] CRAN (R 3.6.3)                       
# class                  7.3-17     2020-04-26 [2] CRAN (R 3.6.3)                       
# cli                    1.1.0      2019-03-19 [1] CRAN (R 3.6.1)                       
# clipr                  0.7.0      2019-07-23 [1] CRAN (R 3.6.1)                       
# clisymbols             1.2.0      2017-05-21 [1] CRAN (R 3.6.1)                       
# cluster                2.1.0      2019-06-19 [2] CRAN (R 3.6.3)                       
# clusterProfiler        3.12.0     2019-05-02 [1] Bioconductor                         
# codetools              0.2-16     2018-12-24 [2] CRAN (R 3.6.3)                       
# coin                   1.3-1      2019-08-28 [1] CRAN (R 3.6.3)                       
# colorspace             1.4-1      2019-03-18 [1] CRAN (R 3.6.1)                       
# colourpicker           1.0        2017-09-27 [1] CRAN (R 3.6.1)                       
# combinat               0.0-8      2012-10-29 [1] CRAN (R 3.6.1)                       
# commonmark             1.7        2018-12-01 [1] CRAN (R 3.6.1)                       
# conquer                1.0.2      2020-08-27 [1] CRAN (R 3.6.3)                       
# coop                   0.6-2      2019-04-22 [1] CRAN (R 3.6.1)                       
# corpcor                1.6.9      2017-04-01 [1] CRAN (R 3.6.1)                       
# corrplot               0.84       2017-10-16 [1] CRAN (R 3.6.1)                       
# covr                   3.3.1      2019-08-23 [1] CRAN (R 3.6.1)                       
# cowplot                1.0.0      2019-07-11 [1] CRAN (R 3.6.1)                       
# cpp11                  0.2.5      2021-01-12 [1] CRAN (R 3.6.3)                       
# crayon                 1.3.4      2017-09-16 [1] CRAN (R 3.6.1)                       
# crosstalk              1.0.0      2016-12-21 [1] CRAN (R 3.6.1)                       
# curl                   4.0        2019-07-22 [1] CRAN (R 3.6.1)                       
# d3heatmap              0.6.1.2    2018-02-01 [1] CRAN (R 3.6.1)                       
# d3Network              0.5.2.1    2015-01-31 [1] CRAN (R 3.6.1)                       
# data.table             1.12.2     2019-04-07 [1] CRAN (R 3.6.1)                       
# DBI                    1.0.0      2018-05-02 [1] CRAN (R 3.6.1)                       
# dbplyr                 1.4.2      2019-06-17 [1] CRAN (R 3.6.1)                       
# DDRTree                0.1.5      2017-04-30 [1] CRAN (R 3.6.1)                       
# debrowser              1.12.3     2019-08-09 [1] Bioconductor                         
# DelayedArray           0.10.0     2019-05-02 [1] Bioconductor                         
# DelayedMatrixStats     1.6.1      2019-09-08 [1] Bioconductor                         
# deldir                 0.2-9      2021-01-16 [1] CRAN (R 3.6.3)                       
# dendextend             1.12.0     2019-05-11 [1] CRAN (R 3.6.1)                       
# densityClust           0.3        2017-10-24 [1] CRAN (R 3.6.1)                       
# DEoptimR               1.0-8      2016-11-19 [1] CRAN (R 3.6.1)                       
# desc                   1.2.0      2018-05-01 [1] CRAN (R 3.6.1)                       
# DESeq2               * 1.24.0     2019-05-02 [1] Bioconductor                         
# devEMF                 3.6-3      2019-06-24 [1] CRAN (R 3.6.1)                       
# devtools               2.2.0      2019-09-07 [1] CRAN (R 3.6.1)                       
# diffobj                0.3.3      2021-01-07 [1] CRAN (R 3.6.3)                       
# diffusionMap           1.2.0      2019-09-10 [1] CRAN (R 3.6.3)                       
# digest                 0.6.20     2019-07-04 [1] CRAN (R 3.6.1)                       
# diptest                0.75-7     2016-12-05 [1] CRAN (R 3.6.1)                       
# distr                  2.8.0      2019-03-11 [1] CRAN (R 3.6.1)                       
# distutils              1.0        2021-01-21 [1] Github (Albluca/distutils@cd82bca)   
# DO.db                  2.9        2019-10-25 [1] Bioconductor                         
# docopt                 0.6.1      2018-10-11 [1] CRAN (R 3.6.1)                       
# doParallel             1.0.15     2019-08-02 [1] CRAN (R 3.6.1)                       
# doRNG                  1.7.1      2018-06-22 [1] CRAN (R 3.6.1)                       
# DOSE                   3.10.2     2019-06-24 [1] Bioconductor                         
# doSNOW                 1.0.18     2019-07-27 [1] CRAN (R 3.6.1)                       
# dplyr                * 1.0.3      2021-01-15 [1] CRAN (R 3.6.3)                       
# dqrng                  0.2.1      2019-05-17 [1] CRAN (R 3.6.1)                       
# dropestr               0.7.9      2019-09-15 [1] Github (hms-dbmi/dropEst@5abbc9c)    
# DT                     0.8        2019-08-07 [1] CRAN (R 3.6.1)                       
# dtw                    1.21-3     2019-09-01 [1] CRAN (R 3.6.1)                       
# dynamicTreeCut         1.63-1     2016-03-11 [1] CRAN (R 3.6.3)                       
# e1071                  1.7-2      2019-06-05 [1] CRAN (R 3.6.1)                       
# edgeR                  3.26.8     2019-09-01 [1] Bioconductor                         
# editData               0.1.2      2017-10-07 [1] CRAN (R 3.6.1)                       
# ellipsis               0.2.0.1    2019-07-02 [1] CRAN (R 3.6.1)                       
# ElPiGraph.R            1.0.0      2021-01-21 [1] Github (Albluca/ElPiGraph.R@761a48a) 
# enrichplot             1.4.0      2019-05-02 [1] Bioconductor                         
# europepmc              0.3        2018-04-20 [1] CRAN (R 3.6.1)                       
# evaluate               0.14       2019-05-28 [1] CRAN (R 3.6.1)                       
# extrafont              0.17       2014-12-08 [1] CRAN (R 3.6.3)                       
# extrafontdb            1.0        2012-06-11 [1] CRAN (R 3.6.3)                       
# fansi                  0.4.0      2018-10-05 [1] CRAN (R 3.6.1)                       
# farver                 1.1.0      2018-11-20 [1] CRAN (R 3.6.1)                       
# fastcluster            1.1.25     2018-06-07 [1] CRAN (R 3.6.1)                       
# fastICA                1.2-2      2019-07-08 [1] CRAN (R 3.6.1)                       
# fastmap                1.1.0      2021-01-25 [1] CRAN (R 3.6.3)                       
# fastmatch              1.1-0      2017-01-28 [1] CRAN (R 3.6.1)                       
# fdrtool                1.2.15     2015-07-08 [1] CRAN (R 3.6.1)                       
# ff                     2.2-14     2018-05-15 [1] CRAN (R 3.6.1)                       
# fgsea                  1.10.1     2019-08-21 [1] Bioconductor                         
# fitdistrplus           1.0-14     2019-01-23 [1] CRAN (R 3.6.1)                       
# flexmix                2.3-15     2019-02-18 [1] CRAN (R 3.6.1)                       
# flextable              0.5.5      2019-06-25 [1] CRAN (R 3.6.1)                       
# FNN                    1.1.3      2019-02-15 [1] CRAN (R 3.6.1)                       
# forcats                0.4.0      2019-02-17 [1] CRAN (R 3.6.1)                       
# foreach                1.4.7      2019-07-27 [1] CRAN (R 3.6.1)                       
# foreign                0.8-76     2020-03-03 [2] CRAN (R 3.6.3)                       
# formatR                1.7        2019-06-11 [1] CRAN (R 3.6.1)                       
# Formula                1.2-3      2018-05-03 [1] CRAN (R 3.6.1)                       
# fpc                    2.2-3      2019-06-28 [1] CRAN (R 3.6.1)                       
# fs                     1.3.1      2019-05-06 [1] CRAN (R 3.6.1)                       
# futile.logger          1.4.3      2016-07-10 [1] CRAN (R 3.6.1)                       
# futile.options         1.0.1      2018-04-20 [1] CRAN (R 3.6.1)                       
# future                 1.14.0     2019-07-02 [1] CRAN (R 3.6.1)                       
# future.apply           1.3.0      2019-06-18 [1] CRAN (R 3.6.1)                       
# gage                   2.34.0     2019-05-02 [1] Bioconductor                         
# gbRd                   0.4-11     2012-10-01 [1] CRAN (R 3.6.1)                       
# gclus                  1.3.2      2019-01-07 [1] CRAN (R 3.6.1)                       
# gdata                  2.18.0     2017-06-06 [1] CRAN (R 3.6.1)                       
# gdtools                0.2.0      2019-09-03 [1] CRAN (R 3.6.1)                       
# genefilter             1.66.0     2019-05-02 [1] Bioconductor                         
# geneplotter            1.62.0     2019-05-02 [1] Bioconductor                         
# generics               0.1.2      2022-01-31 [1] CRAN (R 3.6.3)                       
# GenomeInfoDb           1.20.0     2019-05-02 [1] Bioconductor                         
# GenomeInfoDbData       1.2.1      2019-09-10 [1] Bioconductor                         
# GenomicRanges          1.36.1     2019-09-06 [1] Bioconductor                         
# GenSA                  1.1.7      2018-01-17 [1] CRAN (R 3.6.3)                       
# GEOquery               2.52.0     2019-05-02 [1] Bioconductor                         
# getopt                 1.20.3     2019-03-22 [1] CRAN (R 3.6.1)                       
# ggbeeswarm             0.6.0      2017-08-07 [1] CRAN (R 3.6.1)                       
# ggforce                0.3.1      2019-08-20 [1] CRAN (R 3.6.1)                       
# ggfortify            * 0.4.7      2019-05-26 [1] CRAN (R 3.6.1)                       
# ggm                    2.3        2015-01-21 [1] CRAN (R 3.6.1)                       
# ggplot2              * 3.3.2      2020-06-19 [1] CRAN (R 3.6.3)                       
# ggplotify              0.0.4      2019-08-06 [1] CRAN (R 3.6.1)                       
# ggpubr                 0.2.3      2019-09-03 [1] CRAN (R 3.6.1)                       
# ggradar                0.2        2019-10-09 [1] Github (ricardo-bion/ggradar@6d675be)
# ggraph                 2.0.0      2019-09-02 [1] CRAN (R 3.6.1)                       
# ggrepel                0.8.1      2019-05-07 [1] CRAN (R 3.6.1)                       
# ggridges               0.5.1      2018-09-27 [1] CRAN (R 3.6.1)                       
# ggsci                  2.9        2018-05-14 [1] CRAN (R 3.6.1)                       
# ggsignif               0.6.0      2019-08-08 [1] CRAN (R 3.6.1)                       
# gh                     1.0.1      2017-07-16 [1] CRAN (R 3.6.1)                       
# gistr                  0.5.0      2020-01-09 [2] CRAN (R 3.6.3)                       
# git2r                  0.26.1     2019-06-29 [1] CRAN (R 3.6.1)                       
# glasso                 1.11       2019-10-01 [1] CRAN (R 3.6.1)                       
# glmnet                 4.0-2      2020-06-16 [2] CRAN (R 3.6.3)                       
# GlobalOptions          0.1.2      2020-06-10 [1] CRAN (R 3.6.3)                       
# globals                0.12.4     2018-10-11 [1] CRAN (R 3.6.1)                       
# glue                   1.4.2      2020-08-27 [1] CRAN (R 3.6.3)                       
# GO.db                  3.8.2      2019-10-25 [1] Bioconductor                         
# goftest                1.2-2      2019-12-02 [1] CRAN (R 3.6.3)                       
# GOSemSim               2.10.0     2019-05-02 [1] Bioconductor                         
# GOstats                2.50.0     2019-05-02 [1] Bioconductor                         
# gower                  1.0.0      2022-02-03 [1] CRAN (R 3.6.3)                       
# gplots               * 3.0.1.1    2019-01-27 [1] CRAN (R 3.6.1)                       
# gProfileR              0.6.8      2019-09-07 [1] CRAN (R 3.6.1)                       
# graph                  1.62.0     2019-05-02 [1] Bioconductor                         
# graphlayouts           0.5.0      2019-08-20 [1] CRAN (R 3.6.1)                       
# gridBase               0.4-7      2014-02-24 [1] CRAN (R 3.6.3)                       
# gridExtra              2.3        2017-09-09 [1] CRAN (R 3.6.1)                       
# gridGraphics           0.4-1      2019-05-20 [1] CRAN (R 3.6.1)                       
# GSEABase               1.46.0     2019-05-02 [1] Bioconductor                         
# gtable                 0.3.0      2019-03-25 [1] CRAN (R 3.6.1)                       
# gtools                 3.8.1      2018-06-26 [1] CRAN (R 3.6.1)                       
# Harman                 1.12.0     2019-05-02 [1] Bioconductor                         
# hash                   2.2.6.1    2019-03-04 [1] CRAN (R 3.6.1)                       
# haven                  2.1.1      2019-07-04 [1] CRAN (R 3.6.1)                       
# HDF5Array              1.12.2     2019-08-06 [1] Bioconductor                         
# hdf5r                  1.3.3      2021-01-19 [1] Github (hhoeflin/hdf5r@5c9074f)      
# heatmaply              0.16.0     2019-05-11 [1] CRAN (R 3.6.1)                       
# here                   1.0.1      2020-12-13 [1] CRAN (R 3.6.3)                       
# hexbin                 1.27.3     2019-05-14 [1] CRAN (R 3.6.1)                       
# highr                  0.8        2019-03-20 [1] CRAN (R 3.6.1)                       
# Hmisc                  4.2-0      2019-01-26 [1] CRAN (R 3.6.1)                       
# hms                    0.5.1      2019-08-23 [1] CRAN (R 3.6.1)                       
# hrbrthemes             0.8.0      2020-03-06 [1] CRAN (R 3.6.3)                       
# HSMMSingleCell         1.4.0      2019-05-07 [1] Bioconductor                         
# htmlTable              1.13.1     2019-01-07 [1] CRAN (R 3.6.1)                       
# htmltools              0.3.6      2017-04-28 [1] CRAN (R 3.6.1)                       
# htmlwidgets            1.3        2018-09-30 [1] CRAN (R 3.6.1)                       
# httpuv                 1.5.2      2019-09-11 [1] CRAN (R 3.6.1)                       
# httr                   1.4.1      2019-08-05 [1] CRAN (R 3.6.1)                       
# huge                   1.3.4      2019-10-28 [1] CRAN (R 3.6.1)                       
# ica                    1.0-2      2018-05-24 [1] CRAN (R 3.6.1)                       
# igraph                 1.2.4.1    2019-04-22 [1] CRAN (R 3.6.1)                       
# infotheo               1.2.0      2014-07-26 [1] CRAN (R 3.6.3)                       
# ini                    0.3.1      2018-05-20 [1] CRAN (R 3.6.1)                       
# insight                0.5.0      2019-09-07 [1] CRAN (R 3.6.1)                       
# ipred                  0.9-12     2021-09-15 [1] CRAN (R 3.6.3)                       
# IRanges                2.18.2     2019-08-24 [1] Bioconductor                         
# IRdisplay              0.7.0      2020-05-04 [2] local                                
# IRkernel               1.1.1      2020-07-20 [2] CRAN (R 3.6.3)                       
# irlba                  2.3.3      2019-02-05 [1] CRAN (R 3.6.1)                       
# isoband                0.2.2      2020-06-20 [1] CRAN (R 3.6.1)                       
# iterators              1.0.12     2019-07-26 [1] CRAN (R 3.6.1)                       
# jpeg                   0.1-8.1    2019-10-24 [1] CRAN (R 3.6.1)                       
# jsonlite               1.6        2018-12-07 [1] CRAN (R 3.6.1)                       
# KEGGgraph              1.44.0     2019-05-02 [1] Bioconductor                         
# KEGGREST               1.24.1     2019-10-08 [1] Bioconductor                         
# kernlab                0.9-27     2018-08-10 [1] CRAN (R 3.6.1)                       
# KernSmooth             2.23-17    2020-04-26 [2] CRAN (R 3.6.3)                       
# knitr                  1.24       2019-08-08 [1] CRAN (R 3.6.1)                       
# ks                     1.11.5     2019-05-20 [1] CRAN (R 3.6.1)                       
# labeling               0.3        2014-08-23 [1] CRAN (R 3.6.1)                       
# lambda.r               1.2.3      2018-05-17 [1] CRAN (R 3.6.1)                       
# lars                   1.2        2013-04-24 [1] CRAN (R 3.6.1)                       
# later                  0.8.0      2019-02-11 [1] CRAN (R 3.6.1)                       
# lattice                0.20-41    2020-04-02 [2] CRAN (R 3.6.3)                       
# latticeExtra           0.6-28     2016-02-09 [1] CRAN (R 3.6.1)                       
# lava                   1.6.10     2021-09-02 [1] CRAN (R 3.6.3)                       
# lavaan                 0.6-5      2019-08-28 [1] CRAN (R 3.6.1)                       
# lazyeval               0.2.2      2019-03-15 [1] CRAN (R 3.6.1)                       
# leiden                 0.3.1      2019-07-23 [1] CRAN (R 3.6.1)                       
# libcoin                1.0-6      2020-08-14 [1] CRAN (R 3.6.3)                       
# lifecycle              0.2.0      2020-03-06 [1] CRAN (R 3.6.3)                       
# limma                * 3.40.6     2019-07-26 [1] Bioconductor                         
# listenv                0.7.0      2018-01-21 [1] CRAN (R 3.6.1)                       
# lme4                   1.1-26     2020-12-01 [1] CRAN (R 3.6.3)                       
# lmPerm                 2.1.0      2016-08-02 [1] CRAN (R 3.6.3)                       
# lmtest                 0.9-37     2019-04-30 [1] CRAN (R 3.6.1)                       
# locfit                 1.5-9.1    2013-04-20 [1] CRAN (R 3.6.1)                       
# loomR                  0.2.1.9000 2019-10-08 [1] Github (mojaveazure/loomR@1eca16a)   
# lsei                   1.2-0      2017-10-23 [1] CRAN (R 3.6.1)                       
# lubridate              1.7.4      2018-04-11 [1] CRAN (R 3.6.1)                       
# M3DExampleData         1.10.0     2019-05-07 [1] Bioconductor                         
# M3Drop                 1.10.0     2019-05-02 [1] Bioconductor                         
# magrittr               1.5        2014-11-22 [1] CRAN (R 3.6.1)                       
# maps                   3.3.0      2018-04-03 [2] CRAN (R 3.6.3)                       
# maptools               1.0-2      2020-08-24 [1] CRAN (R 3.6.3)                       
# markdown               1.1        2019-08-07 [1] CRAN (R 3.6.1)                       
# MASS                   7.3-51.6   2020-04-26 [2] CRAN (R 3.6.3)                       
# mathjaxr               1.4-0      2021-03-01 [1] CRAN (R 3.6.3)                       
# Matrix                 1.2-18     2019-11-27 [2] CRAN (R 3.6.3)                       
# MatrixModels           0.4-1      2015-08-22 [1] CRAN (R 3.6.3)                       
# matrixStats            0.55.0     2019-09-07 [1] CRAN (R 3.6.1)                       
# mclust                 5.4.5      2019-07-08 [1] CRAN (R 3.6.1)                       
# memoise                1.1.0      2017-04-21 [1] CRAN (R 3.6.1)                       
# metap                  1.1        2019-02-06 [1] CRAN (R 3.6.1)                       
# mgcv                   1.8-31     2019-11-09 [2] CRAN (R 3.6.3)                       
# mime                   0.7        2019-06-11 [1] CRAN (R 3.6.1)                       
# miniUI                 0.1.1.1    2018-05-18 [1] CRAN (R 3.6.1)                       
# minqa                  1.2.4      2014-10-09 [1] CRAN (R 3.6.3)                       
# mixtools               1.1.0      2017-03-10 [1] CRAN (R 3.6.1)                       
# mnormt                 2.0.2      2020-09-01 [1] CRAN (R 3.6.3)                       
# ModelMetrics           1.2.2.2    2020-03-17 [1] CRAN (R 3.6.3)                       
# modelr                 0.1.5      2019-08-08 [1] CRAN (R 3.6.1)                       
# modeltools             0.2-22     2018-07-16 [1] CRAN (R 3.6.1)                       
# monocle                2.12.0     2019-05-02 [1] Bioconductor                         
# moonBook               0.2.3      2019-10-01 [1] Github (cardiomoon/moonBook@1f6c945) 
# mouse4302.db           3.2.3      2021-07-06 [1] Bioconductor                         
# mouse4302cdf           2.18.0     2021-07-06 [1] Bioconductor                         
# multcomp               1.4-15     2020-11-14 [1] CRAN (R 3.6.3)                       
# multicool              0.1-10     2016-11-25 [1] CRAN (R 3.6.1)                       
# multtest               2.40.0     2019-05-02 [1] Bioconductor                         
# munsell                0.5.0      2018-06-12 [1] CRAN (R 3.6.1)                       
# mutoss                 0.1-12     2017-12-04 [1] CRAN (R 3.6.3)                       
# mvtnorm                1.0-11     2019-06-19 [1] CRAN (R 3.6.1)                       
# networkD3              0.4        2017-03-18 [1] CRAN (R 3.6.1)                       
# nlme                   3.1-148    2020-05-24 [2] CRAN (R 3.6.3)                       
# nloptr                 1.2.2.2    2020-07-02 [1] CRAN (R 3.6.3)                       
# NMF                    0.23.0     2020-08-01 [1] CRAN (R 3.6.3)                       
# nnet                   7.3-14     2020-04-26 [2] CRAN (R 3.6.3)                       
# nortest                1.0-4      2015-07-30 [1] CRAN (R 3.6.1)                       
# npsurv                 0.4-0      2017-10-14 [1] CRAN (R 3.6.1)                       
# numDeriv               2016.8-1.1 2019-06-06 [1] CRAN (R 3.6.1)                       
# officer                0.3.5      2019-06-23 [1] CRAN (R 3.6.1)                       
# oligo                  1.48.0     2019-05-02 [1] Bioconductor                         
# oligoClasses           1.46.0     2019-05-02 [1] Bioconductor                         
# openssl                1.4.1      2019-07-18 [1] CRAN (R 3.6.1)                       
# openxlsx             * 4.1.0.1    2019-05-28 [1] CRAN (R 3.6.1)                       
# optparse               1.6.2      2019-04-02 [1] CRAN (R 3.6.1)                       
# org.Hs.eg.db           3.8.2      2019-11-05 [1] Bioconductor                         
# org.Mm.eg.db           3.8.2      2019-10-25 [1] Bioconductor                         
# packrat                0.5.0      2018-11-14 [1] CRAN (R 3.6.1)                       
# pak                    0.2.1      2021-12-20 [1] CRAN (R 3.6.3)                       
# pander                 0.6.3      2018-11-06 [1] CRAN (R 3.6.1)                       
# parallelly             1.30.0     2021-12-17 [1] CRAN (R 3.6.3)                       
# patchwork              1.0.0      2019-12-01 [1] CRAN (R 3.6.1)                       
# pathview               1.24.0     2019-05-02 [1] Bioconductor                         
# pbapply                1.4-2      2019-08-31 [1] CRAN (R 3.6.1)                       
# pbdZMQ                 0.3-3      2018-05-05 [2] CRAN (R 3.6.3)                       
# pbivnorm               0.6.0      2015-01-23 [1] CRAN (R 3.6.1)                       
# pbkrtest               0.5-0.1    2020-12-18 [1] CRAN (R 3.6.3)                       
# pcaExplorer            2.10.1     2019-08-16 [1] Bioconductor                         
# pcaPP                  1.9-73     2018-01-14 [1] CRAN (R 3.6.1)                       
# pdist                  1.2        2013-02-03 [1] CRAN (R 3.6.1)                       
# pheatmap             * 1.0.12     2019-01-04 [1] CRAN (R 3.6.1)                       
# pillar                 1.4.7      2020-11-20 [1] CRAN (R 3.6.3)                       
# pkgbuild               1.0.5      2019-08-26 [1] CRAN (R 3.6.1)                       
# pkgconfig              2.0.2      2018-08-16 [1] CRAN (R 3.6.1)                       
# pkgload                1.0.2      2018-10-29 [1] CRAN (R 3.6.1)                       
# pkgmaker               0.27       2018-05-25 [1] CRAN (R 3.6.1)                       
# plogr                  0.2.0      2018-03-25 [1] CRAN (R 3.6.1)                       
# plotly                 4.9.0      2019-04-10 [1] CRAN (R 3.6.1)                       
# plotrix                3.8-2      2021-09-08 [1] CRAN (R 3.6.3)                       
# plyr                   1.8.4      2016-06-08 [1] CRAN (R 3.6.1)                       
# png                    0.1-7      2013-12-03 [1] CRAN (R 3.6.1)                       
# polyclip               1.10-0     2019-03-14 [1] CRAN (R 3.6.1)                       
# polynom                1.4-0      2019-03-22 [1] CRAN (R 3.6.1)                       
# prabclus               2.3-1      2019-06-04 [1] CRAN (R 3.6.1)                       
# pracma                 2.2.5      2019-04-09 [1] CRAN (R 3.6.1)                       
# praise                 1.0.0      2015-08-11 [1] CRAN (R 3.6.1)                       
# preprocessCore         1.46.0     2019-05-02 [1] Bioconductor                         
# preseqR                4.0.0      2018-06-27 [1] CRAN (R 3.6.1)                       
# prettyunits            1.0.2      2015-07-13 [1] CRAN (R 3.6.1)                       
# pROC                   1.18.0     2021-09-03 [1] CRAN (R 3.6.3)                       
# processx               3.4.1      2019-07-18 [1] CRAN (R 3.6.1)                       
# prodlim                2019.11.13 2019-11-17 [1] CRAN (R 3.6.3)                       
# progress               1.2.2      2019-05-16 [1] CRAN (R 3.6.1)                       
# progressr              0.10.0     2021-12-19 [1] CRAN (R 3.6.3)                       
# promises               1.0.1      2018-04-13 [1] CRAN (R 3.6.1)                       
# propr                  4.2.8      2020-07-08 [1] Github (tpq/propr@2bd7c44)           
# proxy                  0.4-23     2019-03-05 [1] CRAN (R 3.6.1)                       
# pryr                   0.1.4      2018-02-18 [2] CRAN (R 3.6.3)                       
# ps                     1.3.0      2018-12-21 [1] CRAN (R 3.6.1)                       
# psych                  1.8.12     2019-01-12 [1] CRAN (R 3.6.1)                       
# puma                   3.26.0     2019-05-02 [1] Bioconductor                         
# purrr                  0.3.2      2019-03-15 [1] CRAN (R 3.6.1)                       
# qap                    0.1-1      2017-02-27 [1] CRAN (R 3.6.1)                       
# qgraph                 1.6.3      2019-06-19 [1] CRAN (R 3.6.1)                       
# qlcMatrix              0.9.7      2018-04-20 [1] CRAN (R 3.6.1)                       
# quantmod               0.4.17     2020-03-31 [2] CRAN (R 3.6.3)                       
# quantreg               5.82       2021-01-10 [1] CRAN (R 3.6.3)                       
# qvalue                 2.16.0     2019-05-02 [1] Bioconductor                         
# R.methodsS3            1.7.1      2016-02-16 [1] CRAN (R 3.6.1)                       
# R.oo                   1.22.0     2018-04-22 [1] CRAN (R 3.6.1)                       
# R.utils                2.9.0      2019-06-13 [1] CRAN (R 3.6.1)                       
# R6                     2.4.0      2019-02-14 [1] CRAN (R 3.6.1)                       
# randomForest           4.6-14     2018-03-25 [2] CRAN (R 3.6.3)                       
# ranger                 0.13.1     2021-07-14 [1] CRAN (R 3.6.3)                       
# RANN                   2.6.1      2019-01-08 [1] CRAN (R 3.6.1)                       
# rappdirs               0.3.3      2021-01-31 [1] CRAN (R 3.6.3)                       
# RBGL                   1.60.0     2019-05-02 [1] Bioconductor                         
# rbibutils              2.2.7      2021-12-07 [1] CRAN (R 3.6.3)                       
# rbokeh                 0.5.1      2020-05-26 [2] CRAN (R 3.6.3)                       
# rcmdcheck              1.3.3      2019-05-07 [1] CRAN (R 3.6.1)                       
# RColorBrewer         * 1.1-2      2014-12-07 [1] CRAN (R 3.6.1)                       
# Rcpp                   1.0.6      2021-01-15 [1] CRAN (R 3.6.3)                       
# RcppAnnoy              0.0.18     2020-12-15 [1] CRAN (R 3.6.3)                       
# RcppArmadillo          0.10.1.2.2 2021-01-10 [1] CRAN (R 3.6.3)                       
# RcppEigen              0.3.3.5.0  2018-11-24 [1] CRAN (R 3.6.1)                       
# RcppGSL                0.3.7      2019-10-20 [1] CRAN (R 3.6.1)                       
# RcppHNSW               0.1.0      2019-01-21 [1] CRAN (R 3.6.1)                       
# RcppParallel           4.4.3      2019-05-22 [1] CRAN (R 3.6.1)                       
# RcppProgress           0.4.1      2018-05-11 [1] CRAN (R 3.6.1)                       
# RcppTOML               0.1.7      2020-12-02 [1] CRAN (R 3.6.3)                       
# RcppZiggurat           0.1.5      2018-06-10 [1] CRAN (R 3.6.1)                       
# RCurl                  1.95-4.12  2019-03-04 [1] CRAN (R 3.6.1)                       
# Rdpack                 0.11-0     2019-04-14 [1] CRAN (R 3.6.1)                       
# readr                  1.3.1      2018-12-21 [1] CRAN (R 3.6.1)                       
# readxl                 1.3.1      2019-03-13 [1] CRAN (R 3.6.1)                       
# recipes                0.1.17     2021-09-27 [1] CRAN (R 3.6.3)                       
# registry               0.5-1      2019-03-05 [1] CRAN (R 3.6.1)                       
# reldist                1.6-6      2016-10-09 [1] CRAN (R 3.6.1)                       
# rematch                1.0.1      2016-04-21 [1] CRAN (R 3.6.1)                       
# rematch2               2.1.2      2020-05-01 [1] CRAN (R 3.6.3)                       
# remotes                2.1.0      2019-06-24 [1] CRAN (R 3.6.1)                       
# repr                   1.1.0      2020-01-28 [2] CRAN (R 3.6.3)                       
# reprex                 0.3.0      2019-05-16 [1] CRAN (R 3.6.1)                       
# reshape2               1.4.3      2017-12-11 [1] CRAN (R 3.6.1)                       
# reticulate             1.25       2022-05-11 [1] CRAN (R 3.6.3)                       
# rex                    1.1.2      2017-10-19 [1] CRAN (R 3.6.1)                       
# Rfast                  1.9.5      2019-07-12 [1] CRAN (R 3.6.1)                       
# Rgraphviz              2.28.0     2019-05-02 [1] Bioconductor                         
# rhdf5                  2.28.0     2019-05-02 [1] Bioconductor                         
# Rhdf5lib               1.6.1      2019-09-09 [1] Bioconductor                         
# rio                    0.5.16     2018-11-26 [1] CRAN (R 3.6.3)                       
# rjson                  0.2.20     2018-06-08 [1] CRAN (R 3.6.1)                       
# rlang                  0.4.10     2020-12-30 [1] CRAN (R 3.6.3)                       
# rmarkdown              1.15       2019-08-21 [1] CRAN (R 3.6.1)                       
# rngtools               1.4        2019-07-01 [1] CRAN (R 3.6.1)                       
# robustbase             0.93-5     2019-05-12 [1] CRAN (R 3.6.1)                       
# ROCR                   1.0-7      2015-03-26 [1] CRAN (R 3.6.1)                       
# rowr                   1.1.3      2016-12-22 [1] CRAN (R 3.6.1)                       
# roxygen2               6.1.1      2018-11-07 [1] CRAN (R 3.6.1)                       
# rpart                  4.1-15     2019-04-12 [2] CRAN (R 3.6.3)                       
# rprojroot              2.0.2      2020-11-15 [1] CRAN (R 3.6.3)                       
# rrcov                  1.4-7      2018-11-15 [1] CRAN (R 3.6.1)                       
# rrtable                0.1.0      2018-07-27 [1] CRAN (R 3.6.1)                       
# rsconnect              0.8.16     2019-12-13 [1] CRAN (R 3.6.1)                       
# RSpectra               0.15-0     2019-06-11 [1] CRAN (R 3.6.1)                       
# RSQLite                2.1.2      2019-07-24 [1] CRAN (R 3.6.1)                       
# rstatix                0.6.0      2020-06-18 [1] CRAN (R 3.6.3)                       
# rstudioapi             0.10       2019-03-19 [1] CRAN (R 3.6.1)                       
# rsvd                   1.0.2      2019-07-29 [1] CRAN (R 3.6.1)                       
# Rtsne                  0.15       2018-11-10 [1] CRAN (R 3.6.1)                       
# Rttf2pt1               1.3.8      2020-01-10 [1] CRAN (R 3.6.3)                       
# RUnit                  0.4.32     2018-05-18 [1] CRAN (R 3.6.1)                       
# ruv                    0.9.7.1    2019-08-30 [1] CRAN (R 3.6.1)                       
# rvcheck                0.1.5      2019-10-01 [1] CRAN (R 3.6.1)                       
# rversions              2.0.0      2019-05-09 [1] CRAN (R 3.6.1)                       
# rvest                  0.3.5      2019-11-08 [1] CRAN (R 3.6.1)                       
# rvg                    0.2.1      2019-06-25 [1] CRAN (R 3.6.1)                       
# S4Vectors              0.22.0     2019-05-02 [1] Bioconductor                         
# sandwich               3.0-0      2020-10-02 [1] CRAN (R 3.6.3)                       
# SC3                    1.12.0     2019-05-02 [1] Bioconductor                         
# scales                 1.0.0      2018-08-09 [1] CRAN (R 3.6.1)                       
# scater                 1.12.2     2019-05-24 [1] Bioconductor                         
# scattermore            0.7        2020-11-24 [1] CRAN (R 3.6.3)                       
# scatterplot3d          0.3-41     2018-03-14 [1] CRAN (R 3.6.3)                       
# scMerge                1.0.0      2019-05-02 [1] Bioconductor                         
# scran                  1.12.1     2019-05-27 [1] Bioconductor                         
# sctransform            0.3.2      2020-12-16 [1] CRAN (R 3.6.3)                       
# SDMTools               1.1-221.1  2019-04-18 [1] CRAN (R 3.6.1)                       
# segmented              1.0-0      2019-06-17 [1] CRAN (R 3.6.1)                       
# selectr                0.4-1      2018-04-06 [1] CRAN (R 3.6.1)                       
# seriation              1.2-8      2019-08-27 [1] CRAN (R 3.6.1)                       
# sessioninfo            1.1.1      2018-11-05 [1] CRAN (R 3.6.1)                       
# Seurat                 2.3.4      2018-07-20 [1] CRAN (R 3.6.3)                       
# sfsmisc                1.1-6      2020-04-06 [1] CRAN (R 3.6.1)                       
# shape                  1.4.5      2020-09-13 [1] CRAN (R 3.6.3)                       
# shiny                  1.3.2      2019-04-22 [1] CRAN (R 3.6.1)                       
# shinyAce               0.4.1      2019-09-24 [1] CRAN (R 3.6.3)                       
# shinyalert             1.0        2018-02-12 [1] CRAN (R 3.6.1)                       
# shinyBS                0.61       2015-03-31 [1] CRAN (R 3.6.1)                       
# shinydashboard         0.7.1      2018-10-17 [1] CRAN (R 3.6.1)                       
# shinyjs                1.0        2018-01-08 [1] CRAN (R 3.6.1)                       
# shinythemes            1.1.2      2018-11-06 [1] CRAN (R 3.6.1)                       
# SingleCellExperiment   1.6.0      2019-05-02 [1] Bioconductor                         
# sitmo                  2.0.1      2019-01-07 [1] CRAN (R 3.6.1)                       
# sjlabelled             1.1.1      2019-09-13 [1] CRAN (R 3.6.1)                       
# sjmisc                 2.8.2      2019-09-24 [1] CRAN (R 3.6.1)                       
# slam                   0.1-45     2019-02-26 [1] CRAN (R 3.6.1)                       
# sn                     2.0.1      2021-11-26 [1] CRAN (R 3.6.3)                       
# snow                   0.4-3      2018-09-14 [1] CRAN (R 3.6.1)                       
# sourcetools            0.1.7      2018-04-25 [1] CRAN (R 3.6.1)                       
# sp                     1.4-5      2021-01-10 [1] CRAN (R 3.6.3)                       
# SparseM                1.78       2019-12-13 [1] CRAN (R 3.6.3)                       
# sparsesvd              0.2        2019-07-15 [1] CRAN (R 3.6.1)                       
# spatial                7.3-12     2020-04-26 [2] CRAN (R 3.6.3)                       
# spatstat               1.64-1     2020-05-12 [1] CRAN (R 3.6.3)                       
# spatstat.data          1.7-0      2020-12-16 [1] CRAN (R 3.6.3)                       
# spatstat.utils         1.20-2     2021-01-07 [1] CRAN (R 3.6.3)                       
# SQUAREM                2021.1     2021-01-13 [1] CRAN (R 3.6.3)                       
# startupmsg             0.9.6      2019-03-11 [1] CRAN (R 3.6.1)                       
# statmod                1.4.32     2019-05-29 [1] CRAN (R 3.6.1)                       
# stringi                1.4.3      2019-03-12 [1] CRAN (R 3.6.1)                       
# stringr                1.4.0      2019-02-10 [1] CRAN (R 3.6.1)                       
# SummarizedExperiment   1.14.1     2019-07-31 [1] Bioconductor                         
# survival               3.2-3      2020-06-13 [2] CRAN (R 3.6.3)                       
# sva                    3.32.1     2019-05-22 [1] Bioconductor                         
# sys                    3.3        2019-08-21 [1] CRAN (R 3.6.1)                       
# systemfonts            0.1.1      2019-07-01 [1] CRAN (R 3.6.1)                       
# tclust                 1.4-2      2020-09-29 [1] CRAN (R 3.6.3)                       
# tensor                 1.5        2012-05-05 [1] CRAN (R 3.6.3)                       
# testthat               2.2.1      2019-07-25 [1] CRAN (R 3.6.1)                       
# TFisher                0.2.0      2018-03-21 [1] CRAN (R 3.6.3)                       
# TH.data                1.0-10     2019-01-21 [1] CRAN (R 3.6.3)                       
# threejs                0.3.3      2020-01-21 [1] CRAN (R 3.6.3)                       
# tibble               * 3.0.5      2021-01-15 [1] CRAN (R 3.6.3)                       
# tictoc                 1.0        2014-06-17 [1] CRAN (R 3.6.3)                       
# tidygraph              1.1.2      2019-02-18 [1] CRAN (R 3.6.1)                       
# tidyr                  1.0.0      2019-09-11 [1] CRAN (R 3.6.1)                       
# tidyselect             1.1.0      2020-05-11 [1] CRAN (R 3.6.3)                       
# tidyverse              1.2.1      2017-11-14 [1] CRAN (R 3.6.1)                       
# timeDate               3043.102   2018-02-21 [1] CRAN (R 3.6.3)                       
# tinytex                0.15       2019-08-07 [1] CRAN (R 3.6.1)                       
# tmvnsim                1.0-2      2016-12-15 [1] CRAN (R 3.6.3)                       
# topGO                  2.36.0     2019-05-02 [1] Bioconductor                         
# triebeard              0.3.0      2016-08-04 [1] CRAN (R 3.6.1)                       
# tsne                   0.1-3      2016-07-15 [1] CRAN (R 3.6.1)                       
# TSP                    1.1-7      2019-05-22 [1] CRAN (R 3.6.1)                       
# TTR                    0.23-6     2019-12-15 [2] CRAN (R 3.6.3)                       
# tweenr                 1.0.1      2018-12-14 [1] CRAN (R 3.6.1)                       
# UpSetR                 1.4.0      2019-05-22 [1] CRAN (R 3.6.1)                       
# urltools               1.7.3      2019-04-14 [1] CRAN (R 3.6.1)                       
# usethis                1.5.1      2019-07-04 [1] CRAN (R 3.6.1)                       
# utf8                   1.1.4      2018-05-24 [1] CRAN (R 3.6.1)                       
# uuid                   0.1-2      2015-07-28 [1] CRAN (R 3.6.1)                       
# uwot                   0.1.10     2020-12-15 [1] CRAN (R 3.6.3)                       
# vcd                    1.4-4      2017-12-06 [1] CRAN (R 3.6.1)                       
# vctrs                  0.3.6      2020-12-17 [1] CRAN (R 3.6.3)                       
# veccompare             0.1.0      2017-09-15 [1] CRAN (R 3.6.1)                       
# VennDiagram            1.6.20     2018-03-28 [1] CRAN (R 3.6.1)                       
# VGAM                   1.1-1      2019-02-18 [1] CRAN (R 3.6.1)                       
# vipor                  0.4.5      2017-03-22 [1] CRAN (R 3.6.1)                       
# viridis                0.5.1      2018-03-29 [1] CRAN (R 3.6.1)                       
# viridisLite            0.3.0      2018-02-01 [1] CRAN (R 3.6.1)                       
# waldo                  0.2.3      2020-11-09 [1] CRAN (R 3.6.3)                       
# webr                   0.1.4.1    2019-10-01 [1] Github (cardiomoon/webr@0b3c8c1)     
# webshot                0.5.1      2018-09-28 [1] CRAN (R 3.6.1)                       
# whisker                0.4        2019-08-28 [1] CRAN (R 3.6.1)                       
# withr                  2.1.2      2018-03-15 [1] CRAN (R 3.6.1)                       
# WriteXLS               5.0.0      2019-05-25 [1] CRAN (R 3.6.1)                       
# xfun                   0.9        2019-08-21 [1] CRAN (R 3.6.1)                       
# XML                    3.98-1.20  2019-06-06 [1] CRAN (R 3.6.1)                       
# xml2                   1.2.2      2019-08-09 [1] CRAN (R 3.6.1)                       
# xopen                  1.0.0      2018-09-17 [1] CRAN (R 3.6.1)                       
# xtable                 1.8-4      2019-04-21 [1] CRAN (R 3.6.1)                       
# xts                    0.12-0     2020-01-19 [2] CRAN (R 3.6.3)                       
# XVector                0.24.0     2019-05-02 [1] Bioconductor                         
# yaml                   2.2.0      2018-07-25 [1] CRAN (R 3.6.1)                       
# zeallot                0.1.0      2018-01-28 [1] CRAN (R 3.6.1)                       
# zip                    2.0.4      2019-09-01 [1] CRAN (R 3.6.1)                       
# zlibbioc               1.30.0     2019-05-02 [1] Bioconductor                         
# zoo                    1.8-6      2019-05-28 [1] CRAN (R 3.6.1)                       
# ztable                 0.2.0      2018-07-22 [1] CRAN (R 3.6.1)                       
```

-------------------------------------------------------------------------------------------------------------------
