---
title: "scrbseq"
output: html_document
---

## Prepare session

```{r setup, include=FALSE}
require(knitr)
knitr::opts_chunk$set(echo = TRUE)
path <- '~/Desktop/scrbseq'
dir.create(path = path, recursive = T)
knitr::opts_knit$set(root.dir = path, collapse = T, comment = '#>')
```

```{r loadlibraries, echo=FALSE}
library(scater)
library(tibble)
library(ggpubr)
library(dplyr)
library(data.table)
library(SingleCellExperiment)
library(openxlsx)
library(Seurat)
library(cowplot)
library(pheatmap)

# Define custom themes for ggplot
theme_custom <- theme(axis.text.x = element_text(size = 12.8, color = 'black'),
                      axis.text.y = element_text(size = 12.8, color = 'black'), 
                      axis.title.x = element_text(size = 16, margin = margin(6,0,0,0)), 
                      axis.title.y = element_text(size = 16, margin = margin(0,8,0,0)),
                      plot.title = element_text(size = 16, face = 'plain', hjust = 0.5, margin = margin(5,0,10,0)),
                      plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(0,0,10,0)), 
                      axis.ticks.x = element_line(size = 0.4, colour = 'black'), 
                      axis.ticks.y = element_line(size = 0.4, colour = 'black'),
                      axis.line = element_blank(), 
                      panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank(),
                      panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(),
                      panel.border = element_rect(colour = 'black', size = 0.8, fill = NA),
                      panel.background = element_rect(colour = NA, fill = NA), 
                      strip.text.x = element_text(size = 16, face = 'plain', margin = margin(0,0,5,0) ), 
                      strip.text.y = element_text(size = 16, face = 'plain', margin = margin(0,0,0,5) ), 
                      strip.background = element_blank(), 
                      legend.key = element_blank(), legend.key.size = unit(0.5,'cm'),
                      legend.text = element_text(size = 12.8), 
                      legend.title = element_text(size = 12.8),
                      plot.background = element_rect(colour = NA, fill = NA), aspect.ratio = 1)
theme_custom2 <- theme(axis.text.x = element_blank(), 
                       axis.text.y = element_blank(), 
                       axis.title.x = element_text(size = 16, margin = margin(4,0,0,0)), 
                       axis.title.y = element_text(size = 16, margin = margin(0,4,0,0)),
                       plot.title = element_text(size = 16, face = 'plain', hjust = 0.5, margin = margin(5,0,10,0)),
                       plot.subtitle = element_text(size = 12, hjust = 0.5, margin = margin(0,0,10,0)), 
                       axis.ticks.x = element_blank(), 
                       axis.ticks.y = element_blank(), 
                       axis.line = element_blank(), 
                       panel.grid.minor.y = element_blank(), panel.grid.major.y = element_blank(),
                       panel.grid.minor.x = element_blank(), panel.grid.major.x = element_blank(),
                       panel.border = element_rect(colour = 'grey80', size = 0.8, fill = NA),
                       panel.background = element_rect(colour = NA, fill = NA),
                       strip.text.x = element_text(size = 16, face = 'plain', margin = margin(0,0,5,0) ), 
                       strip.text.y = element_text(size = 16, face = 'plain', margin = margin(0,0,0,5) ), 
                       strip.background = element_blank(), 
                       legend.key = element_blank(), legend.key.size = unit(0.5,'cm'),
                       legend.text = element_text(size = 12.8), 
                       legend.title = element_text(size = 12.8),
                       plot.background = element_rect(colour = NA, fill = NA), aspect.ratio = 1)

# Function to save plots with same size
grid <- function(data, layout=rbind(c(1,1,1,1,2,2,3))) {
  gridExtra::grid.arrange(grobs = list(data + guides(color = 'none', fill = 'none', size = 'none'), 
                                       cowplot::get_legend(data)), ncol = 2, layout_matrix = layout, 
                          top = grid::textGrob('', gp = grid::gpar(fontsize = 16, font = 2)))
}
```

-------------------------------------------------------------------------------------------------------------------

## Data pre-processing

```{r load raw data}
# Download pre-processed data from GEO SuperSeries and place at '~/Desktop/bulk/'
download.file(url='https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE200359&format=file&file=GSE200359%5FRun30%5Fcounts%2Ecsv%2Egz', destfile=paste0(path, '/GSE200359_Run30_counts.csv.gz'))

# Prepare data
Raw_data <- read.csv(gzfile(paste0(path, '/GSE200359_Run30_counts.csv.gz')), header = T, row.names = 1, sep = ',', stringsAsFactors = F)

# Filtering
Raw_data <- Raw_data[rowSums(Raw_data) > 1, ]

# Metadata
Design <- data.frame(row.names = colnames(Raw_data),
                    cell_name = colnames(Raw_data),
                    cell_type = as.character(lapply(colnames(Raw_data), function(x) unlist(strsplit(x, '[.]'))[2])),
                    stringsAsFactors = F)

# Create sce
sce = SingleCellExperiment(assays = list(counts = as.matrix(Raw_data)), colData = Design) %>% calculateQCMetrics()
cell_info = as.data.frame(colData(sce))

# Calculate percentage of mito-genes, ribo-genes
mito.genes <- grep(pattern = "^mt-", x = rownames(Raw_data), value = TRUE)
ribo.genes <- grep(pattern = "^Rpl", x = rownames(Raw_data), value = TRUE)
cell_info$mito_percentage <- Matrix::colSums(Raw_data[mito.genes, ]) / Matrix::colSums(Raw_data)
cell_info$ribo_percentage <- Matrix::colSums(Raw_data[ribo.genes, ]) / Matrix::colSums(Raw_data)
#write.xlsx(cell_info, paste0(path, '/raw_cell_info.xlsx'))

# filter by GENE > 500 and UMI > 5000
selected_cells = cell_info %>% dplyr::filter(total_features_by_counts > 500 & total_counts > 5000)
selected_expr = Raw_data[,colnames(Raw_data) %in% as.character(selected_cells$cell_name)]
```

-------------------------------------------------------------------------------------------------------------------

## Seurat clustering

```{r}
# reinstall seurat package version 2.3.4

# Create seurat object
SC3_Seurat = CreateSeuratObject(raw.data = as.data.frame(selected_expr), normalization.method = 'LogNormalize', meta.data = 
                                  data.frame(row.names = colnames(selected_expr),
                                             cell_type = Design[colnames(selected_expr),'cell_type']))

# Find variable features
SC3_Seurat <- FindVariableGenes(object = SC3_Seurat, mean.function = ExpMean, dispersion.function = LogVMR,
                                x.low.cutoff = 0.0125, x.high.cutoff = 3,
                                y.cutoff = 0.5, do.plot = F)

# Scale data
SC3_Seurat <- ScaleData(SC3_Seurat)

# Run PCA
SC3_Seurat <- RunPCA(object = SC3_Seurat, pcs.compute = 20, pc.genes = SC3_Seurat@var.genes, do.print = T)
SC3_Seurat <- FindClusters(object = SC3_Seurat, reduction.type = "pca", 
                       dims.use = 1:10, k.param = 200, resolution = 0.8,
                       print.output = 0, save.SNN = F, n.iter = 1000, n.start = 1000)
#saveRDS(SC3_Seurat, paste0(path, '/seurat_obj.rds'))
```

-------------------------------------------------------------------------------------------------------------------

## Dimensional reduction Visualization

```{r}
SC3_Seurat <- RunTSNE(object = SC3_Seurat, reduction.use = "pca", dims.use = 1:10, nthreads = 4, reduction.name = "tSNE", reduction.key = "tSNE_", max_iter = 2000)
SC3_Seurat <- RunUMAP(object = SC3_Seurat, reduction.use = "pca", dims.use = 1:10, min_dist = 0.75)
##Seurat3
#SC3_Seurat <- UpdateSeuratObject(SC3_Seurat)
#SC3_Seurat <- RunTSNE(object = SC3_Seurat, reduction = "pca", dims = 1:10, nthreads = 4, reduction.name = "tSNE", reduction.key = "tSNE_", max_iter = 2000)
#SC3_Seurat <- RunUMAP(object = SC3_Seurat, reduction = "pca", dims = 1:10, min_dist = 0.75)

# Rename clusters
SC3_Seurat@ident <- factor(plyr::mapvalues(SC3_Seurat@ident, from = 0:4, to = c(1,5,4,3,2) ), levels=1:5)
#Idents(SC3_Seurat) <- factor(plyr::mapvalues(Idents(SC3_Seurat), from = 0:4, to = c(1,5,4,3,2) ), levels=1:5) #Seurat3

# Plot tSNE
colors <- c('#8DC73F','#25CED1','#FF8A5B', '#EA526F','#FFCA04','#731DD8', '#D5A18E')
condition_color = c('#BF4342', '#033F63')
#tmp <- as.factor(as.numeric(SC3_Seurat@ident))
##tmp <- as.factor(as.numeric(Idents(SC3_Seurat))) #Seurat3
#names(tmp) <- SC3_Seurat@cell.names
#SC3_Seurat@ident <- tmp

p1 <- DimPlot(object = SC3_Seurat, reduction.use = "tSNE", do.return = TRUE, group.by = "ident", vector.friendly = TRUE, pt.size = 5, cols.use = colors) + ggtitle("tSNE") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2

p2 <- DimPlot(object = SC3_Seurat, reduction.use = "umap", do.return = TRUE, vector.friendly = TRUE, pt.size = 4, cols.use = colors) + ggtitle("UMAP") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2

p3 <- DimPlot(object = SC3_Seurat, reduction.use = "tSNE", do.return = TRUE, group.by = 'cell_type', cols.use = condition_color, vector.friendly = TRUE, pt.size = 5) + ggtitle("Cell type") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2

p4 <- DimPlot(object = SC3_Seurat, reduction.use = "umap", do.return = TRUE, group.by = 'cell_type', cols.use = condition_color, vector.friendly = TRUE, pt.size = 4) + ggtitle("Cell Type") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2

##Seurat3
#p1 <- DimPlot(object = SC3_Seurat, reduction = "tSNE", group.by = "ident", pt.size = 1, cols = colors, label = T, 
#              label.size = 5) + ggtitle("tSNE") + theme(plot.title = element_text(hjust = 0.5), 
#                                                        text = element_text(size = 20)) + theme_custom2
#
#p2 <- DimPlot(object = SC3_Seurat, reduction = "umap", pt.size = 1, cols = colors) + ggtitle("UMAP") + theme(plot.title = #element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2
#
#p3 <- DimPlot(object = SC3_Seurat, reduction = "tSNE", group.by = 'cell_type', cols = condition_color, pt.size = 1) + #ggtitle("Cell type") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20)) + theme_custom2
#
#p4 <- DimPlot(object = SC3_Seurat, reduction = "umap", do.return = TRUE, group.by = 'cell_type', cols = condition_color, #pt.size = 1) + ggtitle("Cell Type") + theme(plot.title = element_text(hjust = 0.5), text = element_text(size = 20))

# Save umap plots
ggsave(plot = grid(p1,rbind(c(1,1,1,1,1,1,1,1,1,2,3))), file = paste0(path, '/Fig5Al.pdf'), height = 4.2, width = 4.5)
ggsave(plot = grid(p3,rbind(c(1,1,1,1,1,1,1,1,1,2,3))), file = paste0(path, '/Fig5Ar.pdf'), height = 4.2, width = 4.5)
```

-------------------------------------------------------------------------------------------------------------------

## Feature plots

```{r}
# Genelists
genes <- list(a=c('Tcf7','Ccr7','Sell','Il7r','Slamf6','Bcl2','Stat5a','Id3'), 
              b=c('Gzma','Gzmb','Id2','Prf1'), 
              c=c('Mki67','Dhodh'),
              d=c('Myc','Hdac1','Hdac7','Hif1a','Hif1an','Xbp1'))

# Plot expression
fp1 <- FeaturePlot(SC3_Seurat, genes$a, dark.theme = F, reduction.use = 'tSNE', pt.size = 5, vector.friendly = T, nCol = 4, cols.use = c('grey', 'red'), no.legend = F, no.axes = T, do.return = T) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2
fp2 <- FeaturePlot(SC3_Seurat, genes$b, dark.theme = F, reduction.use = 'tSNE', pt.size = 5, vector.friendly = T, nCol = 2, cols.use = c('grey', 'red'), no.legend = F, no.axes = T, do.return = T) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2
fp3 <- FeaturePlot(SC3_Seurat, genes$c, dark.theme = F, reduction.use = 'tSNE', pt.size = 5, vector.friendly = T, nCol = 1, cols.use = c('grey', 'red'), no.legend = F, no.axes = T, do.return = T) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2
fp4 <- FeaturePlot(SC3_Seurat, genes$d, dark.theme = F, reduction.use = 'tSNE', pt.size = 5, vector.friendly = T, nCol = 1, cols.use = c('grey', 'red'), no.legend = F, no.axes = T, do.return = T) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2

##Seurat3
fp1 <- FeaturePlot(SC3_Seurat, features = genes$a, reduction = 'tSNE', pt.size = 1, 
                   ncol = 4, cols = c('grey', 'red'), combine = F)
fp1 <- lapply(1:length(fp1), function(x) fp1[[x]] + 
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                      panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2 )
fp1 <- gridExtra::grid.arrange(grobs = fp1, ncol=4)
fp2 <- FeaturePlot(SC3_Seurat, features = genes$b, reduction = 'tSNE', pt.size = 1, 
                   ncol = 2, cols = c('grey', 'red'), combine = F)
fp2 <- lapply(1:length(fp2), function(x) fp2[[x]] + 
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                      panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2 )
fp2 <- gridExtra::grid.arrange(grobs = fp2, ncol=2)
fp3 <- FeaturePlot(SC3_Seurat, features = genes$c, reduction = 'tSNE', pt.size = 1, 
                   ncol = 2, cols = c('grey', 'red'), combine = F)
fp3 <- lapply(1:length(fp3), function(x) fp3[[x]] + 
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                      panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2 )
fp3 <- gridExtra::grid.arrange(grobs = fp3, ncol=1)
fp4 <- FeaturePlot(SC3_Seurat, features = genes$d, reduction = 'tSNE', pt.size = 1, 
                   ncol = 2, cols = c('grey', 'red'), combine = F)
fp4 <- lapply(1:length(fp4), function(x) fp4[[x]] + 
                theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), 
                      panel.background = element_blank(), axis.line = element_line(colour = "black")) + theme_custom2 )
fp4 <- gridExtra::grid.arrange(grobs = fp4, ncol=1)

# Save umap plots
ggsave(plot = fp1, file = paste0(path, '/Fig5Cl.pdf'), height = 7, width = 15)
ggsave(plot = fp2, file = paste0(path, '/Fig5Cr.pdf'), height = 7, width = 8)
ggsave(plot = fp3, file = paste0(path, '/Fig6A.pdf'), height = 7, width = 4.2)
ggsave(plot = fp4, file = paste0(path, '/ExtData9Bl.pdf'), height = 20.5, width = 4.2)
```

-------------------------------------------------------------------------------------------------------------------

## Bar plots

```{r}
##Seurat3
# Function to draw dotplot
col <- list(hm=colorRampPalette(c('#133d67','#2166AC','#90b2d5','#d2e0ee','grey90','#efd0d4','#d88b95','#B2182B','#590c15'))(41), hm2=colorRampPalette(c('grey90','#efd0d4','#d88b95','#B2182B','#590c15'))(41))
dotplot <- function(object=bd, sel=genes$sel1, cl=F, scale=T, b=15, gr=NULL, sample='OT1 cells', subtitle='Expression by cluster',smax=100) {
  sel <- sel[sel %in% rownames(object)]
  dt <- DotPlot(object, assay = 'RNA', features = sel, cluster.idents = cl, scale.max=smax, group.by = gr)$data
  if(!is.null(gr)) dt <- cbind(dt, reshape2::colsplit(dt$id, pattern = '_', names = c('condition','cluster')))
  if(scale) l <- list(a=-1.5,b=1.5) else l <- list(a=0,b=b)
  #dtI <- transform(reshape2::dcast(dt, features.plot ~ id, value.var='avg.exp'), row.names = features.plot)[,-1]
  #sel.order <- hclust(d = dist(x = scale(dtI)))
  #sel.order <- callback(sel.order, dtI)
  #dt$features.plot <- factor(dt$features.plot, levels = rownames(dtI)[sel.order$order] )
  p <- ggplot(dt, aes(if(!is.null(gr)) factor(cluster, levels=rev(unique(cluster))) else factor(id, levels=rev(unique(id))), features.plot, color=if(scale) avg.exp.scaled else avg.exp, size=pct.exp)) + 
    geom_point() + scale_x_discrete('cluster') + scale_y_discrete('') + coord_flip() + 
    scale_color_gradientn(ifelse(scale,'z-score','Avg. exp.'), colours = if(scale) col$hm else col$hm2, oob = scales::squish, 
                          limits = c(l$a,l$b), breaks = seq(l$a,l$b, length.out = 3)) + 
    scale_size_continuous('Pct. exp', limits = c(0,smax), breaks = seq(0,smax,smax/4), range = c(0,6)) + 
    ggtitle(gsub('_',' ',sample), subtitle = subtitle) + theme_custom + 
    #facet_grid(.~factor(celltype, levels = levels(object$celltype)), scales = 'free', space = 'free') + 
    facet_grid(features.plot~., scales = 'free', space = 'free') + 
    theme(aspect.ratio = length(unique(dt$id)) / length(sel), #aspect.ratio = length(sel) / length(unique(dt$id)),  
          strip.text = element_text(size = 12.8, face = 'plain', angle=0, vjust=0, hjust=0.5, margin = margin(5,0,5,0)), 
          #axis.text.x = element_text(size = 12.8, color = 'black', angle = 0, vjust = 1, hjust = 0.5))
          axis.text.x = element_text(size = 12.8, color = 'black', angle = 90, vjust = 0.5, hjust = 1))
  if(!is.null(gr)) p + facet_grid(factor(condition, levels = levels(bd$all$condition))~., scales = 'free', space = 'free') else p
}

# Function to rescale
rescale <- function(scores,to=c(0,1)) if(any(scores > 1)) scales::rescale(scores, to=to) else scores

# Extract data
df.pct <- dotplot(object = SC3_Seurat, sel = unlist(genes[c('c','d')]), gr=NULL)$data
df.pct <- dplyr::bind_rows(Map(x=unique(df.pct$features.plot), function(x) {
  dfI <- df.pct %>% filter(features.plot %in% x) %>% mutate(scaled = rescale(avg.exp))
  #dfI <- cbind(dfI, reshape2::colsplit(dfI$id, pattern = '_', names = c('condition','cluster')))
  return(dfI)
}))

# Plot bar plot
bp3 <- ggplot(df.pct %>% filter(features.plot %in% genes$c), aes(x = id, y = pct.exp)) + 
  geom_bar(aes(fill = scaled), color='black', size=0.5, stat = 'identity', width = 0.7, alpha = 1) + 
  scale_x_discrete('cluster') + 
  scale_y_continuous('% expressing cells', limits=c(0,100), breaks = seq(0,100,20), expand = c(0,0)) + 
  scale_fill_gradientn('Exp.', colours = col$hm2, oob = scales::squish, 
                       limits = c(0,1), breaks = seq(0,1, length.out = 2), labels = c('min','max')) + 
  facet_grid(features.plot~., scales = 'free', space = 'free') +
  ggtitle('OT1 cells', subtitle = 'Upstream regulators') + theme_custom + #theme(aspect.ratio = NULL)
  theme(axis.text.x = element_text(size = 12.8, color = 'black', angle = 0, vjust = 0, hjust = 0.5), aspect.ratio = NULL, panel.spacing = unit(0.7, "lines"))
bp4 <- ggplot(df.pct %>% filter(features.plot %in% genes$d), aes(x = id, y = pct.exp)) + 
  geom_bar(aes(fill = scaled), color='black', size=0.5, stat = 'identity', width = 0.7, alpha = 1) + 
  scale_x_discrete('cluster') + 
  scale_y_continuous('% expressing cells', limits=c(0,100), breaks = seq(0,100,20), expand = c(0,0)) + 
  scale_fill_gradientn('Exp.', colours = col$hm2, oob = scales::squish, 
                       limits = c(0,1), breaks = seq(0,1, length.out = 2), labels = c('min','max')) + 
  facet_grid(features.plot~., scales = 'free', space = 'free') +
  ggtitle('OT1 cells', subtitle = 'Upstream regulators') + theme_custom + #theme(aspect.ratio = NULL)
  theme(axis.text.x = element_text(size = 12.8, color = 'black', angle = 0, vjust = 0, hjust = 0.5), aspect.ratio = NULL, panel.spacing = unit(0.7, "lines"))

# Save umap plots
ggsave(plot = bp3, file = paste0(path, '/Fig6B.pdf'), height = 5.5, width = 4)
ggsave(plot = bp4, file = paste0(path, '/ExtData9Br.pdf'), height = 14, width = 4)
```

-------------------------------------------------------------------------------------------------------------------

## Heatmap for each cluster with average expression

```{r}
# Gene list
selected_genes = list(a=c("Mki67", "Ezh2", "Id2", "Id3", "Gzma", "Gzmb", "Gzmk", "Klrg1", "Prf1", "Fasl", "Havcr2", 
                   "Pdcd1", "Lgals3", "Lgals1", "Il18r1", "Il17ra", "Cxcr6", "Cxcr3", "Klf2", "S1pr1", "S1pr4", 
                   "Tcf7", "Slamf6", "Ccr7", "Bcl2", "Il7r", "Sell", "Il6ra", "Klf3", 
                   "Myc", "Bcl2l1", "Il2ra", "Cd83", "Tnfrsf18", "Batf3", "Bax", "Icos", "Cd81", "Tnfrsf4", 
                   "Tnfsf4", "Tnfrsf9", "Tnfsf14", "Dhodh", "Cad", "Umps"))
                   

# Prepare data
data.use = SC3_Seurat@scale.data
#data.use = SC3_Seurat@assays$RNA@scale.data #Seurat3
cell_info = SC3_Seurat@meta.data
#cell_info$seurat_cluster = as.numeric(SC3_Seurat@ident)
#cell_info$seurat_cluster = as.numeric(Idents(SC3_Seurat))
cell_info$seurat_cluster = as.numeric(SC3_Seurat$res.0.8)+1
cell_info$cell_names = rownames(cell_info)
order.data.use = data.use[unlist(selected_genes),cell_info[order(cell_info$seurat_cluster, decreasing = F), 'cell_names']]
#annotation = data.frame(row.names = SC3_Seurat@cell.names, cell.type = SC3_Seurat@meta.data$cell_type, cluster = SC3_Seurat@ident)
#annotation = data.frame(row.names = colnames(SC3_Seurat), cell.type = SC3_Seurat@meta.data$cell_type, cluster = Idents(SC3_Seurat)) #Seurat3
# cluster = c('0' = '#8DC73F', '1' = '#25CED1', '2' = '#FF8A5B','3' = '#EA526F', '4' = '#FFCA04', '5' = '#731DD8')
annotation_colors = list(cell.type = c('CMC' = '#033F63', 'Tfl' = '#BF4342'), 
                         cluster = c('1' = '#8DC73F', '2' = '#25CED1', '3' = '#FF8A5B', '4' = '#EA526F', '5' = '#FFCA04'))
split = c(0, 351, 679, 988,1258, 1518)
avg_df = NULL
for (j in 1:(length(split)-1)) {
  avg_df <- rbind(avg_df, rowMeans(order.data.use[,((split[j]+1): split[j+1])]))
}
avg_df <- as.data.frame(t(avg_df))
colnames(avg_df) <- c('Cluster_1', 'Cluster_2', 'Cluster_3', 'Cluster_4', 'Cluster_5')[c(1,5,4,3,2)]
avg_df <- avg_df[,c(1,5,4,3,2)]
new_annotation = data.frame(row.names = colnames(avg_df), Cluster = as.factor(colnames(avg_df)))
new_annotation_color <- list(Cluster = c('Cluster_1' = '#8DC73F', 'Cluster_2' = '#FFCA04', 'Cluster_3' = '#EA526F', 'Cluster_4' = '#FF8A5B', 'Cluster_5' = '#25CED1'))

# Plot heatmap
heat1 <- pheatmap(t(avg_df[rownames(avg_df) %in% selected_genes$a,]), 
                 cluster_rows = FALSE, cluster_cols = FALSE, show_colnames = T, 
                 #legend_breaks = seq(-0.5,1,0.5), breaks = seq(-0.5,1,length.out=100), 
                 annotation_row = new_annotation, cutree_cols =  1, gaps_col = c(), cellwidth = 15, cellheight = 15, 
                 annotation_colors=new_annotation_color, fontsize = 12)

# Save heatmap
ggsave(paste0(path, '/ExtData9A.pdf'), heat1[[4]], height = 3, width = 13)
ggsave(paste0(path, '/ExtData9D.pdf'), heat2[[4]], height = 3, width = 13)
```

-------------------------------------------------------------------------------------------------------------------

## GSEA for cluster markers

```{r}
library(AnnotationDbi)
library(org.Mm.eg.db)
library(clusterProfiler)

# Find cluster markers
mk <- Map(x=levels(SC3_Seurat@ident), function(x) FindMarkers(SC3_Seurat, ident.1 = x) %>% rownames_to_column(., 'GeneName'))
#write.xlsx(mk[order(mk$avg_logFC, decreasing = T),], file = paste0(path, 'Cluster_', i, '_Markergenes.xlsx'))

# Run enrichment analysis for KEGG pathways and MolSigDB signatures c2
download.file(url='https://data.broadinstitute.org/gsea-msigdb/msigdb/release/6.2/c2.all.v6.2.symbols.gmt', 
              destfile=paste0(path, '/c2.all.v6.2.symbols.gmt'))
c2 <- read.gmt(paste0(path, '/c2.all.v6.2.symbols.gmt'))
enrich <- lapply(setNames(levels(SC3_Seurat@ident), nm=levels(SC3_Seurat@ident))[-3], function(x) {
#enrich <- Map(x=setNames(as.numeric(levels(Idents(SC3_Seurat))), nm=as.numeric(levels(Idents(SC3_Seurat))))[-4], function(x) {#Seurat3
  deg <- mk[[x]]
  deg$entrez = mapIds(org.Mm.eg.db,
                       keys=as.character(deg$GeneName), 
                       column="ENTREZID",
                       keytype="SYMBOL",
                       multiVals="first")
  
  #remove NAs
  deg <- deg[complete.cases(deg),]
  
  #KEGG over-representation test (hypergeometric test)
  path_enrich <- enrichKEGG(deg$entrez, organism = 'mmu')
  
  #Plot enrichment
  kegg <- clusterProfiler::dotplot(path_enrich,  font.size = 6) + 
    theme(legend.key.size = unit(0.8, 'line')) +
    coord_cartesian(xlim = c(0,1))
  
  #MolsigDB c2 enrichment
  msig_enrich <- enricher(toupper(deg$GeneName), TERM2GENE = c2)
  
  #Plot enrichment
  msig <- clusterProfiler::dotplot(msig_enrich,  font.size = 6) + 
    theme(legend.key.size = unit(0.8, 'line')) +
    coord_cartesian(xlim = c(0,1))
  
  return(list(kegg=kegg, msig=msig))
})

# Save plots
lapply(c(1,2), function(x) ggsave(paste0(path, '/Fig6C',x,'.pdf'), enrich[[x]]$kegg, height = 4, width = 5) )
lapply(names(enrich), function(x) ggsave(paste0(path, '/ExtData9C',x,'.pdf'), enrich[[x]]$msig, height = 8, width = 6) )
```

-------------------------------------------------------------------------------------------------------------------
## Session info

```{r sessioninfo, collapse=T, echo=F, warning=F, message=F, include=F}
installed.packages() %>% rownames() %>% devtools::package_info()
#─ Session info ───────────────────────────────────────────────────────────────
# setting  value                       
# version  R version 3.6.3 (2020-02-29)
# os       Ubuntu 16.04.7 LTS          
# system   x86_64, linux-gnu           
# ui       X11                         
# language (EN)                        
# collate  C.UTF-8                     
# ctype    C.UTF-8                     
# tz       Europe/Berlin               
#
#─ Packages ───────────────────────────────────────────────────────────────────
# package              * version    date       lib source                               
# abind                  1.4-5      2016-07-21 [1] CRAN (R 3.6.1)                       
# acepack                1.4.1      2016-10-29 [1] CRAN (R 3.6.1)                       
# affxparser             1.56.0     2019-05-02 [1] Bioconductor                         
# affy                   1.62.0     2019-05-02 [1] Bioconductor                         
# affyio                 1.54.0     2019-05-02 [1] Bioconductor                         
# anndata                0.7.5.5    2022-09-23 [1] CRAN (R 3.6.3)                       
# annotate               1.62.0     2019-05-02 [1] Bioconductor                         
# AnnotationDbi        * 1.46.1     2019-08-20 [1] Bioconductor                         
# AnnotationForge        1.26.0     2019-05-02 [1] Bioconductor                         
# apcluster              1.4.8      2019-08-21 [1] CRAN (R 3.6.1)                       
# ape                    5.3        2019-03-17 [1] CRAN (R 3.6.1)                       
# askpass                1.1        2019-01-13 [1] CRAN (R 3.6.1)                       
# assertthat             0.2.1      2019-03-21 [1] CRAN (R 3.6.1)                       
# backports              1.1.4      2019-04-10 [1] CRAN (R 3.6.1)                       
# base64enc              0.1-3      2015-07-28 [1] CRAN (R 3.6.1)                       
# BBmisc                 1.11       2017-03-10 [1] CRAN (R 3.6.1)                       
# bbmle                  1.0.20     2017-10-30 [1] CRAN (R 3.6.1)                       
# BDgraph                2.61       2019-09-05 [1] CRAN (R 3.6.1)                       
# beachmat               2.0.0      2019-05-02 [1] Bioconductor                         
# beeswarm               0.2.3      2016-04-25 [1] CRAN (R 3.6.1)                       
# BH                     1.69.0-1   2019-01-07 [1] CRAN (R 3.6.1)                       
# bibtex                 0.4.2      2017-06-30 [1] CRAN (R 3.6.1)                       
# Biobase                2.44.0     2019-05-02 [1] Bioconductor                         
# BiocGenerics           0.30.0     2019-05-02 [1] Bioconductor                         
# BiocManager            1.30.4     2018-11-13 [1] CRAN (R 3.6.1)                       
# BiocNeighbors          1.2.0      2019-05-02 [1] Bioconductor                         
# BiocParallel           1.18.1     2019-08-06 [1] Bioconductor                         
# BiocSingular           1.0.0      2019-05-02 [1] Bioconductor                         
# BiocVersion            3.9.0      2018-10-30 [1] Bioconductor                         
# biocViews              1.52.2     2019-05-29 [1] Bioconductor                         
# biomaRt                2.40.5     2019-10-01 [1] Bioconductor                         
# Biostrings             2.52.0     2019-05-02 [1] Bioconductor                         
# bit                    1.1-14     2018-05-29 [1] CRAN (R 3.6.1)                       
# bit64                  0.9-7      2017-05-08 [1] CRAN (R 3.6.1)                       
# bitops                 1.0-6      2013-08-17 [1] CRAN (R 3.6.1)                       
# blob                   1.2.0      2019-07-09 [1] CRAN (R 3.6.1)                       
# boot                   1.3-25     2020-04-26 [2] CRAN (R 3.6.3)                       
# brew                   1.0-6      2011-04-13 [1] CRAN (R 3.6.1)                       
# brio                   1.1.1      2021-01-20 [1] CRAN (R 3.6.3)                       
# broom                  0.7.3      2020-12-16 [1] CRAN (R 3.6.3)                       
# calibrate              1.7.5      2019-10-01 [1] CRAN (R 3.6.1)                       
# callr                  3.3.1      2019-07-18 [1] CRAN (R 3.6.1)                       
# car                    3.0-10     2020-09-29 [1] CRAN (R 3.6.3)                       
# carData                3.0-4      2020-05-22 [1] CRAN (R 3.6.3)                       
# caret                  6.0-90     2021-10-09 [1] CRAN (R 3.6.3)                       
# Category               2.50.0     2019-05-02 [1] Bioconductor                         
# caTools                1.17.1.2   2019-03-06 [1] CRAN (R 3.6.1)                       
# cellranger             1.1.0      2016-07-27 [1] CRAN (R 3.6.1)                       
# checkmate              1.9.4      2019-07-04 [1] CRAN (R 3.6.1)                       
# circlize               0.4.10     2020-06-15 [1] CRAN (R 3.6.3)                       
# class                  7.3-17     2020-04-26 [2] CRAN (R 3.6.3)                       
# cli                    1.1.0      2019-03-19 [1] CRAN (R 3.6.1)                       
# clipr                  0.7.0      2019-07-23 [1] CRAN (R 3.6.1)                       
# clisymbols             1.2.0      2017-05-21 [1] CRAN (R 3.6.1)                       
# cluster                2.1.0      2019-06-19 [2] CRAN (R 3.6.3)                       
# clusterProfiler      * 3.12.0     2019-05-02 [1] Bioconductor                         
# codetools              0.2-16     2018-12-24 [2] CRAN (R 3.6.3)                       
# coin                   1.3-1      2019-08-28 [1] CRAN (R 3.6.3)                       
# colorspace             1.4-1      2019-03-18 [1] CRAN (R 3.6.1)                       
# colourpicker           1.0        2017-09-27 [1] CRAN (R 3.6.1)                       
# combinat               0.0-8      2012-10-29 [1] CRAN (R 3.6.1)                       
# commonmark             1.7        2018-12-01 [1] CRAN (R 3.6.1)                       
# conquer                1.0.2      2020-08-27 [1] CRAN (R 3.6.3)                       
# coop                   0.6-2      2019-04-22 [1] CRAN (R 3.6.1)                       
# corpcor                1.6.9      2017-04-01 [1] CRAN (R 3.6.1)                       
# corrplot               0.84       2017-10-16 [1] CRAN (R 3.6.1)                       
# covr                   3.3.1      2019-08-23 [1] CRAN (R 3.6.1)                       
# cowplot              * 1.0.0      2019-07-11 [1] CRAN (R 3.6.1)                       
# cpp11                  0.2.5      2021-01-12 [1] CRAN (R 3.6.3)                       
# crayon                 1.3.4      2017-09-16 [1] CRAN (R 3.6.1)                       
# crosstalk              1.0.0      2016-12-21 [1] CRAN (R 3.6.1)                       
# curl                   4.0        2019-07-22 [1] CRAN (R 3.6.1)                       
# d3heatmap              0.6.1.2    2018-02-01 [1] CRAN (R 3.6.1)                       
# d3Network              0.5.2.1    2015-01-31 [1] CRAN (R 3.6.1)                       
# data.table           * 1.12.2     2019-04-07 [1] CRAN (R 3.6.1)                       
# DBI                    1.0.0      2018-05-02 [1] CRAN (R 3.6.1)                       
# dbplyr                 1.4.2      2019-06-17 [1] CRAN (R 3.6.1)                       
# DDRTree                0.1.5      2017-04-30 [1] CRAN (R 3.6.1)                       
# debrowser              1.12.3     2019-08-09 [1] Bioconductor                         
# DelayedArray           0.10.0     2019-05-02 [1] Bioconductor                         
# DelayedMatrixStats     1.6.1      2019-09-08 [1] Bioconductor                         
# deldir                 0.2-9      2021-01-16 [1] CRAN (R 3.6.3)                       
# dendextend             1.12.0     2019-05-11 [1] CRAN (R 3.6.1)                       
# densityClust           0.3        2017-10-24 [1] CRAN (R 3.6.1)                       
# DEoptimR               1.0-8      2016-11-19 [1] CRAN (R 3.6.1)                       
# desc                   1.2.0      2018-05-01 [1] CRAN (R 3.6.1)                       
# DESeq2                 1.24.0     2019-05-02 [1] Bioconductor                         
# devEMF                 3.6-3      2019-06-24 [1] CRAN (R 3.6.1)                       
# devtools               2.2.0      2019-09-07 [1] CRAN (R 3.6.1)                       
# diffobj                0.3.3      2021-01-07 [1] CRAN (R 3.6.3)                       
# diffusionMap           1.2.0      2019-09-10 [1] CRAN (R 3.6.3)                       
# digest                 0.6.20     2019-07-04 [1] CRAN (R 3.6.1)                       
# diptest                0.75-7     2016-12-05 [1] CRAN (R 3.6.1)                       
# distr                  2.8.0      2019-03-11 [1] CRAN (R 3.6.1)                       
# distutils              1.0        2021-01-21 [1] Github (Albluca/distutils@cd82bca)   
# DO.db                  2.9        2019-10-25 [1] Bioconductor                         
# docopt                 0.6.1      2018-10-11 [1] CRAN (R 3.6.1)                       
# doParallel             1.0.15     2019-08-02 [1] CRAN (R 3.6.1)                       
# doRNG                  1.7.1      2018-06-22 [1] CRAN (R 3.6.1)                       
# DOSE                   3.10.2     2019-06-24 [1] Bioconductor                         
# doSNOW                 1.0.18     2019-07-27 [1] CRAN (R 3.6.1)                       
# dplyr                * 1.0.3      2021-01-15 [1] CRAN (R 3.6.3)                       
# dqrng                  0.2.1      2019-05-17 [1] CRAN (R 3.6.1)                       
# dropestr               0.7.9      2019-09-15 [1] Github (hms-dbmi/dropEst@5abbc9c)    
# DT                     0.8        2019-08-07 [1] CRAN (R 3.6.1)                       
# dtw                    1.21-3     2019-09-01 [1] CRAN (R 3.6.1)                       
# dynamicTreeCut         1.63-1     2016-03-11 [1] CRAN (R 3.6.3)                       
# e1071                  1.7-2      2019-06-05 [1] CRAN (R 3.6.1)                       
# edgeR                  3.26.8     2019-09-01 [1] Bioconductor                         
# editData               0.1.2      2017-10-07 [1] CRAN (R 3.6.1)                       
# ellipsis               0.2.0.1    2019-07-02 [1] CRAN (R 3.6.1)                       
# ElPiGraph.R            1.0.0      2021-01-21 [1] Github (Albluca/ElPiGraph.R@761a48a) 
# enrichplot             1.4.0      2019-05-02 [1] Bioconductor                         
# europepmc              0.3        2018-04-20 [1] CRAN (R 3.6.1)                       
# evaluate               0.14       2019-05-28 [1] CRAN (R 3.6.1)                       
# extrafont              0.17       2014-12-08 [1] CRAN (R 3.6.3)                       
# extrafontdb            1.0        2012-06-11 [1] CRAN (R 3.6.3)                       
# fansi                  0.4.0      2018-10-05 [1] CRAN (R 3.6.1)                       
# farver                 1.1.0      2018-11-20 [1] CRAN (R 3.6.1)                       
# fastcluster            1.1.25     2018-06-07 [1] CRAN (R 3.6.1)                       
# fastICA                1.2-2      2019-07-08 [1] CRAN (R 3.6.1)                       
# fastmap                1.1.0      2021-01-25 [1] CRAN (R 3.6.3)                       
# fastmatch              1.1-0      2017-01-28 [1] CRAN (R 3.6.1)                       
# fdrtool                1.2.15     2015-07-08 [1] CRAN (R 3.6.1)                       
# ff                     2.2-14     2018-05-15 [1] CRAN (R 3.6.1)                       
# fgsea                  1.10.1     2019-08-21 [1] Bioconductor                         
# fitdistrplus           1.0-14     2019-01-23 [1] CRAN (R 3.6.1)                       
# flexmix                2.3-15     2019-02-18 [1] CRAN (R 3.6.1)                       
# flextable              0.5.5      2019-06-25 [1] CRAN (R 3.6.1)                       
# FNN                    1.1.3      2019-02-15 [1] CRAN (R 3.6.1)                       
# forcats                0.4.0      2019-02-17 [1] CRAN (R 3.6.1)                       
# foreach                1.4.7      2019-07-27 [1] CRAN (R 3.6.1)                       
# foreign                0.8-76     2020-03-03 [2] CRAN (R 3.6.3)                       
# formatR                1.7        2019-06-11 [1] CRAN (R 3.6.1)                       
# Formula                1.2-3      2018-05-03 [1] CRAN (R 3.6.1)                       
# fpc                    2.2-3      2019-06-28 [1] CRAN (R 3.6.1)                       
# fs                     1.3.1      2019-05-06 [1] CRAN (R 3.6.1)                       
# futile.logger          1.4.3      2016-07-10 [1] CRAN (R 3.6.1)                       
# futile.options         1.0.1      2018-04-20 [1] CRAN (R 3.6.1)                       
# future                 1.14.0     2019-07-02 [1] CRAN (R 3.6.1)                       
# future.apply           1.3.0      2019-06-18 [1] CRAN (R 3.6.1)                       
# gage                   2.34.0     2019-05-02 [1] Bioconductor                         
# gbRd                   0.4-11     2012-10-01 [1] CRAN (R 3.6.1)                       
# gclus                  1.3.2      2019-01-07 [1] CRAN (R 3.6.1)                       
# gdata                  2.18.0     2017-06-06 [1] CRAN (R 3.6.1)                       
# gdtools                0.2.0      2019-09-03 [1] CRAN (R 3.6.1)                       
# genefilter             1.66.0     2019-05-02 [1] Bioconductor                         
# geneplotter            1.62.0     2019-05-02 [1] Bioconductor                         
# generics               0.1.2      2022-01-31 [1] CRAN (R 3.6.3)                       
# GenomeInfoDb           1.20.0     2019-05-02 [1] Bioconductor                         
# GenomeInfoDbData       1.2.1      2019-09-10 [1] Bioconductor                         
# GenomicRanges          1.36.1     2019-09-06 [1] Bioconductor                         
# GenSA                  1.1.7      2018-01-17 [1] CRAN (R 3.6.3)                       
# GEOquery               2.52.0     2019-05-02 [1] Bioconductor                         
# getopt                 1.20.3     2019-03-22 [1] CRAN (R 3.6.1)                       
# ggbeeswarm             0.6.0      2017-08-07 [1] CRAN (R 3.6.1)                       
# ggforce                0.3.1      2019-08-20 [1] CRAN (R 3.6.1)                       
# ggfortify              0.4.7      2019-05-26 [1] CRAN (R 3.6.1)                       
# ggm                    2.3        2015-01-21 [1] CRAN (R 3.6.1)                       
# ggplot2                3.3.2      2020-06-19 [1] CRAN (R 3.6.3)                       
# ggplotify              0.0.4      2019-08-06 [1] CRAN (R 3.6.1)                       
# ggpubr               * 0.2.3      2019-09-03 [1] CRAN (R 3.6.1)                       
# ggradar                0.2        2019-10-09 [1] Github (ricardo-bion/ggradar@6d675be)
# ggraph                 2.0.0      2019-09-02 [1] CRAN (R 3.6.1)                       
# ggrepel                0.8.1      2019-05-07 [1] CRAN (R 3.6.1)                       
# ggridges               0.5.1      2018-09-27 [1] CRAN (R 3.6.1)                       
# ggsci                  2.9        2018-05-14 [1] CRAN (R 3.6.1)                       
# ggsignif               0.6.0      2019-08-08 [1] CRAN (R 3.6.1)                       
# gh                     1.0.1      2017-07-16 [1] CRAN (R 3.6.1)                       
# gistr                  0.5.0      2020-01-09 [2] CRAN (R 3.6.3)                       
# git2r                  0.26.1     2019-06-29 [1] CRAN (R 3.6.1)                       
# glasso                 1.11       2019-10-01 [1] CRAN (R 3.6.1)                       
# glmnet                 4.0-2      2020-06-16 [2] CRAN (R 3.6.3)                       
# GlobalOptions          0.1.2      2020-06-10 [1] CRAN (R 3.6.3)                       
# globals                0.12.4     2018-10-11 [1] CRAN (R 3.6.1)                       
# glue                   1.4.2      2020-08-27 [1] CRAN (R 3.6.3)                       
# GO.db                  3.8.2      2019-10-25 [1] Bioconductor                         
# goftest                1.2-2      2019-12-02 [1] CRAN (R 3.6.3)                       
# GOSemSim               2.10.0     2019-05-02 [1] Bioconductor                         
# GOstats                2.50.0     2019-05-02 [1] Bioconductor                         
# gower                  1.0.0      2022-02-03 [1] CRAN (R 3.6.3)                       
# gplots                 3.0.1.1    2019-01-27 [1] CRAN (R 3.6.1)                       
# gProfileR              0.6.8      2019-09-07 [1] CRAN (R 3.6.1)                       
# graph                  1.62.0     2019-05-02 [1] Bioconductor                         
# graphlayouts           0.5.0      2019-08-20 [1] CRAN (R 3.6.1)                       
# gridBase               0.4-7      2014-02-24 [1] CRAN (R 3.6.3)                       
# gridExtra              2.3        2017-09-09 [1] CRAN (R 3.6.1)                       
# gridGraphics           0.4-1      2019-05-20 [1] CRAN (R 3.6.1)                       
# GSEABase               1.46.0     2019-05-02 [1] Bioconductor                         
# gtable                 0.3.0      2019-03-25 [1] CRAN (R 3.6.1)                       
# gtools                 3.8.1      2018-06-26 [1] CRAN (R 3.6.1)                       
# Harman                 1.12.0     2019-05-02 [1] Bioconductor                         
# hash                   2.2.6.1    2019-03-04 [1] CRAN (R 3.6.1)                       
# haven                  2.1.1      2019-07-04 [1] CRAN (R 3.6.1)                       
# HDF5Array              1.12.2     2019-08-06 [1] Bioconductor                         
# hdf5r                  1.3.3      2021-01-19 [1] Github (hhoeflin/hdf5r@5c9074f)      
# heatmaply              0.16.0     2019-05-11 [1] CRAN (R 3.6.1)                       
# here                   1.0.1      2020-12-13 [1] CRAN (R 3.6.3)                       
# hexbin                 1.27.3     2019-05-14 [1] CRAN (R 3.6.1)                       
# highr                  0.8        2019-03-20 [1] CRAN (R 3.6.1)                       
# Hmisc                  4.2-0      2019-01-26 [1] CRAN (R 3.6.1)                       
# hms                    0.5.1      2019-08-23 [1] CRAN (R 3.6.1)                       
# hrbrthemes             0.8.0      2020-03-06 [1] CRAN (R 3.6.3)                       
# HSMMSingleCell         1.4.0      2019-05-07 [1] Bioconductor                         
# htmlTable              1.13.1     2019-01-07 [1] CRAN (R 3.6.1)                       
# htmltools              0.3.6      2017-04-28 [1] CRAN (R 3.6.1)                       
# htmlwidgets            1.3        2018-09-30 [1] CRAN (R 3.6.1)                       
# httpuv                 1.5.2      2019-09-11 [1] CRAN (R 3.6.1)                       
# httr                   1.4.1      2019-08-05 [1] CRAN (R 3.6.1)                       
# huge                   1.3.4      2019-10-28 [1] CRAN (R 3.6.1)                       
# ica                    1.0-2      2018-05-24 [1] CRAN (R 3.6.1)                       
# igraph                 1.2.4.1    2019-04-22 [1] CRAN (R 3.6.1)                       
# infotheo               1.2.0      2014-07-26 [1] CRAN (R 3.6.3)                       
# ini                    0.3.1      2018-05-20 [1] CRAN (R 3.6.1)                       
# insight                0.5.0      2019-09-07 [1] CRAN (R 3.6.1)                       
# ipred                  0.9-12     2021-09-15 [1] CRAN (R 3.6.3)                       
# IRanges                2.18.2     2019-08-24 [1] Bioconductor                         
# IRdisplay              0.7.0      2020-05-04 [2] local                                
# IRkernel               1.1.1      2020-07-20 [2] CRAN (R 3.6.3)                       
# irlba                  2.3.3      2019-02-05 [1] CRAN (R 3.6.1)                       
# isoband                0.2.2      2020-06-20 [1] CRAN (R 3.6.1)                       
# iterators              1.0.12     2019-07-26 [1] CRAN (R 3.6.1)                       
# jpeg                   0.1-8.1    2019-10-24 [1] CRAN (R 3.6.1)                       
# jsonlite               1.6        2018-12-07 [1] CRAN (R 3.6.1)                       
# KEGGgraph              1.44.0     2019-05-02 [1] Bioconductor                         
# KEGGREST               1.24.1     2019-10-08 [1] Bioconductor                         
# kernlab                0.9-27     2018-08-10 [1] CRAN (R 3.6.1)                       
# KernSmooth             2.23-17    2020-04-26 [2] CRAN (R 3.6.3)                       
# knitr                  1.24       2019-08-08 [1] CRAN (R 3.6.1)                       
# ks                     1.11.5     2019-05-20 [1] CRAN (R 3.6.1)                       
# labeling               0.3        2014-08-23 [1] CRAN (R 3.6.1)                       
# lambda.r               1.2.3      2018-05-17 [1] CRAN (R 3.6.1)                       
# lars                   1.2        2013-04-24 [1] CRAN (R 3.6.1)                       
# later                  0.8.0      2019-02-11 [1] CRAN (R 3.6.1)                       
# lattice                0.20-41    2020-04-02 [2] CRAN (R 3.6.3)                       
# latticeExtra           0.6-28     2016-02-09 [1] CRAN (R 3.6.1)                       
# lava                   1.6.10     2021-09-02 [1] CRAN (R 3.6.3)                       
# lavaan                 0.6-5      2019-08-28 [1] CRAN (R 3.6.1)                       
# lazyeval               0.2.2      2019-03-15 [1] CRAN (R 3.6.1)                       
# leiden                 0.3.1      2019-07-23 [1] CRAN (R 3.6.1)                       
# libcoin                1.0-6      2020-08-14 [1] CRAN (R 3.6.3)                       
# lifecycle              0.2.0      2020-03-06 [1] CRAN (R 3.6.3)                       
# limma                  3.40.6     2019-07-26 [1] Bioconductor                         
# listenv                0.7.0      2018-01-21 [1] CRAN (R 3.6.1)                       
# lme4                   1.1-26     2020-12-01 [1] CRAN (R 3.6.3)                       
# lmPerm                 2.1.0      2016-08-02 [1] CRAN (R 3.6.3)                       
# lmtest                 0.9-37     2019-04-30 [1] CRAN (R 3.6.1)                       
# locfit                 1.5-9.1    2013-04-20 [1] CRAN (R 3.6.1)                       
# loomR                  0.2.1.9000 2019-10-08 [1] Github (mojaveazure/loomR@1eca16a)   
# lsei                   1.2-0      2017-10-23 [1] CRAN (R 3.6.1)                       
# lubridate              1.7.4      2018-04-11 [1] CRAN (R 3.6.1)                       
# M3DExampleData         1.10.0     2019-05-07 [1] Bioconductor                         
# M3Drop                 1.10.0     2019-05-02 [1] Bioconductor                         
# magrittr               1.5        2014-11-22 [1] CRAN (R 3.6.1)                       
# maps                   3.3.0      2018-04-03 [2] CRAN (R 3.6.3)                       
# maptools               1.0-2      2020-08-24 [1] CRAN (R 3.6.3)                       
# markdown               1.1        2019-08-07 [1] CRAN (R 3.6.1)                       
# MASS                   7.3-51.6   2020-04-26 [2] CRAN (R 3.6.3)                       
# mathjaxr               1.4-0      2021-03-01 [1] CRAN (R 3.6.3)                       
# Matrix                 1.2-18     2019-11-27 [2] CRAN (R 3.6.3)                       
# MatrixModels           0.4-1      2015-08-22 [1] CRAN (R 3.6.3)                       
# matrixStats            0.55.0     2019-09-07 [1] CRAN (R 3.6.1)                       
# mclust                 5.4.5      2019-07-08 [1] CRAN (R 3.6.1)                       
# memoise                1.1.0      2017-04-21 [1] CRAN (R 3.6.1)                       
# metap                  1.1        2019-02-06 [1] CRAN (R 3.6.1)                       
# mgcv                   1.8-31     2019-11-09 [2] CRAN (R 3.6.3)                       
# mime                   0.7        2019-06-11 [1] CRAN (R 3.6.1)                       
# miniUI                 0.1.1.1    2018-05-18 [1] CRAN (R 3.6.1)                       
# minqa                  1.2.4      2014-10-09 [1] CRAN (R 3.6.3)                       
# mixtools               1.1.0      2017-03-10 [1] CRAN (R 3.6.1)                       
# mnormt                 2.0.2      2020-09-01 [1] CRAN (R 3.6.3)                       
# ModelMetrics           1.2.2.2    2020-03-17 [1] CRAN (R 3.6.3)                       
# modelr                 0.1.5      2019-08-08 [1] CRAN (R 3.6.1)                       
# modeltools             0.2-22     2018-07-16 [1] CRAN (R 3.6.1)                       
# monocle                2.12.0     2019-05-02 [1] Bioconductor                         
# moonBook               0.2.3      2019-10-01 [1] Github (cardiomoon/moonBook@1f6c945) 
# mouse4302.db           3.2.3      2021-07-06 [1] Bioconductor                         
# mouse4302cdf           2.18.0     2021-07-06 [1] Bioconductor                         
# multcomp               1.4-15     2020-11-14 [1] CRAN (R 3.6.3)                       
# multicool              0.1-10     2016-11-25 [1] CRAN (R 3.6.1)                       
# multtest               2.40.0     2019-05-02 [1] Bioconductor                         
# munsell                0.5.0      2018-06-12 [1] CRAN (R 3.6.1)                       
# mutoss                 0.1-12     2017-12-04 [1] CRAN (R 3.6.3)                       
# mvtnorm                1.0-11     2019-06-19 [1] CRAN (R 3.6.1)                       
# networkD3              0.4        2017-03-18 [1] CRAN (R 3.6.1)                       
# nlme                   3.1-148    2020-05-24 [2] CRAN (R 3.6.3)                       
# nloptr                 1.2.2.2    2020-07-02 [1] CRAN (R 3.6.3)                       
# NMF                    0.23.0     2020-08-01 [1] CRAN (R 3.6.3)                       
# nnet                   7.3-14     2020-04-26 [2] CRAN (R 3.6.3)                       
# nortest                1.0-4      2015-07-30 [1] CRAN (R 3.6.1)                       
# npsurv                 0.4-0      2017-10-14 [1] CRAN (R 3.6.1)                       
# numDeriv               2016.8-1.1 2019-06-06 [1] CRAN (R 3.6.1)                       
# officer                0.3.5      2019-06-23 [1] CRAN (R 3.6.1)                       
# oligo                  1.48.0     2019-05-02 [1] Bioconductor                         
# oligoClasses           1.46.0     2019-05-02 [1] Bioconductor                         
# openssl                1.4.1      2019-07-18 [1] CRAN (R 3.6.1)                       
# openxlsx             * 4.1.0.1    2019-05-28 [1] CRAN (R 3.6.1)                       
# optparse               1.6.2      2019-04-02 [1] CRAN (R 3.6.1)                       
# org.Hs.eg.db           3.8.2      2019-11-05 [1] Bioconductor                         
# org.Mm.eg.db         * 3.8.2      2019-10-25 [1] Bioconductor                         
# packrat                0.5.0      2018-11-14 [1] CRAN (R 3.6.1)                       
# pak                    0.2.1      2021-12-20 [1] CRAN (R 3.6.3)                       
# pander                 0.6.3      2018-11-06 [1] CRAN (R 3.6.1)                       
# parallelly             1.30.0     2021-12-17 [1] CRAN (R 3.6.3)                       
# patchwork              1.0.0      2019-12-01 [1] CRAN (R 3.6.1)                       
# pathview               1.24.0     2019-05-02 [1] Bioconductor                         
# pbapply                1.4-2      2019-08-31 [1] CRAN (R 3.6.1)                       
# pbdZMQ                 0.3-3      2018-05-05 [2] CRAN (R 3.6.3)                       
# pbivnorm               0.6.0      2015-01-23 [1] CRAN (R 3.6.1)                       
# pbkrtest               0.5-0.1    2020-12-18 [1] CRAN (R 3.6.3)                       
# pcaExplorer            2.10.1     2019-08-16 [1] Bioconductor                         
# pcaPP                  1.9-73     2018-01-14 [1] CRAN (R 3.6.1)                       
# pdist                  1.2        2013-02-03 [1] CRAN (R 3.6.1)                       
# pheatmap             * 1.0.12     2019-01-04 [1] CRAN (R 3.6.1)                       
# pillar                 1.4.7      2020-11-20 [1] CRAN (R 3.6.3)                       
# pkgbuild               1.0.5      2019-08-26 [1] CRAN (R 3.6.1)                       
# pkgconfig              2.0.2      2018-08-16 [1] CRAN (R 3.6.1)                       
# pkgload                1.0.2      2018-10-29 [1] CRAN (R 3.6.1)                       
# pkgmaker               0.27       2018-05-25 [1] CRAN (R 3.6.1)                       
# plogr                  0.2.0      2018-03-25 [1] CRAN (R 3.6.1)                       
# plotly                 4.9.0      2019-04-10 [1] CRAN (R 3.6.1)                       
# plotrix                3.8-2      2021-09-08 [1] CRAN (R 3.6.3)                       
# plyr                   1.8.4      2016-06-08 [1] CRAN (R 3.6.1)                       
# png                    0.1-7      2013-12-03 [1] CRAN (R 3.6.1)                       
# polyclip               1.10-0     2019-03-14 [1] CRAN (R 3.6.1)                       
# polynom                1.4-0      2019-03-22 [1] CRAN (R 3.6.1)                       
# prabclus               2.3-1      2019-06-04 [1] CRAN (R 3.6.1)                       
# pracma                 2.2.5      2019-04-09 [1] CRAN (R 3.6.1)                       
# praise                 1.0.0      2015-08-11 [1] CRAN (R 3.6.1)                       
# preprocessCore         1.46.0     2019-05-02 [1] Bioconductor                         
# preseqR                4.0.0      2018-06-27 [1] CRAN (R 3.6.1)                       
# prettyunits            1.0.2      2015-07-13 [1] CRAN (R 3.6.1)                       
# pROC                   1.18.0     2021-09-03 [1] CRAN (R 3.6.3)                       
# processx               3.4.1      2019-07-18 [1] CRAN (R 3.6.1)                       
# prodlim                2019.11.13 2019-11-17 [1] CRAN (R 3.6.3)                       
# progress               1.2.2      2019-05-16 [1] CRAN (R 3.6.1)                       
# progressr              0.10.0     2021-12-19 [1] CRAN (R 3.6.3)                       
# promises               1.0.1      2018-04-13 [1] CRAN (R 3.6.1)                       
# propr                  4.2.8      2020-07-08 [1] Github (tpq/propr@2bd7c44)           
# proxy                  0.4-23     2019-03-05 [1] CRAN (R 3.6.1)                       
# pryr                   0.1.4      2018-02-18 [2] CRAN (R 3.6.3)                       
# ps                     1.3.0      2018-12-21 [1] CRAN (R 3.6.1)                       
# psych                  1.8.12     2019-01-12 [1] CRAN (R 3.6.1)                       
# puma                   3.26.0     2019-05-02 [1] Bioconductor                         
# purrr                  0.3.2      2019-03-15 [1] CRAN (R 3.6.1)                       
# qap                    0.1-1      2017-02-27 [1] CRAN (R 3.6.1)                       
# qgraph                 1.6.3      2019-06-19 [1] CRAN (R 3.6.1)                       
# qlcMatrix              0.9.7      2018-04-20 [1] CRAN (R 3.6.1)                       
# quantmod               0.4.17     2020-03-31 [2] CRAN (R 3.6.3)                       
# quantreg               5.82       2021-01-10 [1] CRAN (R 3.6.3)                       
# qvalue                 2.16.0     2019-05-02 [1] Bioconductor                         
# R.methodsS3            1.7.1      2016-02-16 [1] CRAN (R 3.6.1)                       
# R.oo                   1.22.0     2018-04-22 [1] CRAN (R 3.6.1)                       
# R.utils                2.9.0      2019-06-13 [1] CRAN (R 3.6.1)                       
# R6                     2.4.0      2019-02-14 [1] CRAN (R 3.6.1)                       
# randomForest           4.6-14     2018-03-25 [2] CRAN (R 3.6.3)                       
# ranger                 0.13.1     2021-07-14 [1] CRAN (R 3.6.3)                       
# RANN                   2.6.1      2019-01-08 [1] CRAN (R 3.6.1)                       
# rappdirs               0.3.3      2021-01-31 [1] CRAN (R 3.6.3)                       
# RBGL                   1.60.0     2019-05-02 [1] Bioconductor                         
# rbibutils              2.2.7      2021-12-07 [1] CRAN (R 3.6.3)                       
# rbokeh                 0.5.1      2020-05-26 [2] CRAN (R 3.6.3)                       
# rcmdcheck              1.3.3      2019-05-07 [1] CRAN (R 3.6.1)                       
# RColorBrewer           1.1-2      2014-12-07 [1] CRAN (R 3.6.1)                       
# Rcpp                   1.0.6      2021-01-15 [1] CRAN (R 3.6.3)                       
# RcppAnnoy              0.0.18     2020-12-15 [1] CRAN (R 3.6.3)                       
# RcppArmadillo          0.10.1.2.2 2021-01-10 [1] CRAN (R 3.6.3)                       
# RcppEigen              0.3.3.5.0  2018-11-24 [1] CRAN (R 3.6.1)                       
# RcppGSL                0.3.7      2019-10-20 [1] CRAN (R 3.6.1)                       
# RcppHNSW               0.1.0      2019-01-21 [1] CRAN (R 3.6.1)                       
# RcppParallel           4.4.3      2019-05-22 [1] CRAN (R 3.6.1)                       
# RcppProgress           0.4.1      2018-05-11 [1] CRAN (R 3.6.1)                       
# RcppTOML               0.1.7      2020-12-02 [1] CRAN (R 3.6.3)                       
# RcppZiggurat           0.1.5      2018-06-10 [1] CRAN (R 3.6.1)                       
# RCurl                  1.95-4.12  2019-03-04 [1] CRAN (R 3.6.1)                       
# Rdpack                 0.11-0     2019-04-14 [1] CRAN (R 3.6.1)                       
# readr                  1.3.1      2018-12-21 [1] CRAN (R 3.6.1)                       
# readxl                 1.3.1      2019-03-13 [1] CRAN (R 3.6.1)                       
# recipes                0.1.17     2021-09-27 [1] CRAN (R 3.6.3)                       
# registry               0.5-1      2019-03-05 [1] CRAN (R 3.6.1)                       
# reldist                1.6-6      2016-10-09 [1] CRAN (R 3.6.1)                       
# rematch                1.0.1      2016-04-21 [1] CRAN (R 3.6.1)                       
# rematch2               2.1.2      2020-05-01 [1] CRAN (R 3.6.3)                       
# remotes                2.1.0      2019-06-24 [1] CRAN (R 3.6.1)                       
# repr                   1.1.0      2020-01-28 [2] CRAN (R 3.6.3)                       
# reprex                 0.3.0      2019-05-16 [1] CRAN (R 3.6.1)                       
# reshape2               1.4.3      2017-12-11 [1] CRAN (R 3.6.1)                       
# reticulate             1.25       2022-05-11 [1] CRAN (R 3.6.3)                       
# rex                    1.1.2      2017-10-19 [1] CRAN (R 3.6.1)                       
# Rfast                  1.9.5      2019-07-12 [1] CRAN (R 3.6.1)                       
# Rgraphviz              2.28.0     2019-05-02 [1] Bioconductor                         
# rhdf5                  2.28.0     2019-05-02 [1] Bioconductor                         
# Rhdf5lib               1.6.1      2019-09-09 [1] Bioconductor                         
# rio                    0.5.16     2018-11-26 [1] CRAN (R 3.6.3)                       
# rjson                  0.2.20     2018-06-08 [1] CRAN (R 3.6.1)                       
# rlang                  0.4.10     2020-12-30 [1] CRAN (R 3.6.3)                       
# rmarkdown              1.15       2019-08-21 [1] CRAN (R 3.6.1)                       
# rngtools               1.4        2019-07-01 [1] CRAN (R 3.6.1)                       
# robustbase             0.93-5     2019-05-12 [1] CRAN (R 3.6.1)                       
# ROCR                   1.0-7      2015-03-26 [1] CRAN (R 3.6.1)                       
# rowr                   1.1.3      2016-12-22 [1] CRAN (R 3.6.1)                       
# roxygen2               6.1.1      2018-11-07 [1] CRAN (R 3.6.1)                       
# rpart                  4.1-15     2019-04-12 [2] CRAN (R 3.6.3)                       
# rprojroot              2.0.2      2020-11-15 [1] CRAN (R 3.6.3)                       
# rrcov                  1.4-7      2018-11-15 [1] CRAN (R 3.6.1)                       
# rrtable                0.1.0      2018-07-27 [1] CRAN (R 3.6.1)                       
# rsconnect              0.8.16     2019-12-13 [1] CRAN (R 3.6.1)                       
# RSpectra               0.15-0     2019-06-11 [1] CRAN (R 3.6.1)                       
# RSQLite                2.1.2      2019-07-24 [1] CRAN (R 3.6.1)                       
# rstatix                0.6.0      2020-06-18 [1] CRAN (R 3.6.3)                       
# rstudioapi             0.10       2019-03-19 [1] CRAN (R 3.6.1)                       
# rsvd                   1.0.2      2019-07-29 [1] CRAN (R 3.6.1)                       
# Rtsne                  0.15       2018-11-10 [1] CRAN (R 3.6.1)                       
# Rttf2pt1               1.3.8      2020-01-10 [1] CRAN (R 3.6.3)                       
# RUnit                  0.4.32     2018-05-18 [1] CRAN (R 3.6.1)                       
# ruv                    0.9.7.1    2019-08-30 [1] CRAN (R 3.6.1)                       
# rvcheck                0.1.5      2019-10-01 [1] CRAN (R 3.6.1)                       
# rversions              2.0.0      2019-05-09 [1] CRAN (R 3.6.1)                       
# rvest                  0.3.5      2019-11-08 [1] CRAN (R 3.6.1)                       
# rvg                    0.2.1      2019-06-25 [1] CRAN (R 3.6.1)                       
# S4Vectors              0.22.0     2019-05-02 [1] Bioconductor                         
# sandwich               3.0-0      2020-10-02 [1] CRAN (R 3.6.3)                       
# SC3                    1.12.0     2019-05-02 [1] Bioconductor                         
# scales                 1.0.0      2018-08-09 [1] CRAN (R 3.6.1)                       
# scater               * 1.12.2     2019-05-24 [1] Bioconductor                         
# scattermore            0.7        2020-11-24 [1] CRAN (R 3.6.3)                       
# scatterplot3d          0.3-41     2018-03-14 [1] CRAN (R 3.6.3)                       
# scMerge                1.0.0      2019-05-02 [1] Bioconductor                         
# scran                  1.12.1     2019-05-27 [1] Bioconductor                         
# sctransform            0.3.2      2020-12-16 [1] CRAN (R 3.6.3)                       
# SDMTools               1.1-221.1  2019-04-18 [1] CRAN (R 3.6.1)                       
# segmented              1.0-0      2019-06-17 [1] CRAN (R 3.6.1)                       
# selectr                0.4-1      2018-04-06 [1] CRAN (R 3.6.1)                       
# seriation              1.2-8      2019-08-27 [1] CRAN (R 3.6.1)                       
# sessioninfo            1.1.1      2018-11-05 [1] CRAN (R 3.6.1)                       
# Seurat               * 2.3.4      2018-07-20 [1] CRAN (R 3.6.3)                       
# sfsmisc                1.1-6      2020-04-06 [1] CRAN (R 3.6.1)                       
# shape                  1.4.5      2020-09-13 [1] CRAN (R 3.6.3)                       
# shiny                  1.3.2      2019-04-22 [1] CRAN (R 3.6.1)                       
# shinyAce               0.4.1      2019-09-24 [1] CRAN (R 3.6.3)                       
# shinyalert             1.0        2018-02-12 [1] CRAN (R 3.6.1)                       
# shinyBS                0.61       2015-03-31 [1] CRAN (R 3.6.1)                       
# shinydashboard         0.7.1      2018-10-17 [1] CRAN (R 3.6.1)                       
# shinyjs                1.0        2018-01-08 [1] CRAN (R 3.6.1)                       
# shinythemes            1.1.2      2018-11-06 [1] CRAN (R 3.6.1)                       
# SingleCellExperiment * 1.6.0      2019-05-02 [1] Bioconductor                         
# sitmo                  2.0.1      2019-01-07 [1] CRAN (R 3.6.1)                       
# sjlabelled             1.1.1      2019-09-13 [1] CRAN (R 3.6.1)                       
# sjmisc                 2.8.2      2019-09-24 [1] CRAN (R 3.6.1)                       
# slam                   0.1-45     2019-02-26 [1] CRAN (R 3.6.1)                       
# sn                     2.0.1      2021-11-26 [1] CRAN (R 3.6.3)                       
# snow                   0.4-3      2018-09-14 [1] CRAN (R 3.6.1)                       
# sourcetools            0.1.7      2018-04-25 [1] CRAN (R 3.6.1)                       
# sp                     1.4-5      2021-01-10 [1] CRAN (R 3.6.3)                       
# SparseM                1.78       2019-12-13 [1] CRAN (R 3.6.3)                       
# sparsesvd              0.2        2019-07-15 [1] CRAN (R 3.6.1)                       
# spatial                7.3-12     2020-04-26 [2] CRAN (R 3.6.3)                       
# spatstat               1.64-1     2020-05-12 [1] CRAN (R 3.6.3)                       
# spatstat.data          1.7-0      2020-12-16 [1] CRAN (R 3.6.3)                       
# spatstat.utils         1.20-2     2021-01-07 [1] CRAN (R 3.6.3)                       
# SQUAREM                2021.1     2021-01-13 [1] CRAN (R 3.6.3)                       
# startupmsg             0.9.6      2019-03-11 [1] CRAN (R 3.6.1)                       
# statmod                1.4.32     2019-05-29 [1] CRAN (R 3.6.1)                       
# stringi                1.4.3      2019-03-12 [1] CRAN (R 3.6.1)                       
# stringr                1.4.0      2019-02-10 [1] CRAN (R 3.6.1)                       
# SummarizedExperiment   1.14.1     2019-07-31 [1] Bioconductor                         
# survival               3.2-3      2020-06-13 [2] CRAN (R 3.6.3)                       
# sva                    3.32.1     2019-05-22 [1] Bioconductor                         
# sys                    3.3        2019-08-21 [1] CRAN (R 3.6.1)                       
# systemfonts            0.1.1      2019-07-01 [1] CRAN (R 3.6.1)                       
# tclust                 1.4-2      2020-09-29 [1] CRAN (R 3.6.3)                       
# tensor                 1.5        2012-05-05 [1] CRAN (R 3.6.3)                       
# testthat               2.2.1      2019-07-25 [1] CRAN (R 3.6.1)                       
# TFisher                0.2.0      2018-03-21 [1] CRAN (R 3.6.3)                       
# TH.data                1.0-10     2019-01-21 [1] CRAN (R 3.6.3)                       
# threejs                0.3.3      2020-01-21 [1] CRAN (R 3.6.3)                       
# tibble               * 3.0.5      2021-01-15 [1] CRAN (R 3.6.3)                       
# tictoc                 1.0        2014-06-17 [1] CRAN (R 3.6.3)                       
# tidygraph              1.1.2      2019-02-18 [1] CRAN (R 3.6.1)                       
# tidyr                  1.0.0      2019-09-11 [1] CRAN (R 3.6.1)                       
# tidyselect             1.1.0      2020-05-11 [1] CRAN (R 3.6.3)                       
# tidyverse              1.2.1      2017-11-14 [1] CRAN (R 3.6.1)                       
# timeDate               3043.102   2018-02-21 [1] CRAN (R 3.6.3)                       
# tinytex                0.15       2019-08-07 [1] CRAN (R 3.6.1)                       
# tmvnsim                1.0-2      2016-12-15 [1] CRAN (R 3.6.3)                       
# topGO                  2.36.0     2019-05-02 [1] Bioconductor                         
# triebeard              0.3.0      2016-08-04 [1] CRAN (R 3.6.1)                       
# tsne                   0.1-3      2016-07-15 [1] CRAN (R 3.6.1)                       
# TSP                    1.1-7      2019-05-22 [1] CRAN (R 3.6.1)                       
# TTR                    0.23-6     2019-12-15 [2] CRAN (R 3.6.3)                       
# tweenr                 1.0.1      2018-12-14 [1] CRAN (R 3.6.1)                       
# UpSetR                 1.4.0      2019-05-22 [1] CRAN (R 3.6.1)                       
# urltools               1.7.3      2019-04-14 [1] CRAN (R 3.6.1)                       
# usethis                1.5.1      2019-07-04 [1] CRAN (R 3.6.1)                       
# utf8                   1.1.4      2018-05-24 [1] CRAN (R 3.6.1)                       
# uuid                   0.1-2      2015-07-28 [1] CRAN (R 3.6.1)                       
# uwot                   0.1.10     2020-12-15 [1] CRAN (R 3.6.3)                       
# vcd                    1.4-4      2017-12-06 [1] CRAN (R 3.6.1)                       
# vctrs                  0.3.6      2020-12-17 [1] CRAN (R 3.6.3)                       
# veccompare             0.1.0      2017-09-15 [1] CRAN (R 3.6.1)                       
# VennDiagram            1.6.20     2018-03-28 [1] CRAN (R 3.6.1)                       
# VGAM                   1.1-1      2019-02-18 [1] CRAN (R 3.6.1)                       
# vipor                  0.4.5      2017-03-22 [1] CRAN (R 3.6.1)                       
# viridis                0.5.1      2018-03-29 [1] CRAN (R 3.6.1)                       
# viridisLite            0.3.0      2018-02-01 [1] CRAN (R 3.6.1)                       
# waldo                  0.2.3      2020-11-09 [1] CRAN (R 3.6.3)                       
# webr                   0.1.4.1    2019-10-01 [1] Github (cardiomoon/webr@0b3c8c1)     
# webshot                0.5.1      2018-09-28 [1] CRAN (R 3.6.1)                       
# whisker                0.4        2019-08-28 [1] CRAN (R 3.6.1)                       
# withr                  2.1.2      2018-03-15 [1] CRAN (R 3.6.1)                       
# WriteXLS               5.0.0      2019-05-25 [1] CRAN (R 3.6.1)                       
# xfun                   0.9        2019-08-21 [1] CRAN (R 3.6.1)                       
# XML                    3.98-1.20  2019-06-06 [1] CRAN (R 3.6.1)                       
# xml2                   1.2.2      2019-08-09 [1] CRAN (R 3.6.1)                       
# xopen                  1.0.0      2018-09-17 [1] CRAN (R 3.6.1)                       
# xtable                 1.8-4      2019-04-21 [1] CRAN (R 3.6.1)                       
# xts                    0.12-0     2020-01-19 [2] CRAN (R 3.6.3)                       
# XVector                0.24.0     2019-05-02 [1] Bioconductor                         
# yaml                   2.2.0      2018-07-25 [1] CRAN (R 3.6.1)                       
# zeallot                0.1.0      2018-01-28 [1] CRAN (R 3.6.1)                       
# zip                    2.0.4      2019-09-01 [1] CRAN (R 3.6.1)                       
# zlibbioc               1.30.0     2019-05-02 [1] Bioconductor                         
# zoo                    1.8-6      2019-05-28 [1] CRAN (R 3.6.1)                       
# ztable                 0.2.0      2018-07-22 [1] CRAN (R 3.6.1)
```

-------------------------------------------------------------------------------------------------------------------
